@extends('adminlte::page')
@section('title', 'Rapor '.$report['identity']['nama'])
@section('content_header') @stop
@section('content')
@include('asrama._alerts')
@php $heroTitle='Rapor · '.$report['identity']['nama'];$heroDescription=$report['identity']['kelas'].' · '.$report['identity']['tahun_pelajaran'].' · Semester '.$semester;$heroAction='<a target="_blank" class="btn btn-light" href="'.route('asrama.rapor.print',$rapor).'"><i class="fas fa-print mr-1"></i> Preview Cetak</a>'; @endphp
@include('asrama._hero')
<div class="row">
<div class="col-lg-8"><div class="asrama-panel"><div class="asrama-panel__header"><div><h3>Nilai Mata Pelajaran</h3><p>{{ $report['summary']['jumlah_mapel'] }} mapel · jumlah {{ $report['summary']['jumlah'] }} · rata-rata {{ $report['summary']['rata_rata']??'-' }}</p></div></div>
<div class="table-responsive"><table class="table asrama-table"><thead><tr><th>No</th><th>Mata Pelajaran</th><th>Nilai</th><th>Terbilang Arab</th></tr></thead><tbody>
@forelse($report['scores'] as $index=>$score)<tr><td>{{ $index+1 }}</td><td><div class="asrama-arab">{{ $score['nama_arab'] }}</div><small>{{ $score['nama_latin'] }}</small></td><td><strong>{{ $score['nilai']??'-' }}</strong></td><td class="asrama-arab">{{ $score['nilai_arab'] }}</td></tr>@empty<tr><td colspan="4" class="asrama-empty"><i class="fas fa-pen"></i>Nilai mapel belum diinput.</td></tr>@endforelse
</tbody></table></div></div></div>
<div class="col-lg-4"><form method="post" action="{{ route('asrama.rapor.update',$anggota) }}" class="asrama-panel asrama-form" data-asrama-loading data-loading-title="Menyimpan draft rapor">@csrf @method('PUT')<input type="hidden" name="semester" value="{{ $semester }}"><div class="asrama-panel__header"><div><h3>Komponen Rapor</h3><p>Sikap, kehadiran, dan keputusan.</p></div></div><div class="asrama-panel__body">
@if($rapor->status==='terbit')<div class="alert alert-success"><i class="fas fa-lock mr-1"></i> Rapor sudah terbit dan terkunci.</div>@endif
<div class="row"><div class="col-4"><label>Kebersihan</label><input type="number" step=".25" min="0" max="10" name="nilai_kebersihan" class="form-control" value="{{ old('nilai_kebersihan',$rapor->nilai_kebersihan) }}" @disabled($rapor->status==='terbit')></div><div class="col-4"><label>Kelakuan</label><input type="number" step=".25" min="0" max="10" name="nilai_kelakuan" class="form-control" value="{{ old('nilai_kelakuan',$rapor->nilai_kelakuan) }}" @disabled($rapor->status==='terbit')></div><div class="col-4"><label>Kerajinan</label><input type="number" step=".25" min="0" max="10" name="nilai_kerajinan" class="form-control" value="{{ old('nilai_kerajinan',$rapor->nilai_kerajinan) }}" @disabled($rapor->status==='terbit')></div></div>
<hr><div class="row"><div class="col-4"><label>Sakit</label><input required type="number" min="0" name="sakit" class="form-control" value="{{ old('sakit',$rapor->sakit) }}" @disabled($rapor->status==='terbit')></div><div class="col-4"><label>Izin</label><input required type="number" min="0" name="izin" class="form-control" value="{{ old('izin',$rapor->izin) }}" @disabled($rapor->status==='terbit')></div><div class="col-4"><label>Lain-lain</label><input required type="number" min="0" name="lain_lain" class="form-control" value="{{ old('lain_lain',$rapor->lain_lain) }}" @disabled($rapor->status==='terbit')></div></div>
<div class="form-group mt-3"><label>Predikat</label><input name="predikat" class="form-control" placeholder="Sangat Baik / جيد جدا" value="{{ old('predikat',$rapor->predikat) }}" @disabled($rapor->status==='terbit')></div><div class="form-group"><label>Keputusan</label><input name="keputusan" class="form-control" placeholder="Naik / منقول" value="{{ old('keputusan',$rapor->keputusan) }}" @disabled($rapor->status==='terbit')></div><div class="form-group"><label>Catatan wali</label><textarea name="catatan_wali" class="form-control" @disabled($rapor->status==='terbit')>{{ old('catatan_wali',$rapor->catatan_wali) }}</textarea></div>
<div class="form-group"><label>Tanggal rapor</label><input type="date" name="tanggal_rapor" class="form-control" value="{{ old('tanggal_rapor',$rapor->tanggal_rapor?->toDateString()) }}" @disabled($rapor->status==='terbit')></div><div class="form-group"><label>Tanggal Hijriah (Arab)</label><input dir="rtl" name="tanggal_hijriah" class="form-control asrama-arab" value="{{ old('tanggal_hijriah',$rapor->tanggal_hijriah) }}" @disabled($rapor->status==='terbit')></div>
@if($rapor->status!=='terbit')<button class="btn btn-info btn-block"><i class="fas fa-save mr-1"></i> Simpan Draft</button>@endif
</div></form>
@if($rapor->status!=='terbit')@can('publish-rapor-asrama')<form method="post" action="{{ route('asrama.rapor.publish',$rapor) }}" data-asrama-loading data-confirm="Terbitkan dan kunci rapor ini?">@csrf<button class="btn btn-success btn-block mb-3"><i class="fas fa-lock mr-1"></i> Terbitkan Rapor</button></form>@endcan
@else @can('publish-rapor-asrama')<form method="post" action="{{ route('asrama.rapor.unpublish',$rapor) }}" data-asrama-loading data-confirm="Batalkan terbit agar nilai dapat diubah?">@csrf<button class="btn btn-outline-danger btn-block mb-3"><i class="fas fa-unlock mr-1"></i> Batalkan Terbit</button></form>@endcan @endif
</div></div>
@include('asrama._scripts')
@stop
@section('css') @include('asrama._styles') @stop
