@extends('adminlte::page')
@section('title', 'Catat Surat Masuk')
@php($editing = $item->exists)
@section('content_header')
<div class="row mb-2"><div class="col-sm-6"><h1><i class="fas fa-{{ $editing ? 'edit' : 'plus-circle' }} text-primary"></i> {{ $editing ? 'Edit' : 'Catat' }} Surat Masuk</h1></div><div class="col-sm-6"><ol class="breadcrumb float-sm-right"><li class="breadcrumb-item"><a href="{{ route('admin.tata-usaha.surat-masuk.index') }}">Surat Masuk</a></li><li class="breadcrumb-item active">{{ $editing ? 'Edit' : 'Catat' }}</li></ol></div></div>
@stop
@section('content')
<div class="tu-surat-form"><div class="card bg-gradient-primary text-white mb-4"><div class="card-body"><h3 class="mb-1">{{ $editing ? 'Perbarui Data Surat' : 'Pencatatan Surat Masuk' }}</h3><p class="mb-0">PTSP hanya mengisi data dasar surat. Isi disposisi diisi manual oleh Kepala TU/Kepala Madrasah.</p></div></div>
<div class="card card-outline card-primary"><div class="card-header"><h3 class="card-title"><i class="fas fa-file-alt mr-1"></i> Data Surat Masuk</h3></div><form method="post" enctype="multipart/form-data" action="{{ $editing ? route('admin.tata-usaha.surat-masuk.update', $item) : route('admin.tata-usaha.surat-masuk.store') }}"><div class="card-body">@csrf @if($editing) @method('PUT') @endif
    @if($editing)<div class="alert alert-info"><i class="fas fa-hashtag mr-1"></i> Nomor berkas: <strong>{{ $item->nomor_berkas }}</strong></div>@endif
    <div class="form-row"><div class="form-group col-md-6"><label>Tanggal/Nomor <span class="text-danger">*</span></label><input name="tanggal_nomor" class="form-control @error('tanggal_nomor') is-invalid @enderror" value="{{ old('tanggal_nomor', $item->tanggal_nomor) }}" placeholder="Contoh: 21 September 2026 / 001/MA/IX/2026" required>@error('tanggal_nomor')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="form-group col-md-6"><label>Diterima Tanggal <span class="text-danger">*</span></label><input type="date" name="diterima_tanggal" class="form-control @error('diterima_tanggal') is-invalid @enderror" value="{{ old('diterima_tanggal', $item->diterima_tanggal?->format('Y-m-d')) }}" required>@error('diterima_tanggal')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="form-group position-relative"><label for="asal">Asal <span class="text-danger">*</span></label><input id="asal" name="asal" autocomplete="off" class="form-control @error('asal') is-invalid @enderror" value="{{ old('asal', $item->asal) }}" placeholder="Cari universitas, sekolah, atau ketik instansi baru" required><small class="form-text text-muted"><i class="fas fa-search mr-1"></i>Autocomplete mencari referensi sekolah, perguruan tinggi, PPDB, lulusan, dan riwayat surat masuk. Nama baru langsung tersimpan pada record surat dan akan muncul dari riwayat.</small><div id="asalSuggestions" class="list-group position-absolute w-100 shadow-sm" style="z-index:20;display:none"></div>@error('asal')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="form-group"><label>Isi Ringkasan <span class="text-danger">*</span></label><textarea name="isi_ringkasan" rows="5" class="form-control @error('isi_ringkasan') is-invalid @enderror" required>{{ old('isi_ringkasan', $item->isi_ringkasan) }}</textarea>@error('isi_ringkasan')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="form-group"><label>Surat Masuk <small class="text-muted">(opsional, PDF/JPG/PNG/DOC/DOCX maksimal 10 MB)</small></label><input type="file" name="surat_masuk" class="form-control-file @error('surat_masuk') is-invalid @enderror" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx">@if($item->surat_masuk_nama)<small class="d-block mt-2">File saat ini: <a href="{{ route('admin.tata-usaha.surat-masuk.download', [$item, 'surat-masuk']) }}">{{ $item->surat_masuk_nama }}</a></small>@endif @error('surat_masuk')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
    <div class="alert alert-light border mb-0"><i class="fas fa-info-circle text-primary mr-1"></i> Setelah disimpan, lembar disposisi dapat dicetak. Kepala TU/Kepala Madrasah mengisi bagian disposisi secara manual.</div>
</div><div class="card-footer"><button class="btn btn-primary"><i class="fas fa-save mr-1"></i> Simpan Data</button> <a href="{{ $editing ? route('admin.tata-usaha.surat-masuk.show', $item) : route('admin.tata-usaha.surat-masuk.index') }}" class="btn btn-secondary">Batal</a></div></form></div></div>
@stop
@section('js')<script>
$(function(){const input=document.getElementById('asal'),box=document.getElementById('asalSuggestions');let timer;function hide(){box.style.display='none';box.innerHTML='';}input.addEventListener('input',function(){clearTimeout(timer);const q=this.value.trim();if(q.length<2){hide();return}timer=setTimeout(()=>fetch('{{ route('admin.tata-usaha.surat-masuk.asal-suggestions') }}?q='+encodeURIComponent(q),{headers:{'Accept':'application/json'}}).then(r=>r.json()).then(items=>{box.innerHTML='';if(!items.length){hide();return}items.forEach(item=>{const a=document.createElement('button');a.type='button';a.className='list-group-item list-group-item-action text-left';a.innerHTML='<strong>'+escapeHtml(item.nama)+'</strong><small class="d-block text-muted">'+escapeHtml(item.sumber||item.jenis||'Referensi')+'</small>';a.addEventListener('click',()=>{input.value=item.nama;hide()});box.appendChild(a)});box.style.display='block'}).catch(hide),250)});document.addEventListener('click',e=>{if(!e.target.closest('#asalSuggestions')&&!e.target.closest('#asal'))hide()});function escapeHtml(v){const d=document.createElement('div');d.textContent=v||'';return d.innerHTML}});
</script>@endsection
