<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <meta name="theme-color" content="#123787">
    <title>Monitor Jadwal Belajar | SIMANSA</title>
    <link rel="icon" href="{{ asset('favicon.ico') }}">
    <link rel="stylesheet" href="{{ asset('vendor/fontawesome-free/css/all.min.css') }}">
    <style>
        :root{--blue:#2563eb;--teal:#0f766e;--ink:#10213d;--muted:#64748b;--line:#dbe5f2}*{box-sizing:border-box}html,body{min-height:100%;margin:0}body{font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;color:var(--ink);background:#eef5ff}.piket-monitor{max-width:1920px;min-height:100dvh;margin:auto;padding:clamp(10px,1.4vw,24px);background:radial-gradient(circle at 92% 0,rgba(45,212,191,.16),transparent 24%),radial-gradient(circle at 0 40%,rgba(59,130,246,.14),transparent 22%)}
        .piket-top{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:clamp(13px,1.3vw,22px);border-radius:20px;background:linear-gradient(115deg,#1d4ed8,#2563eb 50%,#0f766e);color:#fff;box-shadow:0 16px 36px rgba(37,99,235,.24)}.piket-brand{display:flex;align-items:center;gap:11px}.piket-brand img{width:42px;height:42px;padding:4px;border-radius:12px;background:#fff;object-fit:contain}.piket-brand small,.piket-brand strong{display:block}.piket-brand small{font-size:10px;font-weight:800;letter-spacing:.1em}.piket-brand strong{margin-top:2px;font-size:clamp(17px,1.6vw,27px);line-height:1.05}.piket-actions{display:flex;align-items:center;gap:13px}.piket-clock{text-align:right}.piket-clock strong{display:block;font-size:clamp(23px,2.4vw,42px);line-height:.92;font-variant-numeric:tabular-nums}.piket-clock span{font-size:10px;opacity:.86}.piket-fullscreen{width:42px;height:42px;border:1px solid rgba(255,255,255,.34);border-radius:11px;background:rgba(255,255,255,.13);color:#fff;cursor:pointer;font-size:16px}.piket-fullscreen:hover{background:rgba(255,255,255,.25)}
        .piket-focus{margin:14px 0;padding:clamp(13px,1.2vw,21px);border:1px solid #bfd5ff;border-left:7px solid var(--blue);border-radius:17px;background:#fff;box-shadow:0 8px 22px rgba(15,23,42,.06)}.piket-focus.is-break{border-color:#fed7aa;border-left-color:#f59e0b;background:#fffaf0}.piket-focus-label{font-size:11px;font-weight:900;letter-spacing:.08em;color:var(--blue)}.is-break .piket-focus-label{color:#b45309}.piket-focus-main{margin:3px 0;font-size:clamp(20px,2vw,32px);font-weight:900}.piket-focus-meta{font-size:clamp(12px,1.1vw,16px);color:var(--muted)}.piket-progress{height:8px;margin-top:12px;overflow:hidden;border-radius:99px;background:#dbeafe}.is-break .piket-progress{background:#ffedd5}.piket-progress span{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,var(--blue),#14b8a6)}.is-break .piket-progress span{background:linear-gradient(90deg,#f59e0b,#f97316)}
        .piket-section{padding:clamp(12px,1.2vw,20px);border:1px solid var(--line);border-radius:17px;background:#fff;box-shadow:0 8px 22px rgba(15,23,42,.05)}.piket-section-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:12px;font-size:clamp(13px,1.1vw,17px);font-weight:900}.piket-count{min-width:28px;padding:3px 8px;border-radius:99px;background:#dbeafe;color:#1d4ed8;text-align:center;font-size:12px}.piket-classes{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:9px}.piket-class{position:relative;overflow:hidden;padding:10px 11px 10px 42px;border:1px solid #e2e8f0;border-radius:12px;background:linear-gradient(120deg,#fff,#eff6ff)}.piket-class i{position:absolute;top:12px;left:12px;color:#2563eb}.piket-class:nth-child(6n+2){background:linear-gradient(120deg,#fff,#ecfdf5)}.piket-class:nth-child(6n+2) i,.piket-class:nth-child(6n+2) .piket-kelas{color:#059669}.piket-class:nth-child(6n+3){background:linear-gradient(120deg,#fff,#f5f3ff)}.piket-class:nth-child(6n+3) i,.piket-class:nth-child(6n+3) .piket-kelas{color:#7c3aed}.piket-class:nth-child(6n+4){background:linear-gradient(120deg,#fff,#fff7ed)}.piket-class:nth-child(6n+4) i,.piket-class:nth-child(6n+4) .piket-kelas{color:#ea580c}.piket-kelas{font-size:11px;font-weight:900;color:#2563eb}.piket-mapel{margin:2px 0;font-size:14px;font-weight:900}.piket-guru{overflow:hidden;color:var(--muted);font-size:11px;text-overflow:ellipsis;white-space:nowrap}.piket-empty{padding:10px 0;color:var(--muted);font-size:14px}.piket-timeline{display:flex;gap:8px;overflow-x:auto;margin-top:14px;padding:11px;border:1px solid var(--line);border-radius:15px;background:#fff}.piket-slot{min-width:120px;padding:8px;border:1px solid #e2e8f0;border-radius:10px;background:#f8fafc;color:var(--muted);font-size:11px}.piket-slot strong,.piket-slot small{display:block}.piket-slot strong{color:var(--ink);font-size:12px}.piket-slot.current{border-color:#2563eb;background:linear-gradient(135deg,#2563eb,#3b82f6);color:#fff}.piket-slot.current strong{color:#fff}.piket-slot.break{background:#fffaf0;border-color:#fed7aa}.piket-slot.current.break{border-color:#f59e0b;background:linear-gradient(135deg,#f59e0b,#f97316)}.piket-footer{padding:12px 0 2px;color:#64748b;text-align:center;font-size:10px;letter-spacing:.06em}
        @media(max-width:600px){.piket-monitor{padding:10px}.piket-top{align-items:flex-start}.piket-brand img{display:none}.piket-brand small{font-size:8px}.piket-brand strong{font-size:16px}.piket-clock strong{font-size:21px}.piket-fullscreen{display:none}.piket-classes{grid-template-columns:1fr}.piket-focus{margin:10px 0}.piket-timeline{margin-top:10px}}
    </style>
</head>
<body>
<main class="piket-monitor">
    <header class="piket-top">
        <div class="piket-brand"><img src="{{ asset('favicon.ico') }}" alt="Logo SIMANSA"><div><small><i class="fas fa-circle"></i> MONITOR GURU PIKET</small><strong id="monitorDay">Memuat jadwal…</strong></div></div>
        <div class="piket-actions"><div class="piket-clock"><strong id="monitorClock">--:--:--</strong><span>{{ $tahun?->nama ?? 'Tahun pelajaran belum aktif' }} · Semester {{ $semester }} · WIB</span></div><button type="button" class="piket-fullscreen" id="fullscreenButton" title="Layar penuh"><i class="fas fa-expand"></i></button></div>
    </header>
    <section class="piket-focus" id="monitorFocus" aria-live="polite"></section>
    <section class="piket-section"><div class="piket-section-head"><span><i class="fas fa-chalkboard-teacher text-primary"></i> Kegiatan kelas saat ini</span><span class="piket-count" id="monitorCount">0</span></div><div class="piket-classes" id="monitorClasses"></div></section>
    <section class="piket-timeline" id="monitorTimeline" aria-label="Urutan jam pelajaran hari ini"></section>
    <footer class="piket-footer">SIMANSA · MONITOR PEMBELAJARAN LANGSUNG · Halaman ini diperbarui otomatis</footer>
</main>
<script>
(() => {
    const slots=@json($slots),day=@json($hari),days={senin:'Senin',selasa:'Selasa',rabu:'Rabu',kamis:'Kamis',jumat:'Jumat',sabtu:'Sabtu'};
    const toMinutes=value=>{const [h,m]=value.split(':').map(Number);return h*60+m},escape=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
    const nowParts=()=>Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Jakarta',hour:'2-digit',minute:'2-digit',second:'2-digit',weekday:'long',hourCycle:'h23'}).formatToParts(new Date()).filter(p=>p.type!=='literal').map(p=>[p.type,p.value]));
    const icon=mapel=>{const m=String(mapel).toLowerCase();return m.includes('matematika')||m.includes('fisika')||m.includes('kimia')?'fa-square-root-alt':m.includes('bahasa')||m.includes('sejarah')?'fa-book-open':m.includes('qur')||m.includes('fiq')||m.includes('tahfidz')?'fa-mosque':m.includes('informatika')?'fa-laptop-code':'fa-lightbulb'};
    let priorDay=null;
    function render(){const now=nowParts(),minutes=Number(now.hour)*60+Number(now.minute),current=slots.find(slot=>minutes>=toMinutes(slot.mulai)&&minutes<toMinutes(slot.selesai)),next=slots.find(slot=>minutes<toMinutes(slot.mulai)),nextLesson=slots.find(slot=>slot.tipe==='pelajaran'&&minutes<toMinutes(slot.mulai)),focus=document.getElementById('monitorFocus'),classes=document.getElementById('monitorClasses');document.getElementById('monitorClock').textContent=`${now.hour}:${now.minute}:${now.second}`;document.getElementById('monitorDay').textContent=day?`${days[day]} · Jadwal Hari Ini`:'Tidak ada jadwal belajar hari ini';if(priorDay&&priorDay!==now.weekday)location.reload();priorDay=now.weekday;
        if(current){const breakTime=current.tipe!=='pelajaran',total=Math.max(toMinutes(current.selesai)-toMinutes(current.mulai),1),progress=Math.min(100,Math.max(0,(minutes-toMinutes(current.mulai))*100/total));focus.classList.toggle('is-break',breakTime);focus.innerHTML=`<div class="piket-focus-label"><i class="fas ${breakTime?'fa-coffee':'fa-circle'}"></i> ${breakTime?escape(current.label).toUpperCase():'SEDANG BERLANGSUNG · JAM KE-'+current.jam_ke}</div><div class="piket-focus-main">${current.mulai}–${current.selesai} WIB</div><div class="piket-focus-meta">${breakTime?(nextLesson?`Berikutnya: Jam ke-${nextLesson.jam_ke}, mulai ${nextLesson.mulai} WIB.`:'Tidak ada pembelajaran berikutnya hari ini.'):`${current.kelas.length} kelas sedang mengikuti pembelajaran.`}</div><div class="piket-progress"><span style="width:${progress}%"></span></div>`;const data=breakTime?[]:current.kelas;document.getElementById('monitorCount').textContent=breakTime?'—':data.length;classes.innerHTML=data.length?data.map(item=>`<article class="piket-class"><i class="fas ${icon(item.mapel)}"></i><div class="piket-kelas">${escape(item.kelas)}</div><div class="piket-mapel">${escape(item.mapel)}</div><div class="piket-guru"><i class="fas fa-user-tie"></i> ${escape(item.guru)}</div></article>`).join(''):`<div class="piket-empty">${breakTime?`${escape(current.label)} sedang berlangsung. Silakan bersiap untuk kegiatan berikutnya.`:'Jadwal masih kosong pada jam ini.'}</div>`
        }else{focus.classList.remove('is-break');focus.innerHTML=next?`<div class="piket-focus-label"><i class="fas fa-clock"></i> JADWAL BERIKUTNYA</div><div class="piket-focus-main">${next.mulai}–${next.selesai} WIB</div><div class="piket-focus-meta">${next.tipe==='pelajaran'?'Jam ke-'+next.jam_ke:escape(next.label)} akan dimulai pukul ${next.mulai} WIB.</div>`:'<div class="piket-focus-label"><i class="fas fa-moon"></i> DI LUAR JAM PEMBELAJARAN</div><div class="piket-focus-main">Tidak ada sesi aktif saat ini</div><div class="piket-focus-meta">Monitor akan aktif kembali pada jam belajar berikutnya.</div>';document.getElementById('monitorCount').textContent=0;classes.innerHTML='<div class="piket-empty">Belum ada pembelajaran yang sedang berlangsung.</div>'}document.getElementById('monitorTimeline').innerHTML=slots.map(slot=>`<div class="piket-slot ${slot.tipe!=='pelajaran'?'break':''} ${current===slot?'current':''}"><strong>${slot.tipe==='pelajaran'?'Jam '+slot.jam_ke:escape(slot.label)}</strong><small>${slot.mulai}–${slot.selesai}</small><small>${slot.tipe==='pelajaran'?slot.kelas.length+' kelas':'Waktu jeda'}</small></div>`).join('')||'<span class="piket-empty">Slot jam belum dikonfigurasi untuk hari ini.</span>'}
    document.getElementById('fullscreenButton').addEventListener('click',()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen());render();setInterval(render,1000);setInterval(()=>location.reload(),300000);
})();
</script>
</body>
</html>
