<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <meta name="theme-color" content="#07152f">
    <title>Live Polling OSIS | SIMANSA</title>
    <link rel="icon" href="{{ asset('favicon.ico') }}">
    <link rel="stylesheet" href="{{ asset('vendor/fontawesome-free/css/all.min.css') }}">
    <style>
        :root{color-scheme:dark;--ink:#f8fafc;--muted:#9fb2ce;--line:rgba(148,163,184,.2);--blue:#4f7cff;--cyan:#22d3ee;--green:#34d399;--panel:rgba(10,27,57,.74)}
        *{box-sizing:border-box}html,body{min-height:100%;margin:0}body{font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;color:var(--ink);background:#061126;overflow-x:hidden}
        body:before,body:after{content:"";position:fixed;z-index:-2;border-radius:50%;filter:blur(4px)}body:before{width:55vw;height:55vw;left:-20vw;top:-25vw;background:radial-gradient(circle,rgba(37,99,235,.38),transparent 66%)}body:after{width:48vw;height:48vw;right:-18vw;bottom:-24vw;background:radial-gradient(circle,rgba(13,148,136,.33),transparent 65%)}
        .noise{position:fixed;inset:0;z-index:-1;opacity:.35;background-image:linear-gradient(rgba(255,255,255,.018) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.018) 1px,transparent 1px);background-size:34px 34px;mask-image:linear-gradient(to bottom,#000,transparent)}
        .screen{width:min(1800px,100%);min-height:100vh;margin:auto;padding:clamp(18px,2vw,34px)}
        .topbar{display:flex;align-items:center;justify-content:space-between;gap:24px;margin-bottom:clamp(20px,3vh,36px)}.brand{display:flex;align-items:center;gap:13px}.brand-mark{display:grid;place-items:center;width:62px;height:62px;padding:5px;border:1px solid rgba(255,255,255,.18);border-radius:18px;background:rgba(255,255,255,.96);box-shadow:0 12px 30px rgba(34,211,238,.16)}.brand-mark img{display:block;width:100%;height:100%;object-fit:contain}.brand strong,.brand span{display:block}.brand strong{font-size:20px;letter-spacing:.04em}.brand span{font-size:12px;color:var(--muted)}
        .live-status{display:flex;align-items:center;gap:10px;padding:10px 15px;border:1px solid var(--line);border-radius:999px;background:rgba(10,27,57,.72);font-size:12px;color:var(--muted);backdrop-filter:blur(14px)}.live-status b{color:#fff}.live-dot{width:9px;height:9px;border-radius:50%;background:#fb4b61;box-shadow:0 0 0 0 rgba(251,75,97,.55);animation:pulse 1.7s infinite}.live-status.offline .live-dot{background:#94a3b8;animation:none}
        .hero{display:grid;grid-template-columns:minmax(0,1.3fr) minmax(330px,.7fr);align-items:end;gap:30px;margin-bottom:24px}.eyebrow{display:inline-flex;align-items:center;gap:9px;color:#8be9fb;font-weight:850;font-size:12px;letter-spacing:.13em;text-transform:uppercase}.hero h1{max-width:1050px;margin:12px 0 10px;font-size:clamp(34px,4.2vw,74px);line-height:.96;letter-spacing:-.045em}.hero p{max-width:760px;margin:0;color:var(--muted);font-size:clamp(14px,1.25vw,19px)}
        .countdown{padding:20px 22px;border:1px solid var(--line);border-radius:22px;background:linear-gradient(145deg,rgba(37,99,235,.22),rgba(10,27,57,.72));box-shadow:0 18px 45px rgba(0,0,0,.18);backdrop-filter:blur(16px)}.countdown>span{display:block;color:#8be9fb;font-size:11px;font-weight:800;letter-spacing:.11em;text-transform:uppercase}.countdown strong{display:block;margin:6px 0 2px;font-size:clamp(25px,2.3vw,40px);font-variant-numeric:tabular-nums}.countdown small{color:var(--muted)}
        .metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:24px}.metric{position:relative;overflow:hidden;padding:18px 20px;border:1px solid var(--line);border-radius:18px;background:var(--panel);backdrop-filter:blur(16px)}.metric:after{content:"";position:absolute;width:80px;height:80px;right:-30px;bottom:-40px;border-radius:50%;background:var(--accent,#4f7cff);filter:blur(2px);opacity:.2}.metric span{display:block;color:var(--muted);font-size:11px;font-weight:800;letter-spacing:.07em;text-transform:uppercase}.metric strong{display:block;margin-top:4px;font-size:clamp(25px,2.25vw,38px);font-variant-numeric:tabular-nums}.metric:nth-child(2){--accent:#34d399}.metric:nth-child(3){--accent:#fbbf24}.metric:nth-child(4){--accent:#22d3ee}
        .package-grid{display:grid;grid-template-columns:repeat(var(--columns,2),minmax(0,1fr));gap:18px}.package{position:relative;overflow:hidden;border:1px solid var(--line);border-radius:25px;background:linear-gradient(150deg,rgba(14,39,79,.92),rgba(7,21,47,.9));box-shadow:0 22px 55px rgba(0,0,0,.2)}.package-head{display:flex;align-items:center;gap:16px;padding:19px 21px;border-bottom:1px solid var(--line)}.package-number{display:grid;place-items:center;width:55px;height:55px;flex:0 0 auto;border-radius:17px;background:linear-gradient(145deg,var(--blue),#7657ff);font-size:26px;font-weight:900;box-shadow:0 10px 25px rgba(79,124,255,.25)}.package-title small,.package-title strong{display:block}.package-title small{color:#91a8ca;font-size:10px;font-weight:850;letter-spacing:.1em;text-transform:uppercase}.package-title strong{margin:2px 0;font-size:clamp(18px,1.5vw,26px)}.package-title em{display:block;color:#8be9fb;font-size:12px;font-style:normal}
        .candidates{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;padding:18px}.candidate{min-width:0;text-align:center}.portrait{position:relative;width:100%;aspect-ratio:4/5;overflow:hidden;border:1px solid rgba(255,255,255,.13);border-radius:18px;background:linear-gradient(145deg,#173761,#102543)}.portrait img{width:100%;height:100%;object-fit:cover;display:block}.portrait:after{content:"";position:absolute;inset:auto 0 0;height:34%;background:linear-gradient(transparent,rgba(4,13,29,.84))}.candidate small{display:block;margin-top:9px;color:#62d8ee;font-size:9px;font-weight:900;letter-spacing:.07em;text-transform:uppercase}.candidate strong{display:block;overflow:hidden;margin-top:2px;color:#fff;font-size:clamp(11px,1vw,14px);text-overflow:ellipsis;white-space:nowrap}.candidate span{display:block;color:#91a8ca;font-size:10px}
        .result{padding:2px 20px 21px}.result-value{display:flex;align-items:end;justify-content:space-between;gap:12px;margin-bottom:10px}.result-value span{color:var(--muted);font-size:11px;font-weight:800;text-transform:uppercase}.result-value strong{font-size:clamp(22px,2vw,34px);font-variant-numeric:tabular-nums}.result-value strong small{margin-left:7px;color:#7dd3fc;font-size:13px}.bar{height:13px;overflow:hidden;border-radius:999px;background:rgba(148,163,184,.17)}.bar span{display:block;width:0;height:100%;border-radius:inherit;background:linear-gradient(90deg,var(--blue),var(--cyan),var(--green));box-shadow:0 0 18px rgba(34,211,238,.38);transition:width .65s cubic-bezier(.2,.8,.2,1)}
        .empty{display:grid;place-items:center;min-height:calc(100vh - 150px);text-align:center}.empty-card{max-width:680px;padding:clamp(34px,5vw,70px);border:1px solid var(--line);border-radius:30px;background:var(--panel);box-shadow:0 25px 70px rgba(0,0,0,.25);backdrop-filter:blur(18px)}.empty-icon{display:grid;place-items:center;width:94px;height:94px;margin:auto;border-radius:28px;background:linear-gradient(145deg,rgba(79,124,255,.28),rgba(34,211,238,.14));color:#7dd3fc;font-size:38px}.empty h1{margin:25px 0 10px;font-size:clamp(30px,4vw,52px)}.empty p{margin:0;color:var(--muted);font-size:17px}.empty .brandline{margin-top:28px;color:#64748b;font-size:12px;letter-spacing:.12em;text-transform:uppercase}
        .footer{display:flex;justify-content:space-between;gap:16px;margin-top:20px;color:#7187a7;font-size:11px}.footer strong{color:#9fb2ce}.updated-flash{animation:flash .55s}
        @keyframes pulse{70%{box-shadow:0 0 0 10px rgba(251,75,97,0)}100%{box-shadow:0 0 0 0 rgba(251,75,97,0)}}@keyframes flash{50%{color:#67e8f9;transform:translateY(-2px)}}
        @media(max-width:1100px){.hero{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(2,1fr)}.package-grid{grid-template-columns:1fr}}@media(max-width:620px){.screen{padding:15px}.topbar{align-items:flex-start}.brand span,.live-status .clock-label{display:none}.hero h1{font-size:38px}.metrics{gap:9px}.metric{padding:14px}.metric strong{font-size:24px}.package-head{padding:15px}.candidates{padding:12px;gap:7px}.portrait{border-radius:13px}.footer{flex-direction:column}.countdown{padding:16px}.live-status{padding:9px 11px}}
    </style>
</head>
<body>
<div class="noise"></div>
<main class="screen">
    <header class="topbar">
        <div class="brand"><span class="brand-mark"><img src="{{ $schoolLogo }}" alt="Logo MAN 1 Metro"></span><div><strong>SIMANSA</strong><span>Sistem Informasi MAN 1 Metro</span></div></div>
        <div class="live-status {{ $election ? '' : 'offline' }}" id="liveStatus"><span class="live-dot"></span><b id="liveLabel">{{ $election ? 'LIVE' : 'STANDBY' }}</b><span class="clock-label">Diperbarui</span><span id="updatedAt">{{ now()->format('H:i:s') }}</span></div>
    </header>

    <section id="emptyState" class="empty" {{ $election ? 'hidden' : '' }}>
        <div class="empty-card"><span class="empty-icon"><i class="fas fa-broadcast-tower"></i></span><h1>Belum Ada Live Polling</h1><p>Layar hasil akan aktif otomatis saat panitia membuka pemilihan OSIS pada tahun pelajaran aktif.</p><div class="brandline">Aman • Anonim • Transparan</div></div>
    </section>

    <div id="pollingState" {{ $election ? '' : 'hidden' }}>
        <section class="hero"><div><span class="eyebrow"><i class="fas fa-circle"></i> Suara Demokrasi Siswa</span><h1 id="electionTitle">{{ $initialPolling['title'] ?? 'Live Polling OSIS' }}</h1><p id="electionTheme">{{ $initialPolling['theme'] ?? 'Pilihan hari ini, langkah baik untuk madrasah esok hari.' }}</p></div><aside class="countdown"><span><i class="far fa-clock"></i> Pemungutan suara berakhir dalam</span><strong id="countdown">-- : -- : --</strong><small>Hasil bergerak otomatis tanpa memuat ulang halaman</small></aside></section>
        <section class="metrics"><article class="metric"><span>Total Hak Pilih</span><strong id="voters">{{ number_format($initialPolling['voters'] ?? 0, 0, ',', '.') }}</strong></article><article class="metric"><span>Suara Masuk</span><strong id="voted">{{ number_format($initialPolling['voted'] ?? 0, 0, ',', '.') }}</strong></article><article class="metric"><span>Belum Memilih</span><strong id="remaining">{{ number_format($initialPolling['remaining'] ?? 0, 0, ',', '.') }}</strong></article><article class="metric"><span>Partisipasi</span><strong id="turnout">{{ $initialPolling['turnout'] ?? 0 }}%</strong></article></section>
        <section class="package-grid" id="packageGrid" style="--columns:{{ min(max(count($initialPolling['packages'] ?? []), 1), 3) }}">
            @foreach(($initialPolling['packages'] ?? []) as $package)
            <article class="package" data-package-id="{{ $package['id'] }}"><header class="package-head"><span class="package-number">{{ $package['number'] }}</span><div class="package-title"><small>Paket Kandidat</small><strong>{{ $package['name'] }}</strong><em>{{ $package['slogan'] ?: 'Bersama untuk madrasah' }}</em></div></header><div class="candidates">
                @foreach($package['candidates'] as $candidate)<div class="candidate"><div class="portrait"><img src="{{ $candidate['photo'] }}" alt="Foto {{ $candidate['name'] }}"></div><small>{{ $candidate['role'] }}</small><strong title="{{ $candidate['name'] }}">{{ $candidate['name'] }}</strong><span>{{ $candidate['class'] }}</span></div>@endforeach
            </div><footer class="result"><div class="result-value"><span>Perolehan sementara</span><strong><b data-votes>{{ number_format($package['votes'], 0, ',', '.') }}</b><small data-percentage>{{ $package['percentage'] }}%</small></strong></div><div class="bar"><span data-bar style="width:{{ $package['percentage'] }}%"></span></div></footer></article>
            @endforeach
        </section>
        <footer class="footer"><span>Perolehan ditampilkan secara agregat. Identitas pemilih tidak pernah dipublikasikan.</span><span><strong>LIVE POLLING OSIS</strong> · MAN 1 Metro</span></footer>
    </div>
</main>
<script>
const dataUrl=@json(route('public.osis-polling.data'));let endsAt=@json($initialPolling['ends_at'] ?? null);let requestRunning=false;
const formatNumber=value=>new Intl.NumberFormat('id-ID').format(Number(value||0));
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[char]));
function setMode(active){document.getElementById('emptyState').hidden=active;document.getElementById('pollingState').hidden=!active;document.getElementById('liveStatus').classList.toggle('offline',!active);document.getElementById('liveLabel').textContent=active?'LIVE':'STANDBY'}
function renderPackages(packages){const grid=document.getElementById('packageGrid');grid.style.setProperty('--columns',Math.min(Math.max(packages.length,1),3));grid.innerHTML=packages.map(item=>`<article class="package" data-package-id="${escapeHtml(item.id)}"><header class="package-head"><span class="package-number">${escapeHtml(item.number)}</span><div class="package-title"><small>Paket Kandidat</small><strong>${escapeHtml(item.name)}</strong><em>${escapeHtml(item.slogan||'Bersama untuk madrasah')}</em></div></header><div class="candidates">${item.candidates.map(candidate=>`<div class="candidate"><div class="portrait"><img src="${escapeHtml(candidate.photo)}" alt="Foto ${escapeHtml(candidate.name)}"></div><small>${escapeHtml(candidate.role)}</small><strong title="${escapeHtml(candidate.name)}">${escapeHtml(candidate.name)}</strong><span>${escapeHtml(candidate.class)}</span></div>`).join('')}</div><footer class="result"><div class="result-value"><span>Perolehan sementara</span><strong><b data-votes>${formatNumber(item.votes)}</b><small data-percentage>${escapeHtml(item.percentage)}%</small></strong></div><div class="bar"><span data-bar style="width:${Number(item.percentage)||0}%"></span></div></footer></article>`).join('')}
function updatePolling(data){setMode(data.active);document.getElementById('updatedAt').textContent=data.updated_at||'--:--:--';if(!data.active)return;endsAt=data.ends_at;document.getElementById('electionTitle').textContent=data.title;document.getElementById('electionTheme').textContent=data.theme||'Pilihan hari ini, langkah baik untuk madrasah esok hari.';const knownIds=[...document.querySelectorAll('[data-package-id]')].map(node=>node.dataset.packageId);if(data.packages.some(item=>!knownIds.includes(item.id))||knownIds.length!==data.packages.length)renderPackages(data.packages);['voters','voted','remaining'].forEach(id=>{const node=document.getElementById(id);const next=formatNumber(data[id]);if(node.textContent!==next){node.textContent=next;node.classList.remove('updated-flash');void node.offsetWidth;node.classList.add('updated-flash')}});document.getElementById('turnout').textContent=data.turnout+'%';data.packages.forEach(item=>{const card=document.querySelector(`[data-package-id="${item.id}"]`);if(!card)return;card.querySelector('[data-votes]').textContent=formatNumber(item.votes);card.querySelector('[data-percentage]').textContent=item.percentage+'%';card.querySelector('[data-bar]').style.width=item.percentage+'%'})}
async function refresh(){if(requestRunning)return;requestRunning=true;try{const response=await fetch(dataUrl,{headers:{Accept:'application/json'},cache:'no-store'});if(response.ok)updatePolling(await response.json())}catch(error){document.getElementById('liveLabel').textContent='MENGHUBUNGKAN'}finally{requestRunning=false}}
function tick(){if(!endsAt){document.getElementById('countdown').textContent='-- : -- : --';return}const seconds=Math.max(0,Math.floor((new Date(endsAt).getTime()-Date.now())/1000));const days=Math.floor(seconds/86400),hours=Math.floor(seconds%86400/3600),minutes=Math.floor(seconds%3600/60),secs=seconds%60;document.getElementById('countdown').textContent=(days?days+' HARI · ':'')+[hours,minutes,secs].map(v=>String(v).padStart(2,'0')).join(' : ')}
tick();setInterval(tick,1000);setInterval(()=>{if(!document.hidden)refresh()},4000);
</script>
</body>
</html>
