<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <meta name="theme-color" content="#07152f">
    <title>Live Polling OSIS | SIMANSA</title>
    <link rel="icon" href="{{ asset('favicon.ico') }}">
    <link rel="stylesheet" href="{{ asset('vendor/fontawesome-free/css/all.min.css') }}">
    <style>
        :root{color-scheme:dark;--ink:#f8fafc;--muted:#9fb2ce;--line:rgba(148,163,184,.2);--blue:#4f7cff;--cyan:#22d3ee;--green:#34d399;--panel:rgba(10,27,57,.74);--screen-gap:clamp(7px,1.15vh,13px)}
        *{box-sizing:border-box}html,body{height:100%;margin:0}body{font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;color:var(--ink);background:#061126;overflow:hidden}
        body:before,body:after{content:"";position:fixed;z-index:-2;border-radius:50%;filter:blur(4px)}body:before{width:55vw;height:55vw;left:-20vw;top:-25vw;background:radial-gradient(circle,rgba(37,99,235,.38),transparent 66%)}body:after{width:48vw;height:48vw;right:-18vw;bottom:-24vw;background:radial-gradient(circle,rgba(13,148,136,.33),transparent 65%)}
        .noise{position:fixed;inset:0;z-index:-1;opacity:.35;background-image:linear-gradient(rgba(255,255,255,.018) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.018) 1px,transparent 1px);background-size:34px 34px;mask-image:linear-gradient(to bottom,#000,transparent)}
        .screen{display:grid;grid-template-rows:auto minmax(0,1fr);width:min(1880px,100%);height:100dvh;margin:auto;padding:clamp(10px,1.35vw,22px)}
        .topbar{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-bottom:var(--screen-gap)}.brand{display:flex;align-items:center;gap:10px}.brand-mark{display:grid;place-items:center;width:48px;height:48px;padding:4px;border:1px solid rgba(255,255,255,.18);border-radius:14px;background:rgba(255,255,255,.96);box-shadow:0 10px 24px rgba(34,211,238,.14)}.brand-mark img{display:block;width:100%;height:100%;object-fit:contain}.brand strong,.brand span{display:block}.brand strong{font-size:17px;letter-spacing:.04em}.brand span{font-size:10px;color:var(--muted)}
        .topbar-actions{display:flex;align-items:center;gap:8px}.live-status{display:flex;align-items:center;gap:8px;padding:8px 12px;border:1px solid var(--line);border-radius:999px;background:rgba(10,27,57,.72);font-size:10px;color:var(--muted);backdrop-filter:blur(14px)}.live-status b{color:#fff}.live-dot{width:8px;height:8px;border-radius:50%;background:#fb4b61;box-shadow:0 0 0 0 rgba(251,75,97,.55);animation:pulse 1.7s infinite}.live-status.offline .live-dot{background:#94a3b8;animation:none}.fullscreen-toggle{display:flex;align-items:center;gap:7px;padding:8px 12px;border:1px solid var(--line);border-radius:999px;background:rgba(10,27,57,.72);color:#dbeafe;font:inherit;font-size:10px;cursor:pointer}.fullscreen-toggle:hover{border-color:#60a5fa;background:rgba(37,99,235,.22)}
        #pollingState{display:grid;grid-template-rows:auto auto minmax(0,1fr) auto;gap:var(--screen-gap);min-height:0}#pollingState[hidden]{display:none}
        .hero{display:grid;grid-template-columns:minmax(0,1fr) minmax(270px,.34fr);align-items:center;gap:clamp(16px,2vw,34px)}.eyebrow{display:inline-flex;align-items:center;gap:7px;color:#8be9fb;font-weight:850;font-size:9px;letter-spacing:.13em;text-transform:uppercase}.hero h1{max-width:1100px;margin:4px 0 3px;font-size:clamp(25px,2.5vw,44px);line-height:1;letter-spacing:-.035em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.hero p{max-width:900px;margin:0;color:var(--muted);font-size:clamp(10px,.9vw,14px);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
        .countdown{padding:10px 14px;border:1px solid var(--line);border-radius:15px;background:linear-gradient(145deg,rgba(37,99,235,.22),rgba(10,27,57,.72));box-shadow:0 12px 32px rgba(0,0,0,.16);backdrop-filter:blur(16px)}.countdown>span{display:block;color:#8be9fb;font-size:8px;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.countdown strong{display:block;margin:2px 0 0;font-size:clamp(20px,1.75vw,30px);font-variant-numeric:tabular-nums;line-height:1.1}.countdown small{display:none}
        .metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:var(--screen-gap)}.metric{position:relative;display:flex;align-items:center;justify-content:space-between;gap:10px;overflow:hidden;padding:9px 13px;border:1px solid var(--line);border-radius:13px;background:var(--panel);backdrop-filter:blur(16px)}.metric:after{content:"";position:absolute;width:58px;height:58px;right:-26px;bottom:-34px;border-radius:50%;background:var(--accent,#4f7cff);opacity:.2}.metric span{color:var(--muted);font-size:8px;font-weight:800;letter-spacing:.06em;text-transform:uppercase}.metric strong{font-size:clamp(19px,1.65vw,28px);font-variant-numeric:tabular-nums;line-height:1}.metric:nth-child(2){--accent:#34d399}.metric:nth-child(3){--accent:#fbbf24}.metric:nth-child(4){--accent:#22d3ee}
        .package-grid{display:grid;grid-template-columns:repeat(var(--columns,2),minmax(0,1fr));gap:var(--screen-gap);min-height:0}.package{--pkg-a:#4f7cff;--pkg-b:#7657ff;position:relative;display:grid;grid-template-rows:auto minmax(0,1fr) auto;min-height:0;overflow:hidden;border:1px solid var(--line);border-radius:18px;background:linear-gradient(150deg,color-mix(in srgb,var(--pkg-a) 13%,rgba(10,27,57,.94)),rgba(7,21,47,.92) 52%);box-shadow:0 16px 38px rgba(0,0,0,.18)}.package:nth-child(2){--pkg-a:#0ea5a5;--pkg-b:#22c55e}.package:nth-child(3){--pkg-a:#f59e0b;--pkg-b:#ef4444}.package:nth-child(4){--pkg-a:#d946ef;--pkg-b:#8b5cf6}.package:before{content:"";position:absolute;z-index:2;inset:0 18% auto;height:2px;background:linear-gradient(90deg,transparent,var(--pkg-a),transparent);box-shadow:0 0 16px var(--pkg-a)}.package-head{display:flex;align-items:center;gap:10px;padding:9px 12px;border-bottom:1px solid var(--line)}.package-number{display:grid;place-items:center;width:38px;height:38px;flex:0 0 auto;border-radius:11px;background:linear-gradient(145deg,var(--pkg-a),var(--pkg-b));font-size:18px;font-weight:900;box-shadow:0 8px 20px color-mix(in srgb,var(--pkg-a) 30%,transparent)}.package-title{min-width:0}.package-title small,.package-title strong{display:block}.package-title small{color:#91a8ca;font-size:7px;font-weight:850;letter-spacing:.1em;text-transform:uppercase}.package-title strong{overflow:hidden;margin:1px 0;font-size:clamp(13px,1.1vw,18px);text-overflow:ellipsis;white-space:nowrap}.package-title em{display:block;overflow:hidden;color:#8be9fb;font-size:8px;font-style:normal;text-overflow:ellipsis;white-space:nowrap}
        .candidates{display:grid;grid-template-columns:repeat(3,minmax(0,138px));align-content:center;justify-content:center;gap:clamp(5px,.6vw,10px);min-height:0;padding:clamp(7px,1vh,12px)}.candidate{min-width:0;text-align:center}.portrait{position:relative;width:min(100%,clamp(78px,7.2vw,138px));aspect-ratio:4/5;margin:auto;overflow:hidden;border:1px solid rgba(255,255,255,.13);border-radius:13px;background:linear-gradient(145deg,#173761,#102543)}.portrait img{width:100%;height:100%;object-fit:cover;display:block}.portrait:after{content:"";position:absolute;inset:auto 0 0;height:30%;background:linear-gradient(transparent,rgba(4,13,29,.78))}.candidate small{display:block;margin-top:5px;color:#62d8ee;font-size:7px;font-weight:900;letter-spacing:.06em;text-transform:uppercase}.candidate strong{display:block;overflow:hidden;margin-top:1px;color:#fff;font-size:clamp(8px,.68vw,11px);text-overflow:ellipsis;white-space:nowrap}.candidate span{display:block;color:#91a8ca;font-size:7px}
        .result{padding:7px 12px 10px;border-top:1px solid rgba(148,163,184,.1)}.result-value{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:5px}.result-value span{color:var(--muted);font-size:8px;font-weight:800;text-transform:uppercase}.result-value strong{font-size:clamp(15px,1.35vw,22px);font-variant-numeric:tabular-nums}.result-value strong small{margin-left:5px;color:#7dd3fc;font-size:9px}.bar{height:7px;overflow:hidden;border-radius:999px;background:rgba(148,163,184,.17)}.bar span{display:block;width:0;height:100%;border-radius:inherit;background:linear-gradient(90deg,var(--pkg-a),var(--pkg-b));box-shadow:0 0 14px color-mix(in srgb,var(--pkg-a) 42%,transparent);transition:width .65s cubic-bezier(.2,.8,.2,1)}
        .empty{display:grid;place-items:center;min-height:0;height:100%;text-align:center}.empty-card{max-width:560px;padding:clamp(25px,4vw,52px);border:1px solid var(--line);border-radius:24px;background:var(--panel);box-shadow:0 25px 70px rgba(0,0,0,.25);backdrop-filter:blur(18px)}.empty-icon{display:grid;place-items:center;width:72px;height:72px;margin:auto;border-radius:21px;background:linear-gradient(145deg,rgba(79,124,255,.28),rgba(34,211,238,.14));color:#7dd3fc;font-size:28px}.empty h1{margin:18px 0 8px;font-size:clamp(25px,3vw,42px)}.empty p{margin:0;color:var(--muted);font-size:14px}.empty .brandline{margin-top:20px;color:#64748b;font-size:9px;letter-spacing:.12em;text-transform:uppercase}
        .footer{display:flex;justify-content:space-between;gap:16px;color:#7187a7;font-size:8px}.footer strong{color:#9fb2ce}.updated-flash{animation:flash .55s}
        @keyframes pulse{70%{box-shadow:0 0 0 10px rgba(251,75,97,0)}100%{box-shadow:0 0 0 0 rgba(251,75,97,0)}}@keyframes flash{50%{color:#67e8f9;transform:translateY(-2px)}}
        @media(max-height:760px) and (min-width:901px){:root{--screen-gap:6px}.screen{padding:8px 12px}.brand-mark{width:38px;height:38px;border-radius:11px}.brand span{display:none}.live-status,.fullscreen-toggle{padding:6px 10px}.hero h1{font-size:24px}.countdown{padding:7px 11px}.countdown strong{font-size:19px}.metric{padding:6px 10px}.metric strong{font-size:18px}.package-head{padding:6px 9px}.package-number{width:31px;height:31px;font-size:15px}.candidates{padding:5px}.portrait{width:min(100%,clamp(66px,6.2vw,104px));border-radius:10px}.candidate small{margin-top:3px}.result{padding:5px 9px 7px}.footer{font-size:7px}}
        @media(max-width:900px){html,body{height:auto;min-height:100%}body{overflow-x:hidden;overflow-y:auto}.screen{display:block;height:auto;min-height:100dvh;padding:13px}.topbar{margin-bottom:14px}#pollingState{display:grid;gap:12px}.hero{grid-template-columns:1fr}.hero h1,.hero p{white-space:normal}.metrics{grid-template-columns:repeat(2,1fr)}.metric{padding:10px 12px}.package-grid{grid-template-columns:1fr!important}.package{min-height:auto}.portrait{width:min(100%,138px)}.footer{padding-bottom:8px}}@media(max-width:560px){.brand span,.live-status .clock-label,.fullscreen-toggle span{display:none}.brand-mark{width:40px;height:40px}.topbar-actions{gap:5px}.live-status,.fullscreen-toggle{padding:7px 9px}.hero h1{font-size:27px}.metrics{gap:7px}.metric{display:block}.metric span,.metric strong{display:block}.metric strong{margin-top:4px;font-size:22px}.candidates{grid-template-columns:repeat(3,minmax(0,1fr));gap:5px}.portrait{width:100%;border-radius:10px}.footer{flex-direction:column}}
    </style>
</head>
<body>
<div class="noise"></div>
<main class="screen">
    <header class="topbar">
        <div class="brand"><span class="brand-mark"><img src="{{ $schoolLogo }}" alt="Logo MAN 1 Metro"></span><div><strong>SIMANSA</strong><span>Sistem Informasi MAN 1 Metro</span></div></div>
        <div class="topbar-actions"><div class="live-status {{ $election ? '' : 'offline' }}" id="liveStatus"><span class="live-dot"></span><b id="liveLabel">{{ ($initialPolling['phase'] ?? null) === 'scheduled' ? 'MENUNGGU' : ($election ? 'LIVE' : 'STANDBY') }}</b><span class="clock-label">Diperbarui</span><span id="updatedAt">{{ now()->format('H:i:s') }}</span></div><button type="button" class="fullscreen-toggle" id="fullscreenToggle" title="Tampilkan layar penuh"><i class="fas fa-expand"></i><span>Layar Penuh</span></button></div>
    </header>

    <section id="emptyState" class="empty" {{ $election ? 'hidden' : '' }}>
        <div class="empty-card"><span class="empty-icon"><i class="fas fa-broadcast-tower"></i></span><h1>Belum Ada Live Polling</h1><p>Layar hasil akan aktif otomatis saat panitia membuka pemilihan OSIS pada tahun pelajaran aktif.</p><div class="brandline">Aman • Anonim • Transparan</div></div>
    </section>

    <div id="pollingState" {{ $election ? '' : 'hidden' }}>
        <section class="hero"><div><span class="eyebrow"><i class="fas fa-circle"></i> Suara Demokrasi Siswa</span><h1 id="electionTitle">{{ $initialPolling['title'] ?? 'Live Polling OSIS' }}</h1><p id="electionTheme">{{ $initialPolling['theme'] ?? 'Pilihan hari ini, langkah baik untuk madrasah esok hari.' }}</p></div><aside class="countdown"><span id="countdownLabel"><i class="far fa-clock"></i> {{ ($initialPolling['phase'] ?? null) === 'scheduled' ? 'Pemungutan suara dimulai dalam' : 'Pemungutan suara berakhir dalam' }}</span><strong id="countdown">-- : -- : --</strong><small>Hasil bergerak otomatis tanpa memuat ulang halaman</small></aside></section>
        <section class="metrics"><article class="metric"><span>Total Hak Pilih</span><strong id="voters">{{ number_format($initialPolling['voters'] ?? 0, 0, ',', '.') }}</strong></article><article class="metric"><span>Suara Masuk</span><strong id="voted">{{ number_format($initialPolling['voted'] ?? 0, 0, ',', '.') }}</strong></article><article class="metric"><span>Belum Memilih</span><strong id="remaining">{{ number_format($initialPolling['remaining'] ?? 0, 0, ',', '.') }}</strong></article><article class="metric"><span>Partisipasi</span><strong id="turnout">{{ $initialPolling['turnout'] ?? 0 }}%</strong></article></section>
        <section class="package-grid" id="packageGrid" data-count="{{ count($initialPolling['packages'] ?? []) }}" style="--columns:{{ min(max(count($initialPolling['packages'] ?? []), 1), 4) }}">
            @foreach(($initialPolling['packages'] ?? []) as $package)
            <article class="package" data-package-id="{{ $package['id'] }}"><header class="package-head"><span class="package-number">{{ $package['number'] }}</span><div class="package-title"><small>Paket Kandidat</small><strong>{{ $package['name'] }}</strong><em>{{ $package['slogan'] ?: 'Bersama untuk madrasah' }}</em></div></header><div class="candidates">
                @foreach($package['candidates'] as $candidate)<div class="candidate"><div class="portrait"><img src="{{ $candidate['photo'] }}" alt="Foto {{ $candidate['name'] }}"></div><small>{{ $candidate['role'] }}</small><strong title="{{ $candidate['name'] }}">{{ $candidate['name'] }}</strong><span>{{ $candidate['class'] }}</span></div>@endforeach
            </div><footer class="result"><div class="result-value"><span>Perolehan sementara</span><strong><b data-votes>{{ number_format($package['votes'], 0, ',', '.') }}</b><small data-percentage>{{ $package['percentage'] }}%</small></strong></div><div class="bar"><span data-bar style="width:{{ $package['percentage'] }}%"></span></div></footer></article>
            @endforeach
        </section>
        <footer class="footer"><span>Perolehan ditampilkan secara agregat. Identitas pemilih tidak pernah dipublikasikan.</span><span><strong>LIVE POLLING OSIS</strong> · MAN 1 Metro</span></footer>
    </div>
</main>
<script>
const dataUrl=@json(route('public.osis-polling.data'));let phase=@json($initialPolling['phase'] ?? null);let startsAt=@json($initialPolling['starts_at'] ?? null);let endsAt=@json($initialPolling['ends_at'] ?? null);let requestRunning=false;
const formatNumber=value=>new Intl.NumberFormat('id-ID').format(Number(value||0));
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[char]));
function setMode(active){document.getElementById('emptyState').hidden=active;document.getElementById('pollingState').hidden=!active;document.getElementById('liveStatus').classList.toggle('offline',!active);document.getElementById('liveLabel').textContent=active?(phase==='scheduled'?'MENUNGGU':'LIVE'):'STANDBY'}
function renderPackages(packages){const grid=document.getElementById('packageGrid');grid.dataset.count=packages.length;grid.style.setProperty('--columns',Math.min(Math.max(packages.length,1),4));grid.innerHTML=packages.map(item=>`<article class="package" data-package-id="${escapeHtml(item.id)}"><header class="package-head"><span class="package-number">${escapeHtml(item.number)}</span><div class="package-title"><small>Paket Kandidat</small><strong>${escapeHtml(item.name)}</strong><em>${escapeHtml(item.slogan||'Bersama untuk madrasah')}</em></div></header><div class="candidates">${item.candidates.map(candidate=>`<div class="candidate"><div class="portrait"><img src="${escapeHtml(candidate.photo)}" alt="Foto ${escapeHtml(candidate.name)}"></div><small>${escapeHtml(candidate.role)}</small><strong title="${escapeHtml(candidate.name)}">${escapeHtml(candidate.name)}</strong><span>${escapeHtml(candidate.class)}</span></div>`).join('')}</div><footer class="result"><div class="result-value"><span>Perolehan sementara</span><strong><b data-votes>${formatNumber(item.votes)}</b><small data-percentage>${escapeHtml(item.percentage)}%</small></strong></div><div class="bar"><span data-bar style="width:${Number(item.percentage)||0}%"></span></div></footer></article>`).join('')}
function updatePolling(data){phase=data.phase;startsAt=data.starts_at;endsAt=data.ends_at;setMode(data.active);document.getElementById('updatedAt').textContent=data.updated_at||'--:--:--';if(!data.active)return;document.getElementById('electionTitle').textContent=data.title;document.getElementById('electionTheme').textContent=data.theme||'Pilihan hari ini, langkah baik untuk madrasah esok hari.';const knownIds=[...document.querySelectorAll('[data-package-id]')].map(node=>node.dataset.packageId);if(data.packages.some(item=>!knownIds.includes(item.id))||knownIds.length!==data.packages.length)renderPackages(data.packages);['voters','voted','remaining'].forEach(id=>{const node=document.getElementById(id);const next=formatNumber(data[id]);if(node.textContent!==next){node.textContent=next;node.classList.remove('updated-flash');void node.offsetWidth;node.classList.add('updated-flash')}});document.getElementById('turnout').textContent=data.turnout+'%';data.packages.forEach(item=>{const card=document.querySelector(`[data-package-id="${item.id}"]`);if(!card)return;card.querySelector('[data-votes]').textContent=formatNumber(item.votes);card.querySelector('[data-percentage]').textContent=item.percentage+'%';card.querySelector('[data-bar]').style.width=item.percentage+'%'})}
async function refresh(){if(requestRunning)return;requestRunning=true;try{const response=await fetch(dataUrl,{headers:{Accept:'application/json'},cache:'no-store'});if(response.ok)updatePolling(await response.json())}catch(error){document.getElementById('liveLabel').textContent='MENGHUBUNGKAN'}finally{requestRunning=false}}
function tick(){const waiting=phase==='scheduled',target=waiting?startsAt:endsAt;document.getElementById('countdownLabel').innerHTML=`<i class="far fa-clock"></i> ${waiting?'Pemungutan suara dimulai dalam':'Pemungutan suara berakhir dalam'}`;if(!target){document.getElementById('countdown').textContent='-- : -- : --';return}const seconds=Math.max(0,Math.floor((new Date(target).getTime()-Date.now())/1000));const days=Math.floor(seconds/86400),hours=Math.floor(seconds%86400/3600),minutes=Math.floor(seconds%3600/60),secs=seconds%60;document.getElementById('countdown').textContent=(days?days+' HARI · ':'')+[hours,minutes,secs].map(v=>String(v).padStart(2,'0')).join(' : ')}
document.getElementById('fullscreenToggle').addEventListener('click',async()=>{if(!document.fullscreenElement){await document.documentElement.requestFullscreen?.()}else{await document.exitFullscreen?.()}});
tick();setInterval(tick,1000);setInterval(()=>{if(!document.hidden)refresh()},4000);
</script>
</body>
</html>
