@extends('adminlte::page')
@section('title', $kelas->nama_kelas.' · Asrama')
@section('plugins.Select2', true)
@section('content_header') @stop
@section('content')
@include('asrama._alerts')
@php
    $heroTitle=$kelas->kelasReguler?->nama_kelas ?? $kelas->nama_kelas;
    $heroDescription='Rombel SIMANSA · '.$kelas->tahunPelajaran->nama.' · '.ucfirst($kelas->jenis);
    $heroAction='<a class="btn btn-light" href="'.route('asrama.kelas.index',['tahun_pelajaran_id'=>$kelas->tahun_pelajaran_id]).'"><i class="fas fa-arrow-left mr-1"></i> Daftar Rombel</a>';
@endphp
@include('asrama._hero')
<div class="row">
<div class="col-xl-8">
<div class="asrama-panel"><div class="asrama-panel__header"><div><h3>Santri Rombel</h3><p>Santri berasal dari anggota aktif rombel SIMANSA ini.</p></div><button class="btn btn-sm btn-info" data-toggle="modal" data-target="#assignStudents"><i class="fas fa-sync-alt mr-1"></i> Sinkronkan Santri</button></div>
<div class="table-responsive"><table class="table asrama-table"><thead><tr><th>No</th><th>Santri</th><th>Nomor Induk</th><th>Pengasuh</th><th>Jabatan</th><th></th></tr></thead><tbody>
@forelse($kelas->anggotaAktif->sortBy('santri.siswa.nama_lengkap') as $index=>$item)
<tr><td>{{ $item->nomor_urut ?? $index+1 }}</td><td><strong>{{ $item->santri->siswa->nama_lengkap }}</strong><br><small>NISN {{ $item->santri->siswa->nisn ?: '-' }}</small></td><td><code>{{ $item->santri->nomor_induk_asrama }}</code></td><td>{{ $item->pengasuhAssignment?->rombelPengasuh?->pengasuh?->gtk?->nama_lengkap ?? 'Belum dibagi' }}</td><td>@if($item->is_ketua_kelas)<span class="badge badge-warning">Ketua</span>@else Santri @endif</td><td class="text-right"><form method="post" action="{{ route('asrama.kelas.santri.destroy',[$kelas,$item]) }}" data-asrama-loading data-confirm="Lepas santri ini dari rombel Asrama?" data-loading-title="Melepas santri">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger asrama-icon-button"><i class="fas fa-times"></i></button></form></td></tr>
@empty<tr><td colspan="6" class="asrama-empty"><i class="fas fa-users"></i>Belum ada santri pada rombel ini.</td></tr>@endforelse
</tbody></table></div></div>

<div class="asrama-panel"><div class="asrama-panel__header"><div><h3>Pengasuh Rombel</h3><p>Satu rombel dapat mempunyai dua atau lebih pengasuh; tiap santri memiliki satu pengasuh utama.</p></div><button class="btn btn-sm btn-info" data-toggle="modal" data-target="#addCaregiver"><i class="fas fa-user-plus mr-1"></i> Tambah Pengasuh</button></div>
<div class="table-responsive"><table class="table asrama-table"><thead><tr><th>Pengasuh</th><th>Status</th><th>Santri Binaan</th><th>Aksi</th></tr></thead><tbody>
@forelse($kelas->pengasuhRombel as $caregiver)
<tr><td><strong>{{ $caregiver->pengasuh->gtk->nama_lengkap }}</strong><br><small>{{ $caregiver->pengasuh->jabatan }}</small></td><td>@if($caregiver->is_primary)<span class="asrama-badge asrama-badge--active">Pengasuh utama</span>@else<span class="asrama-badge asrama-badge--muted">Pendamping</span>@endif</td><td>{{ $caregiver->santriAssignments->where('is_active',true)->count() }} santri</td><td><button class="btn btn-sm btn-outline-info" data-toggle="modal" data-target="#assignCaregiver{{ $caregiver->id }}"><i class="fas fa-random mr-1"></i> Bagi Santri</button> <form class="d-inline" method="post" action="{{ route('asrama.kelas.pengasuh.destroy',[$kelas,$caregiver]) }}" data-asrama-loading data-confirm="Lepas pengasuh dari rombel ini?" data-loading-title="Melepas pengasuh">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="fas fa-times"></i></button></form></td></tr>
@empty<tr><td colspan="4" class="asrama-empty"><i class="fas fa-user-tie"></i>Pengasuh rombel belum ditetapkan.</td></tr>@endforelse
</tbody></table></div></div>

<div class="asrama-panel"><div class="asrama-panel__header"><div><h3>Pengampu Mata Pelajaran</h3><p>Pengampu memperoleh menu input nilai sesuai penugasannya.</p></div><button class="btn btn-sm btn-info" data-toggle="modal" data-target="#addTeacher"><i class="fas fa-plus mr-1"></i> Tambah Pengampu</button></div>
<div class="table-responsive"><table class="table asrama-table"><thead><tr><th>Mapel</th><th>Semester</th><th>Pengampu</th><th></th></tr></thead><tbody>
@forelse($kelas->pengampu->sortBy('mapel.urutan') as $item)<tr><td><span class="asrama-arab">{{ $item->mapel->nama_arab }}</span><br><small>{{ $item->mapel->nama_latin }}</small></td><td>{{ $item->semester }}</td><td>{{ $item->asatidz->gtk->nama_lengkap }}</td><td class="text-right"><a class="btn btn-sm btn-outline-info" href="{{ route('asrama.nilai.edit',$item) }}"><i class="fas fa-pen"></i></a> <form class="d-inline" method="post" action="{{ route('asrama.kelas.pengampu.destroy',[$kelas,$item]) }}" data-asrama-loading data-confirm="Hapus penugasan mapel ini?" data-loading-title="Menghapus penugasan">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="fas fa-trash"></i></button></form></td></tr>
@empty<tr><td colspan="4" class="asrama-empty"><i class="fas fa-book"></i>Belum ada pengampu.</td></tr>@endforelse
</tbody></table></div></div>
</div>
<div class="col-xl-4">
<div class="asrama-panel"><div class="asrama-panel__header"><div><h3>Ketua Rombel</h3><p>Mengikuti kebutuhan Asrama.</p></div></div><div class="asrama-panel__body asrama-form"><form method="post" action="{{ route('asrama.kelas.ketua',$kelas) }}" data-asrama-loading data-loading-title="Menetapkan ketua rombel">@csrf<select name="anggota_id" class="form-control asrama-select mb-3" data-placeholder="Belum ditetapkan" data-allow-clear="1"><option value=""></option>@foreach($kelas->anggotaAktif->sortBy('santri.siswa.nama_lengkap') as $item)<option value="{{ $item->id }}" @selected($item->is_ketua_kelas)>{{ $item->santri->siswa->nama_lengkap }}</option>@endforeach</select><button class="btn btn-info btn-block"><i class="fas fa-save mr-1"></i> Simpan Ketua</button></form></div></div>
<div class="asrama-panel"><div class="asrama-panel__header"><div><h3>Konfigurasi</h3><p>Nama rombel tetap mengikuti SIMANSA.</p></div></div><div class="asrama-panel__body"><button class="btn btn-outline-secondary btn-block" data-toggle="modal" data-target="#editClass"><i class="fas fa-cog mr-1"></i> Atur Rombel Asrama</button></div></div>
</div></div>

<div class="modal fade asrama-modal" id="assignStudents"><div class="modal-dialog modal-lg modal-dialog-centered"><form method="post" action="{{ route('asrama.kelas.santri.store',$kelas) }}" class="modal-content asrama-form" data-asrama-loading data-loading-title="Menyinkronkan santri" data-loading-text="Keanggotaan rombel dan akses portal sedang diperbarui.">@csrf
<div class="modal-header"><div><h5 class="modal-title"><i class="fas fa-sync-alt mr-2"></i>Sinkronkan Santri Rombel</h5><small class="text-white-50">Hanya siswa aktif dari {{ $kelas->nama_kelas }} yang dapat dipilih.</small></div><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><label class="asrama-choice mb-3"><input type="checkbox" name="ambil_semua_rombel" value="1" checked> <strong class="d-inline ml-1">Ambil seluruh siswa aktif rombel</strong><small class="d-block mt-1">Pilihan tercepat untuk rombel yang seluruh siswanya tinggal di Asrama.</small></label><div class="form-group mb-0"><label>Atau pilih per siswa</label><select multiple name="siswa_ids[]" class="form-control asrama-select" data-placeholder="Cari siswa">@foreach($availableStudents as $student)<option value="{{ $student->id }}">{{ $student->nama_lengkap }} · {{ $student->nis_lokal ?: $student->nisn }}</option>@endforeach</select></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Batal</button><button class="btn btn-info"><i class="fas fa-sync-alt mr-1"></i> Sinkronkan</button></div></form></div></div>

<div class="modal fade asrama-modal" id="addCaregiver"><div class="modal-dialog modal-lg modal-dialog-centered"><form method="post" action="{{ route('asrama.kelas.pengasuh.store',$kelas) }}" class="modal-content asrama-form" data-asrama-loading data-loading-title="Menambahkan pengasuh rombel">@csrf
<div class="modal-header"><div><h5 class="modal-title"><i class="fas fa-user-tie mr-2"></i>Tambah Pengasuh Rombel</h5><small class="text-white-50">Pengasuh harus sudah terdaftar pada menu Pengasuh & Pengajar.</small></div><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><label>Pengasuh</label><select required name="asrama_asatidz_id" class="form-control asrama-select" data-placeholder="Cari pengasuh"><option value=""></option>@foreach($caregivers as $item)<option value="{{ $item->id }}">{{ $item->gtk->nama_lengkap }}</option>@endforeach</select><label class="asrama-choice mt-3"><input type="checkbox" name="is_primary" value="1"> <strong class="d-inline ml-1">Jadikan pengasuh utama rombel</strong><small class="d-block mt-1">Pengasuh lain tetap dapat membina kelompok santri di rombel yang sama.</small></label></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Batal</button><button class="btn btn-info"><i class="fas fa-plus mr-1"></i> Tambahkan</button></div></form></div></div>

@foreach($kelas->pengasuhRombel as $caregiver)
<div class="modal fade asrama-modal" id="assignCaregiver{{ $caregiver->id }}"><div class="modal-dialog modal-xl modal-dialog-centered"><form method="post" action="{{ route('asrama.kelas.pengasuh.santri',[$kelas,$caregiver]) }}" class="modal-content asrama-form" data-asrama-loading data-loading-title="Membagi santri kepada pengasuh">@csrf
<div class="modal-header"><div><h5 class="modal-title">Santri Binaan · {{ $caregiver->pengasuh->gtk->nama_lengkap }}</h5><small class="text-white-50">Assignment lama santri akan berpindah otomatis ke pengasuh ini.</small></div><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><label class="asrama-choice mb-3"><input type="checkbox" name="semua_santri" value="1"> <strong class="d-inline ml-1">Assign seluruh santri rombel</strong></label><label>Pilih santri tertentu</label><select multiple name="anggota_ids[]" class="form-control asrama-select" data-placeholder="Cari dan pilih santri">@foreach($kelas->anggotaAktif->sortBy('santri.siswa.nama_lengkap') as $member)<option value="{{ $member->id }}" @selected($member->pengasuhAssignment?->asrama_rombel_pengasuh_id===$caregiver->id)>{{ $member->santri->siswa->nama_lengkap }}{{ $member->pengasuhAssignment?' · saat ini '.$member->pengasuhAssignment->rombelPengasuh->pengasuh->gtk->nama_lengkap:'' }}</option>@endforeach</select></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Batal</button><button class="btn btn-info"><i class="fas fa-random mr-1"></i> Simpan Pembagian</button></div></form></div></div>
@endforeach

<div class="modal fade asrama-modal" id="addTeacher"><div class="modal-dialog modal-lg modal-dialog-centered"><form method="post" action="{{ route('asrama.kelas.pengampu.store',$kelas) }}" class="modal-content asrama-form" data-asrama-loading data-loading-title="Menambahkan pengampu">@csrf
<div class="modal-header"><h5 class="modal-title"><i class="fas fa-book-open mr-2"></i>Tambah Pengampu</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="row"><div class="col-12"><label>Mapel</label><select required name="asrama_mapel_id" class="form-control asrama-select" data-placeholder="Cari mapel"><option value=""></option>@foreach($mapels as $mapel)<option value="{{ $mapel->id }}">{{ $mapel->nama_latin }} · {{ $mapel->nama_arab }}</option>@endforeach</select></div><div class="col-md-8 mt-3"><label>Pengampu</label><select required name="asrama_asatidz_id" class="form-control asrama-select" data-placeholder="Cari GTK"><option value=""></option>@foreach($teachers as $item)<option value="{{ $item->id }}">{{ $item->gtk->nama_lengkap }}</option>@endforeach</select></div><div class="col-md-4 mt-3"><label>Semester</label><select required name="semester" class="form-control asrama-select"><option>Ganjil</option><option>Genap</option></select></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Batal</button><button class="btn btn-info"><i class="fas fa-plus mr-1"></i> Tambahkan</button></div></form></div></div>

<div class="modal fade asrama-modal" id="editClass"><div class="modal-dialog modal-lg modal-dialog-centered"><form method="post" action="{{ route('asrama.kelas.update',$kelas) }}" class="modal-content asrama-form" data-asrama-loading data-loading-title="Memperbarui rombel">@csrf @method('PUT')
<div class="modal-header"><div><h5 class="modal-title">Konfigurasi {{ $kelas->nama_kelas }}</h5><small class="text-white-50">Nama dan anggota inti tetap berasal dari SIMANSA.</small></div><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="row"><div class="col-md-6"><label>Rombel SIMANSA</label><input class="form-control" value="{{ $kelas->kelasReguler?->nama_kelas ?? $kelas->nama_kelas }}" disabled></div><div class="col-md-6"><label>Nama Arab</label><input dir="rtl" name="nama_arab" class="form-control asrama-arab" value="{{ $kelas->nama_arab }}"></div><div class="col-md-6 mt-3"><label>Kelompok</label><select name="jenis" class="form-control asrama-select">@foreach(['putra'=>'Putra','putri'=>'Putri','campuran'=>'Campuran'] as $value=>$label)<option value="{{ $value }}" @selected($kelas->jenis===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-12 mt-3"><label>Catatan</label><textarea name="deskripsi" class="form-control">{{ $kelas->deskripsi }}</textarea></div><div class="col-12 mt-3"><div class="custom-control custom-switch"><input id="classActive" type="checkbox" class="custom-control-input" name="is_active" value="1" @checked($kelas->is_active)><label class="custom-control-label" for="classActive">Rombel Asrama aktif</label></div></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Batal</button><button class="btn btn-info"><i class="fas fa-save mr-1"></i> Simpan</button></div></form></div></div>
@include('asrama._scripts')
@stop
@section('css') @include('asrama._styles') @stop
