@extends('adminlte::page')
@section('title', $kelas->nama_kelas.' · Asrama')
@section('content_header') @stop
@section('content')
@include('asrama._alerts')
@php $heroTitle=$kelas->nama_kelas;$heroDescription=$kelas->asrama->nama.' · '.$kelas->tahunPelajaran->nama.' · '.ucfirst($kelas->jenis);$heroAction='<a class="btn btn-light" href="'.route('asrama.kelas.index',['tahun_pelajaran_id'=>$kelas->tahun_pelajaran_id]).'"><i class="fas fa-arrow-left mr-1"></i> Daftar Kelas</a>'; @endphp
@include('asrama._hero')
<div class="row">
<div class="col-lg-8">
<div class="asrama-panel"><div class="asrama-panel__header"><div><h3>Anggota Kelas</h3><p>Assign satu siswa atau seluruh siswa dari rombel reguler.</p></div><button class="btn btn-sm btn-info" data-toggle="modal" data-target="#assignStudents"><i class="fas fa-user-plus mr-1"></i> Assign</button></div>
<div class="table-responsive"><table class="table asrama-table"><thead><tr><th>No</th><th>Santri</th><th>Nomor Induk</th><th>Kelas Reguler</th><th>Jabatan</th><th></th></tr></thead><tbody>
@forelse($kelas->anggotaAktif->sortBy('santri.siswa.nama_lengkap') as $index=>$item)<tr><td>{{ $item->nomor_urut??$index+1 }}</td><td><strong>{{ $item->santri->siswa->nama_lengkap }}</strong><br><small>NISN {{ $item->santri->siswa->nisn }}</small></td><td><code>{{ $item->santri->nomor_induk_asrama }}</code></td><td>{{ $item->santri->siswa->kelasTahunAktif->first()?->nama_kelas??'-' }}</td><td>@if($item->is_ketua_kelas)<span class="badge badge-warning">Ketua Kelas</span>@else Santri @endif</td><td class="text-right"><form method="post" action="{{ route('asrama.kelas.santri.destroy',[$kelas,$item]) }}" onsubmit="return confirm('Keluarkan santri dari kelas asrama?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="fas fa-times"></i></button></form></td></tr>
@empty<tr><td colspan="6" class="asrama-empty"><i class="fas fa-users"></i>Belum ada anggota kelas.</td></tr>@endforelse
</tbody></table></div></div>

<div class="asrama-panel"><div class="asrama-panel__header"><div><h3>Pengampu Mata Pelajaran</h3><p>Penugasan menentukan akses asatidz untuk input nilai.</p></div><button class="btn btn-sm btn-info" data-toggle="modal" data-target="#addTeacher"><i class="fas fa-plus mr-1"></i> Tambah</button></div>
<div class="table-responsive"><table class="table asrama-table"><thead><tr><th>Mapel</th><th>Semester</th><th>Asatidz</th><th>Nilai</th><th></th></tr></thead><tbody>
@forelse($kelas->pengampu->sortBy('mapel.urutan') as $item)<tr><td><span class="asrama-arab">{{ $item->mapel->nama_arab }}</span><br><small>{{ $item->mapel->nama_latin }}</small></td><td>{{ $item->semester }}</td><td>{{ $item->asatidz->gtk->nama_lengkap }}</td><td><a class="btn btn-sm btn-outline-info" href="{{ route('asrama.nilai.edit',$item) }}">Input Nilai</a></td><td><form method="post" action="{{ route('asrama.kelas.pengampu.destroy',[$kelas,$item]) }}" onsubmit="return confirm('Hapus penugasan?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="fas fa-trash"></i></button></form></td></tr>
@empty<tr><td colspan="5" class="asrama-empty"><i class="fas fa-book"></i>Belum ada pengampu.</td></tr>@endforelse
</tbody></table></div></div>
</div>
<div class="col-lg-4">
<div class="asrama-panel"><div class="asrama-panel__header"><div><h3>Wali Kelas</h3><p>Asatidz penanggung jawab kelas.</p></div></div><div class="asrama-panel__body asrama-form"><form method="post" action="{{ route('asrama.kelas.wali',$kelas) }}">@csrf<select name="wali_asatidz_id" class="form-control mb-3"><option value="">Belum ditetapkan</option>@foreach($asatidz as $item)<option value="{{ $item->id }}" @selected($kelas->wali_asatidz_id===$item->id)>{{ $item->gtk->nama_lengkap }}</option>@endforeach</select><button class="btn btn-info btn-block">Simpan Wali</button></form></div></div>
<div class="asrama-panel"><div class="asrama-panel__header"><div><h3>Ketua Kelas</h3><p>Dipilih dari anggota aktif.</p></div></div><div class="asrama-panel__body asrama-form"><form method="post" action="{{ route('asrama.kelas.ketua',$kelas) }}">@csrf<select name="anggota_id" class="form-control mb-3"><option value="">Belum ditetapkan</option>@foreach($kelas->anggotaAktif->sortBy('santri.siswa.nama_lengkap') as $item)<option value="{{ $item->id }}" @selected($item->is_ketua_kelas)>{{ $item->santri->siswa->nama_lengkap }}</option>@endforeach</select><button class="btn btn-info btn-block">Simpan Ketua</button></form></div></div>
<div class="asrama-panel"><div class="asrama-panel__header"><div><h3>Pengaturan Kelas</h3></div></div><div class="asrama-panel__body"><button class="btn btn-outline-secondary btn-block" data-toggle="modal" data-target="#editClass">Edit Kelas</button></div></div>
</div></div>

<div class="modal fade" id="assignStudents"><div class="modal-dialog modal-lg"><form method="post" action="{{ route('asrama.kelas.santri.store',$kelas) }}" class="modal-content asrama-form">@csrf<div class="modal-header"><h5>Assign Santri</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="alert alert-info">Rombel sumber mengambil seluruh siswa aktif dari kelas reguler dan otomatis membuat keanggotaan santri bila belum tersedia.</div><div class="form-group"><label>Ambil seluruh siswa dari rombel reguler</label><select name="sumber_kelas_id" class="form-control"><option value="">Tidak menggunakan rombel</option>@foreach($regularClasses as $item)<option value="{{ $item->id }}">{{ $item->nama_kelas }} · {{ $item->siswaAktif()->count() }} siswa</option>@endforeach</select></div><div class="form-group"><label>Atau pilih siswa individual</label><select multiple size="10" name="siswa_ids[]" class="form-control">@foreach($availableStudents as $student)<option value="{{ $student->id }}">{{ $student->nama_lengkap }} · {{ $student->nis_lokal ?: $student->nisn }}</option>@endforeach</select><small class="text-muted">Keduanya dapat digunakan bersamaan.</small></div></div><div class="modal-footer"><button class="btn btn-info">Assign ke Kelas</button></div></form></div></div>

<div class="modal fade" id="addTeacher"><div class="modal-dialog"><form method="post" action="{{ route('asrama.kelas.pengampu.store',$kelas) }}" class="modal-content asrama-form">@csrf<div class="modal-header"><h5>Tambah Pengampu</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="form-group"><label>Mapel</label><select required name="asrama_mapel_id" class="form-control">@foreach($mapels as $mapel)<option value="{{ $mapel->id }}">{{ $mapel->nama_latin }} · {{ $mapel->nama_arab }}</option>@endforeach</select></div><div class="form-group"><label>Asatidz</label><select required name="asrama_asatidz_id" class="form-control">@foreach($asatidz as $item)<option value="{{ $item->id }}">{{ $item->gtk->nama_lengkap }}</option>@endforeach</select></div><div class="form-group"><label>Semester</label><select required name="semester" class="form-control"><option>Ganjil</option><option>Genap</option></select></div></div><div class="modal-footer"><button class="btn btn-info">Tambahkan</button></div></form></div></div>

<div class="modal fade" id="editClass"><div class="modal-dialog modal-lg"><form method="post" action="{{ route('asrama.kelas.update',$kelas) }}" class="modal-content asrama-form">@csrf @method('PUT')<div class="modal-header"><h5>Edit Kelas</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="row"><div class="col-md-6"><label>Nama kelas</label><input required name="nama_kelas" class="form-control" value="{{ $kelas->nama_kelas }}"></div><div class="col-md-6"><label>Nama Arab</label><input dir="rtl" name="nama_arab" class="form-control asrama-arab" value="{{ $kelas->nama_arab }}"></div><div class="col-md-3 mt-3"><label>Tingkat</label><input type="number" name="tingkat" class="form-control" value="{{ $kelas->tingkat }}"></div><div class="col-md-3 mt-3"><label>Jenis</label><select name="jenis" class="form-control">@foreach(['putra','putri','campuran'] as $v)<option @selected($kelas->jenis===$v)>{{ $v }}</option>@endforeach</select></div><div class="col-md-3 mt-3"><label>Kapasitas</label><input type="number" required name="kapasitas" class="form-control" value="{{ $kelas->kapasitas }}"></div><div class="col-md-3 mt-3"><label>Ruang</label><input name="ruang" class="form-control" value="{{ $kelas->ruang }}"></div><div class="col-12 mt-3"><label>Deskripsi</label><textarea name="deskripsi" class="form-control">{{ $kelas->deskripsi }}</textarea></div><div class="col-12 mt-3"><div class="custom-control custom-switch"><input id="classActive" type="checkbox" class="custom-control-input" name="is_active" value="1" @checked($kelas->is_active)><label class="custom-control-label" for="classActive">Kelas aktif</label></div></div></div></div><div class="modal-footer"><button class="btn btn-info">Simpan</button></div></form></div></div>
@stop
@section('css') @include('asrama._styles') @stop
