@extends('adminlte::page')

@section('title', 'Global Search')
@section('content_header')
<div class="d-flex justify-content-between align-items-center flex-wrap mb-2">
    <div><h1 class="mb-1"><i class="fas fa-search text-primary mr-2"></i>Global Search SIMANSA</h1><p class="text-muted mb-0">Cari siswa, alumni, GTK, dan data orang tua dari satu tempat.</p></div>
</div>
@stop

@section('content')
<div class="global-search-page">
    <div class="search-hero card border-0 shadow-sm mb-4"><div class="card-body p-4 p-lg-5"><div class="small text-uppercase font-weight-bold text-white-50 mb-2">Smart data finder</div><h2 class="text-white mb-2">Temukan data penting dengan cepat</h2><p class="text-white-50 mb-4">Gunakan nama, NISN, NIK, NUPTK, NIP, kode GTK, nomor KK, atau nomor telepon.</p><form method="GET" action="{{ route('admin.global-search.index') }}"><div class="input-group input-group-lg search-input"><input type="search" name="q" value="{{ $query }}" class="form-control" placeholder="Contoh: Ahmad, 009876..., 198..." autofocus><div class="input-group-append"><button class="btn btn-light text-primary font-weight-bold px-4"><i class="fas fa-search mr-2"></i>Cari</button></div></div></form><div class="search-hints mt-3"><span><i class="fas fa-shield-alt mr-1"></i>Hanya dapat diakses pengguna berwenang</span><span><i class="fas fa-database mr-1"></i>Lintas data akademik dan kepegawaian</span></div></div></div>

    @if($query !== '' && mb_strlen($query) < 2)
        <div class="alert alert-warning border-0 shadow-sm"><i class="fas fa-info-circle mr-2"></i>Masukkan minimal 2 karakter untuk memulai pencarian.</div>
    @elseif($query !== '')
        @php($total = $students->count() + $gtks->count() + $parents->count())
        <div class="result-summary d-flex justify-content-between align-items-center flex-wrap mb-3"><div><span class="text-muted">Hasil pencarian untuk</span> <strong>“{{ $query }}”</strong></div><span class="badge badge-primary px-3 py-2">{{ $total }} hasil</span></div>
        <div class="row mb-4"><div class="col-md-4 mb-3 mb-md-0"><div class="metric-card"><span class="metric-icon bg-primary"><i class="fas fa-user-graduate"></i></span><div><small>Siswa & alumni</small><strong>{{ $students->count() }}</strong></div></div></div><div class="col-md-4 mb-3 mb-md-0"><div class="metric-card"><span class="metric-icon bg-success"><i class="fas fa-chalkboard-teacher"></i></span><div><small>GTK</small><strong>{{ $gtks->count() }}</strong></div></div></div><div class="col-md-4"><div class="metric-card"><span class="metric-icon bg-warning"><i class="fas fa-users"></i></span><div><small>Data orang tua</small><strong>{{ $parents->count() }}</strong></div></div></div></div>

        <div class="result-card card card-outline card-primary mb-4"><div class="card-header"><h3 class="card-title"><i class="fas fa-user-graduate mr-2"></i>Siswa dan alumni <span class="badge badge-light ml-2">{{ $students->count() }}</span></h3></div><div class="card-body p-0 table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Nama</th><th>Status / rombel</th><th>Identitas</th><th class="text-right">Aksi</th></tr></thead><tbody>@forelse($students as $student)<tr><td><strong>{{ $student->nama_lengkap }}</strong><small class="d-block text-muted">{{ $student->jenis_kelamin === 'L' ? 'Laki-laki' : 'Perempuan' }}</small></td><td><span class="badge badge-{{ $student->status_siswa === 'aktif' ? 'success' : 'secondary' }}">{{ ucfirst($student->status_siswa ?: '—') }}</span><small class="d-block text-muted mt-1">{{ $student->kelasSaatIni?->nama_kelas ?: 'Alumni / tanpa rombel' }}</small></td><td><small class="d-block">NISN: {{ $student->nisn ?: '—' }}</small><small class="d-block">NIK: {{ $student->nik ?: '—' }}</small></td><td class="text-right"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.siswa.show', $student) }}"><i class="fas fa-arrow-right mr-1"></i>Detail</a></td></tr>@empty<tr><td colspan="4" class="empty-result">Tidak ada data siswa atau alumni yang cocok.</td></tr>@endforelse</tbody></table></div></div>

        <div class="result-card card card-outline card-success mb-4"><div class="card-header"><h3 class="card-title"><i class="fas fa-chalkboard-teacher mr-2"></i>GTK <span class="badge badge-light ml-2">{{ $gtks->count() }}</span></h3></div><div class="card-body p-0 table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Nama GTK</th><th>Status / jenis</th><th>Identitas</th><th class="text-right">Aksi</th></tr></thead><tbody>@forelse($gtks as $gtk)<tr><td><strong>{{ $gtk->nama_lengkap }}</strong><small class="d-block text-muted">{{ $gtk->email ?: 'Email belum diisi' }}</small></td><td><span class="badge badge-{{ $gtk->status_aktif ? 'success' : 'secondary' }}">{{ $gtk->status_aktif ? 'Aktif' : 'Nonaktif' }}</span><small class="d-block text-muted mt-1">{{ $gtk->jenis_ptk ?: ($gtk->kategori_ptk ?: 'GTK') }}</small></td><td><small class="d-block">NIK: {{ $gtk->nik ?: '—' }}</small><small class="d-block">NIP/NUPTK: {{ $gtk->nip ?: ($gtk->nuptk ?: '—') }}</small><small class="d-block">Kode: {{ $gtk->kode_gtk ?: '—' }}</small></td><td class="text-right"><a class="btn btn-sm btn-outline-success" href="{{ route('admin.gtk.show', $gtk) }}"><i class="fas fa-arrow-right mr-1"></i>Detail</a></td></tr>@empty<tr><td colspan="4" class="empty-result">Tidak ada GTK yang cocok.</td></tr>@endforelse</tbody></table></div></div>

        <div class="result-card card card-outline card-warning mb-4"><div class="card-header"><h3 class="card-title"><i class="fas fa-users mr-2"></i>Orang tua siswa <span class="badge badge-light ml-2">{{ $parents->count() }}</span></h3></div><div class="card-body p-0 table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Orang tua yang cocok</th><th>Siswa terkait</th><th>Metadata keluarga</th><th class="text-right">Aksi</th></tr></thead><tbody>@forelse($parents as $row)@php($ortu = $row['ortu'])<tr><td>@foreach($row['matches'] as $match)<div class="mb-1"><strong>{{ $match['nama'] ?: 'Nama belum diisi' }}</strong><span class="badge badge-warning ml-1">{{ $match['peran'] }}</span><small class="d-block text-muted">NIK: {{ $match['identitas'] ?: '—' }}</small></div>@endforeach</td><td><strong>{{ $ortu->siswa?->nama_lengkap ?: 'Siswa tidak ditemukan' }}</strong><small class="d-block text-muted">{{ $ortu->siswa?->kelasSaatIni?->nama_kelas ?: ($ortu->siswa?->status_siswa === 'alumni' ? 'Alumni' : 'Tanpa rombel') }}</small></td><td><small class="d-block">No. KK: {{ $ortu->no_kk ?: '—' }}</small><small class="d-block">Alamat: {{ $ortu->alamat_ortu ?: '—' }}</small></td><td class="text-right">@if($ortu->siswa)<a class="btn btn-sm btn-outline-warning" href="{{ route('admin.siswa.show', $ortu->siswa) }}"><i class="fas fa-arrow-right mr-1"></i>Lihat siswa</a>@endif</td></tr>@empty<tr><td colspan="4" class="empty-result">Tidak ada data orang tua yang cocok.</td></tr>@endforelse</tbody></table></div></div>
    @elseif($query === '')
        <div class="empty-search card border-0 shadow-sm"><div class="card-body text-center py-5"><div class="empty-search-icon"><i class="fas fa-search"></i></div><h4>Mulai pencarian global</h4><p class="text-muted mb-0">Cari berdasarkan nama atau identitas. Hasil akan otomatis dipisahkan menjadi siswa, GTK, dan orang tua.</p></div></div>
    @endif
</div>
@stop

@section('css')
<style>
.global-search-page .search-hero{background:linear-gradient(120deg,#2746c7,#5a45d6 55%,#7438b8);border-radius:16px}.global-search-page .search-input .form-control{border:0;box-shadow:none}.global-search-page .search-hints{display:flex;gap:20px;flex-wrap:wrap;color:rgba(255,255,255,.78);font-size:.78rem}.global-search-page .metric-card{height:100%;display:flex;align-items:center;gap:13px;background:#fff;border:1px solid #e5eaf2;border-radius:12px;padding:15px;box-shadow:0 4px 14px rgba(31,45,61,.06)}.global-search-page .metric-icon{width:42px;height:42px;border-radius:11px;display:grid;place-items:center;color:#fff}.global-search-page .metric-card small,.global-search-page .metric-card strong{display:block}.global-search-page .metric-card small{color:#6c757d;font-size:.78rem}.global-search-page .metric-card strong{font-size:1.45rem;color:#25364a}.global-search-page .result-card{border-radius:12px;overflow:hidden}.global-search-page .result-card .card-header{display:flex;justify-content:space-between;align-items:center}.global-search-page .table thead th{background:#f7f9fc;border-top:0;color:#536273;font-size:.76rem;text-transform:uppercase}.global-search-page .table td{vertical-align:middle}.global-search-page .empty-result{padding:34px;text-align:center;color:#748396}.global-search-page .empty-search{border-radius:16px}.global-search-page .empty-search-icon{width:64px;height:64px;margin:0 auto 16px;border-radius:18px;display:grid;place-items:center;background:#eef2ff;color:#4f46e5;font-size:1.7rem}
</style>
@endsection
