@extends('adminlte::page')
@section('title', 'Laporan '.$election->title)
@section('content_header')
<div class="row mb-2"><div class="col-sm-6"><h1><i class="fas fa-chart-pie text-primary"></i> Laporan Pemilihan OSIM</h1></div><div class="col-sm-6"><ol class="breadcrumb float-sm-right"><li class="breadcrumb-item"><a href="{{ route('admin.osis-election.index') }}">Pemilihan OSIM</a></li><li class="breadcrumb-item active">Laporan</li></ol></div></div>
@stop
@section('content')
<div class="osis-report">
<div class="card bg-gradient-primary text-white mb-4"><div class="card-body d-flex justify-content-between align-items-center flex-wrap"><div><small class="font-weight-bold text-uppercase"><i class="fas fa-file-alt mr-1"></i>Laporan lengkap</small><h2 class="mb-1">{{ $election->title }}</h2><p class="mb-0">{{ $election->starts_at->format('d M Y H:i') }} — {{ $election->ends_at->format('d M Y H:i') }} WIB · Dicetak {{ now()->format('d M Y H:i') }} WIB</p></div><div class="mt-3 mt-md-0"><a href="{{ route('admin.osis-election.report.excel',$election) }}" class="btn btn-success btn-sm"><i class="fas fa-file-excel mr-1"></i>Excel</a><a href="{{ route('admin.osis-election.report.pdf',$election) }}" class="btn btn-danger btn-sm ml-1"><i class="fas fa-file-pdf mr-1"></i>PDF</a><a href="{{ route('admin.osis-election.show',$election) }}" class="btn btn-light btn-sm ml-1"><i class="fas fa-arrow-left mr-1"></i>Panel</a></div></div></div>
<div class="row"><div class="col-md-3 col-6 mb-3"><div class="card card-outline card-primary"><div class="card-body"><small>DPT</small><h3>{{ number_format($total) }}</h3><span>{{ number_format($studentTotal) }} siswa · {{ number_format($gtkTotal) }} GTK</span></div></div></div><div class="col-md-3 col-6 mb-3"><div class="card card-outline card-success"><div class="card-body"><small>Sudah memilih</small><h3 class="text-success">{{ number_format($voted) }}</h3><span>Suara terekam</span></div></div></div><div class="col-md-3 col-6 mb-3"><a class="card card-outline card-warning text-reset text-decoration-none h-100" href="{{ route('admin.osis-election.report.pending',$election) }}"><div class="card-body"><small>Belum memilih</small><h3 class="text-warning">{{ number_format($pendingStudents->count()) }}</h3><span>Lihat daftar evaluasi <i class="fas fa-arrow-right"></i></span></div></a></div><div class="col-md-3 col-6 mb-3"><div class="card card-outline card-info"><div class="card-body"><small>Partisipasi</small><h3 class="text-info">{{ $turnout }}%</h3><span>Dari seluruh DPT</span></div></div></div></div>
<div class="card card-outline card-primary"><div class="card-header"><h3 class="card-title font-weight-bold">Perolehan Suara</h3></div><div class="card-body">@forelse($packages as $item)<div class="result-row"><strong>Paslon {{ $item['package']->number }} · {{ $item['package']->name ?: 'Paket '.$item['package']->number }}</strong><div class="progress"><div class="progress-bar bg-primary" style="width:{{ $item['percentage'] }}%"></div></div><b>{{ number_format($item['votes']) }} <small>({{ $item['percentage'] }}%)</small></b></div>@empty<p class="text-muted mb-0">Belum ada paket kandidat.</p>@endforelse<p class="small text-muted mb-0 mt-3"><i class="fas fa-shield-alt mr-1"></i>Perolehan ditampilkan agregat. Pilihan tiap pemilih tidak pernah dicantumkan.</p></div></div>
<div class="card card-outline card-primary"><div class="card-header"><h3 class="card-title font-weight-bold">Partisipasi per Rombel</h3></div><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>ROMBEL</th><th>DPT</th><th>SUDAH</th><th>BELUM</th><th>PARTISIPASI</th></tr></thead><tbody>@forelse($participation as $item)<tr><td>{{ $item['class'] }}</td><td>{{ $item['total'] }}</td><td class="text-success font-weight-bold">{{ $item['voted'] }}</td><td class="text-warning font-weight-bold">{{ $item['pending'] }}</td><td>{{ $item['percentage'] }}%</td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-3">Tidak ada data siswa pada DPT.</td></tr>@endforelse</tbody></table></div></div>
<div class="osis-report-legal"><i class="fas fa-shield-alt mr-1"></i>Berkas dicetak langsung dari SIMANSA · {{ now()->format('d/m/Y H:i') }} WIB</div></div>
@stop
@section('css')<style>.osis-report .card-body small{display:block;font-size:.72rem;font-weight:800;text-transform:uppercase;color:#64748b}.osis-report .card-body h3{margin:.3rem 0;font-size:1.65rem;font-weight:800}.osis-report .card-body span{font-size:.78rem;color:#64748b}.osis-report a.card{transition:transform .16s,box-shadow .16s}.osis-report a.card:hover{box-shadow:0 10px 20px rgba(245,158,11,.13);transform:translateY(-2px)}.osis-report-legal{margin:1rem 0;padding:.8rem 1rem;border:1px dashed #94a3b8;border-radius:9px;color:#475569;font-size:.78rem}.result-row{display:grid;grid-template-columns:minmax(180px,280px) 1fr 110px;gap:1rem;align-items:center;margin-bottom:1rem}.result-row b{text-align:right}.progress{height:12px;border-radius:99px}.progress-bar{border-radius:inherit}@media(max-width:575.98px){.result-row{grid-template-columns:1fr}.result-row b{text-align:left}}</style>@stop
