@extends('adminlte::page')
@php
    $routePrefix = request()->routeIs('siswa.*') ? 'siswa.polling' : 'admin.gtk.polling';
@endphp
@section('title','Polling Saya')
@section('content_header')<div class="row mb-2"><div class="col-sm-6"><h1><i class="fas fa-poll-h text-primary mr-2"></i>Polling Saya</h1></div><div class="col-sm-6"><ol class="breadcrumb float-sm-right"><li class="breadcrumb-item active">Polling</li></ol></div></div>@stop
@section('content')
<div class="simansa-polling-respondent"><div class="card bg-gradient-primary text-white mb-4 polling-hero"><div class="card-body"><div class="row align-items-center"><div class="col-lg-8"><div class="small text-uppercase font-weight-bold mb-2"><i class="fas fa-comment-dots mr-1"></i>Suara Anda Berarti</div><h2 class="h3 font-weight-bold mb-2">Polling & Survei</h2><p class="mb-0">Isi polling yang ditujukan kepada Anda sebelum batas waktu berakhir.</p></div><div class="col-lg-4 mt-3 mt-lg-0 text-lg-right"><span class="poll-count">{{ $active->filter(fn($p)=>$p->responses->isEmpty())->count() }}</span><small class="d-block">belum diisi</small></div></div></div></div>
<h4 class="font-weight-bold mb-3">Polling Aktif</h4><div class="row">@forelse($active as $polling)@php($answered=$polling->responses->isNotEmpty())<div class="col-lg-6"><div class="card card-outline card-{{ $answered?'success':'primary' }} polling-card"><div class="card-body"><div class="d-flex align-items-start"><div class="polling-icon bg-{{ $answered?'success':'primary' }}"><i class="fas {{ $answered?'fa-check':'fa-poll-h' }}"></i></div><div class="flex-grow-1 ml-3"><div class="d-flex justify-content-between"><span class="badge badge-{{ $answered?'success':'warning' }}">{{ $answered?'Sudah diisi':'Menunggu jawaban' }}</span><small class="text-muted">{{ $polling->ends_at->diffForHumans() }}</small></div><h5 class="font-weight-bold mt-2 mb-1">{{ $polling->title }}</h5><p class="text-muted mb-3">{{ Str::limit($polling->description,130) }}</p><a href="{{ route($routePrefix.'.show',$polling) }}" class="btn btn-{{ $answered?'outline-primary':'primary' }}"><i class="fas {{ $answered?'fa-eye':'fa-pen' }} mr-1"></i>{{ $answered?'Lihat Jawaban':'Isi Sekarang' }}</a></div></div></div></div></div>@empty<div class="col-12"><div class="card"><div class="card-body text-center py-5 text-muted"><i class="fas fa-check-circle fa-3x text-success mb-3"></i><h5>Tidak ada polling aktif</h5><p class="mb-0">Semua polling sudah Anda selesaikan atau belum ada jadwal baru.</p></div></div></div>@endforelse</div>
@if($history->isNotEmpty())<div class="card card-outline card-primary"><div class="card-header"><h3 class="card-title font-weight-bold"><i class="fas fa-history text-primary mr-2"></i>Riwayat Respons</h3></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover mb-0"><thead class="bg-light"><tr><th>Polling</th><th>Waktu Mengisi</th><th>Status</th><th></th></tr></thead><tbody>@foreach($history as $item)<tr><td><strong>{{ $item->polling->title }}</strong></td><td>{{ $item->submitted_at->format('d/m/Y H:i') }}</td><td><span class="badge badge-success">Terkirim</span></td><td class="text-right"><a href="{{ route($routePrefix.'.show',$item->polling) }}" class="btn btn-sm btn-outline-primary"><i class="fas fa-eye mr-1"></i>Lihat</a></td></tr>@endforeach</tbody></table></div></div></div>@endif</div>
@stop
@section('css')<style>.simansa-polling-respondent .polling-hero{border:0;border-radius:18px;overflow:hidden}.simansa-polling-respondent .poll-count{font-size:2.4rem;font-weight:900;line-height:1}.simansa-polling-respondent .polling-card{height:calc(100% - 1.5rem)}.simansa-polling-respondent .polling-icon{align-items:center;border-radius:12px;color:#fff;display:flex;flex:0 0 48px;height:48px;justify-content:center;font-size:1.2rem}@media(max-width:575.98px){.simansa-polling-respondent .card-body{padding:1rem}}</style>@stop
