<style>
    :root{--asrama-navy:#17324d;--asrama-teal:#0f9f94;--asrama-gold:#f3b33d;--asrama-soft:#edf8f7;--asrama-ink:#172b3d}
    .asrama-hero{display:flex;justify-content:space-between;align-items:center;gap:1.5rem;padding:1.6rem 1.75rem;margin-bottom:1.35rem;border-radius:24px;color:#fff;background:linear-gradient(135deg,var(--asrama-navy),var(--asrama-teal));box-shadow:0 18px 42px rgba(24,58,90,.18)}
    .asrama-hero__eyebrow{display:inline-flex;gap:.45rem;align-items:center;margin-bottom:.55rem;font-size:.75rem;font-weight:700;letter-spacing:.09em;text-transform:uppercase;color:rgba(255,255,255,.78)}
    .asrama-hero h2{margin:0 0 .35rem;font-size:1.75rem;font-weight:750}.asrama-hero p{max-width:760px;margin:0;color:rgba(255,255,255,.9)}
    .asrama-panel{margin-bottom:1.35rem;border:0;border-radius:20px;background:#fff;box-shadow:0 12px 32px rgba(22,44,70,.08);overflow:hidden}
    .asrama-panel__header{display:flex;justify-content:space-between;align-items:center;gap:1rem;padding:1.15rem 1.35rem;border-bottom:1px solid #edf1f5}
    .asrama-panel__header h3{margin:0;font-size:1.05rem;font-weight:700;color:var(--asrama-ink)}.asrama-panel__header p{margin:.2rem 0 0;color:#718096;font-size:.86rem}
    .asrama-panel__body{padding:1.35rem}.asrama-stat{height:100%;padding:1.2rem;border-radius:18px;background:#fff;box-shadow:0 10px 26px rgba(22,44,70,.08);border-left:4px solid var(--asrama-teal)}
    .asrama-stat span{display:block;color:#718096;font-size:.78rem;text-transform:uppercase;letter-spacing:.04em}.asrama-stat strong{display:block;margin:.25rem 0;font-size:1.85rem;color:var(--asrama-navy)}.asrama-stat small{color:#8492a6}
    .asrama-table{margin:0}.asrama-table thead th{border-top:0;border-bottom:1px solid #dce5ed;background:#f7fafc;color:#516174;font-size:.75rem;text-transform:uppercase;letter-spacing:.035em;white-space:nowrap}
    .asrama-table td{vertical-align:middle}.asrama-arab{font-family:"Noto Naskh Arabic","Amiri","Traditional Arabic",serif;font-size:1.18em;direction:rtl}
    .asrama-badge{display:inline-flex;align-items:center;padding:.3rem .58rem;border-radius:999px;font-size:.75rem;font-weight:650}
    .asrama-badge--active{color:#08756f;background:#dff7f4}.asrama-badge--muted{color:#64748b;background:#eef2f6}
    .asrama-form label{font-weight:650;color:#435366;font-size:.86rem}.asrama-form .form-control{border-radius:10px;border-color:#dce4ec}.asrama-form .btn{border-radius:10px}
    .asrama-alert{border:0;border-radius:14px}.asrama-empty{padding:2.5rem;text-align:center;color:#718096}.asrama-empty i{display:block;margin-bottom:.75rem;font-size:2rem;color:#a8b6c5}
    .asrama-modal .modal-content{border:0;border-radius:22px;box-shadow:0 24px 70px rgba(13,35,55,.25);overflow:hidden}.asrama-modal .modal-header{padding:1.15rem 1.35rem;color:#fff;border:0;background:linear-gradient(135deg,var(--asrama-navy),#245f77)}.asrama-modal .modal-title{font-weight:750}.asrama-modal .modal-header .close{color:#fff;text-shadow:none;opacity:.82}.asrama-modal .modal-body{padding:1.4rem}.asrama-modal .modal-footer{padding:1rem 1.4rem;border-color:#edf1f5;background:#f8fafc}
    .asrama-choice{display:block;height:100%;padding:1rem;border:1px solid #dce6ed;border-radius:14px;background:#fbfdfd}.asrama-choice:hover{border-color:var(--asrama-teal);background:var(--asrama-soft)}.asrama-choice strong{display:block;color:var(--asrama-ink)}.asrama-choice small{color:#718096}
    .asrama-progress{position:fixed;z-index:2000;inset:0;display:none;align-items:center;justify-content:center;background:rgba(12,28,43,.62);backdrop-filter:blur(3px)}.asrama-progress.is-visible{display:flex}.asrama-progress__box{width:min(390px,calc(100% - 36px));padding:1.6rem;text-align:center;border-radius:22px;background:#fff;box-shadow:0 24px 70px rgba(0,0,0,.25)}.asrama-progress__icon{display:grid;width:56px;height:56px;margin:0 auto 1rem;place-items:center;border-radius:50%;color:#fff;background:linear-gradient(135deg,var(--asrama-teal),var(--asrama-navy));font-size:1.4rem}.asrama-progress .progress{height:8px;border-radius:99px;background:#e8eff3}.asrama-progress .progress-bar{width:72%;border-radius:99px;background:linear-gradient(90deg,var(--asrama-teal),var(--asrama-gold));animation:asrama-loading 1.25s ease-in-out infinite alternate}
    .select2-container{width:100%!important}.select2-container--bootstrap4 .select2-selection{min-height:40px;border-color:#dce4ec;border-radius:10px}.select2-container--bootstrap4 .select2-selection--multiple .select2-selection__choice{border:0;border-radius:999px;color:#08756f;background:#dff7f4}.select2-dropdown{border-color:#dce4ec;border-radius:12px;overflow:hidden;box-shadow:0 14px 34px rgba(22,44,70,.14)}
    .asrama-room{position:relative;height:100%;padding:1.25rem;border-radius:18px;background:linear-gradient(145deg,#fff,#f6fafb);border:1px solid #e4edf1;box-shadow:0 10px 24px rgba(22,44,70,.07)}.asrama-room--putra{border-top:4px solid #3b82f6}.asrama-room--putri{border-top:4px solid #ec4899}.asrama-room__capacity{height:7px;border-radius:99px;background:#e8eef2;overflow:hidden}.asrama-room__capacity span{display:block;height:100%;border-radius:99px;background:var(--asrama-teal)}
    .asrama-pill{display:inline-flex;align-items:center;gap:.35rem;padding:.35rem .65rem;border-radius:999px;color:#425466;background:#edf2f6;font-size:.78rem;font-weight:650}.asrama-icon-button{width:36px;height:36px;border-radius:10px}.asrama-help{padding:.8rem 1rem;border-radius:12px;color:#3e596a;background:#eef7fb;border-left:3px solid #38a3c5;font-size:.86rem}
    @keyframes asrama-loading{from{transform:translateX(-22%)}to{transform:translateX(38%)}}
    @media(max-width:768px){.asrama-hero{align-items:flex-start;flex-direction:column}.asrama-hero__action{width:100%}.asrama-hero__action .btn{width:100%}.asrama-panel__header{align-items:flex-start;flex-direction:column}}
</style>
