@php
    $editing = $catatanKonseling->exists;
    $selectedStudent = $editing ? $catatanKonseling->siswa : ($selectedStudent ?? null);
    $defaultCounselor = old('konselor_id', $catatanKonseling->konselor_id ?: auth()->user()->gtk?->id);
@endphp
<div class="row">
    <div class="col-lg-5">
        <h6 class="form-section"><i class="fas fa-id-card text-primary"></i> Identitas Layanan</h6>
        <div class="form-group"><label>Siswa <span class="text-danger">*</span></label><select name="siswa_id" id="siswa_id" class="form-control @error('siswa_id') is-invalid @enderror" required>@if($selectedStudent)<option value="{{ $selectedStudent->id }}" selected>{{ $selectedStudent->nama_lengkap }}</option>@endif</select>@error('siswa_id')<span class="invalid-feedback">{{ $message }}</span>@enderror<small class="form-text text-muted">@if($isCounselingAdmin)Cari siswa aktif berdasarkan nama, NISN, atau NIS Lokal.@else Hanya siswa dari rombel yang Anda ampu pada jadwal aktif.@endif</small></div>
        <div class="form-group"><label>Konselor (Guru BK) <span class="text-danger">*</span></label>@if($isCounselingAdmin)<select name="konselor_id" class="form-control select2 @error('konselor_id') is-invalid @enderror" required><option value="">Pilih konselor</option>@foreach($konselor as $item)<option value="{{ $item->id }}" @selected($defaultCounselor===$item->id)>{{ $item->nama_lengkap }}</option>@endforeach</select>@else<input type="hidden" name="konselor_id" value="{{ $defaultCounselor }}"><select class="form-control" disabled aria-label="Konselor aktif"><option>{{ $konselor->first()?->nama_lengkap ?: 'Profil Guru BK belum terhubung' }}</option></select><small class="form-text text-muted"><i class="fas fa-lock mr-1"></i>Konselor otomatis mengikuti akun BK yang sedang masuk.</small>@endif @error('konselor_id')<span class="invalid-feedback d-block">{{ $message }}</span>@enderror</div>
        <div class="form-group"><label>Tahun Pelajaran <span class="text-danger">*</span></label><select name="tahun_pelajaran_id" class="form-control @error('tahun_pelajaran_id') is-invalid @enderror" required>@foreach($tahunPelajaran as $tp)<option value="{{ $tp->id }}" @selected(old('tahun_pelajaran_id',$catatanKonseling->tahun_pelajaran_id ?: $tahunPelajaran->firstWhere('is_active',true)?->id)===$tp->id)>{{ $tp->nama }} · {{ $tp->semester_aktif }}</option>@endforeach</select>@error('tahun_pelajaran_id')<span class="invalid-feedback">{{ $message }}</span>@enderror</div>
        <div class="row"><div class="col-sm-6"><div class="form-group"><label>Tanggal <span class="text-danger">*</span></label><input type="date" name="tanggal_konseling" class="form-control @error('tanggal_konseling') is-invalid @enderror" value="{{ old('tanggal_konseling',optional($catatanKonseling->tanggal_konseling)->format('Y-m-d') ?: now()->format('Y-m-d')) }}" required>@error('tanggal_konseling')<span class="invalid-feedback">{{ $message }}</span>@enderror</div></div><div class="col-sm-6"><div class="form-group"><label>Bidang Masalah <span class="text-danger">*</span></label><select name="kategori_masalah" class="form-control" required>@foreach($kategori as $key=>$label)<option value="{{ $key }}" @selected(old('kategori_masalah',$catatanKonseling->kategori_masalah ?: 'belajar')===$key)>{{ $label }}</option>@endforeach</select></div></div></div>
    </div>
    <div class="col-lg-7">
        <h6 class="form-section"><i class="fas fa-clipboard-check text-primary"></i> Catatan & Tindak Lanjut</h6>
        <div class="form-group"><label>Permasalahan / Hasil Asesmen <span class="text-danger">*</span></label><textarea name="permasalahan" rows="4" class="form-control @error('permasalahan') is-invalid @enderror" required>{{ old('permasalahan',$catatanKonseling->permasalahan) }}</textarea>@error('permasalahan')<span class="invalid-feedback">{{ $message }}</span>@enderror</div>
        <div class="form-group"><label>Hasil Konseling</label><textarea name="hasil_konseling" rows="3" class="form-control">{{ old('hasil_konseling',$catatanKonseling->hasil_konseling) }}</textarea></div>
        <div class="row"><div class="col-md-6"><div class="form-group"><label>Rekomendasi</label><textarea name="rekomendasi" rows="3" class="form-control">{{ old('rekomendasi',$catatanKonseling->rekomendasi) }}</textarea></div></div><div class="col-md-6"><div class="form-group"><label>Tindak Lanjut</label><textarea name="tindak_lanjut" rows="3" class="form-control">{{ old('tindak_lanjut',$catatanKonseling->tindak_lanjut) }}</textarea></div></div></div>
        <div class="row"><div class="col-md-4"><div class="form-group"><label>Status <span class="text-danger">*</span></label><select name="status" id="status" class="form-control" required>@foreach($status as $key=>$label)<option value="{{ $key }}" @selected(old('status',$catatanKonseling->status ?: 'baru')===$key)>{{ $label }}</option>@endforeach</select></div></div><div class="col-md-4"><div class="form-group"><label>Tanggal Tindak Lanjut</label><input type="date" name="tanggal_tindak_lanjut" class="form-control @error('tanggal_tindak_lanjut') is-invalid @enderror" value="{{ old('tanggal_tindak_lanjut',optional($catatanKonseling->tanggal_tindak_lanjut)->format('Y-m-d')) }}">@error('tanggal_tindak_lanjut')<span class="invalid-feedback">{{ $message }}</span>@enderror</div></div><div class="col-md-4"><div class="form-group"><label>Rujukan Ke</label><input type="text" name="rujukan_ke" id="rujukan_ke" class="form-control @error('rujukan_ke') is-invalid @enderror" value="{{ old('rujukan_ke',$catatanKonseling->rujukan_ke) }}" placeholder="Psikolog/puskesmas/dll.">@error('rujukan_ke')<span class="invalid-feedback">{{ $message }}</span>@enderror</div></div></div>
        <div class="callout callout-warning py-2"><div class="custom-control custom-switch"><input type="hidden" name="is_confidential" value="0"><input type="checkbox" name="is_confidential" value="1" id="is_confidential" class="custom-control-input" @checked(old('is_confidential',$catatanKonseling->exists ? $catatanKonseling->is_confidential : true))><label class="custom-control-label" for="is_confidential"><strong>Catatan rahasia</strong></label></div><small>Hanya pengguna dengan akses catatan rahasia, pembuat, dan konselor terkait yang dapat membacanya.</small></div>
        <div class="callout callout-info py-2 mb-0"><div class="custom-control custom-switch"><input type="hidden" name="share_with_teachers" value="0"><input type="checkbox" name="share_with_teachers" value="1" id="share_with_teachers" class="custom-control-input" @checked(old('share_with_teachers',$catatanKonseling->share_with_teachers))><label class="custom-control-label" for="share_with_teachers"><strong>Bagikan notice kepada guru terkait</strong></label></div><small>Hanya wali kelas dan guru mapel yang mengajar rombel siswa. Siswa tidak dapat melihat notice ini.</small><textarea name="teacher_notice" id="teacher_notice" rows="2" class="form-control mt-2 @error('teacher_notice') is-invalid @enderror" placeholder="Contoh: Mohon pantau konsentrasi belajar dan berikan kesempatan konsultasi setelah pembelajaran.">{{ old('teacher_notice',$catatanKonseling->teacher_notice) }}</textarea>@error('teacher_notice')<span class="invalid-feedback">{{ $message }}</span>@enderror</div>
    </div>
</div>
