@extends('adminlte::page')
@section('title','Daftar Catatan Konseling')
@section('content_header')
<div class="row mb-2"><div class="col-sm-6"><h1><i class="fas fa-clipboard-list text-primary"></i> Daftar Catatan Konseling</h1></div><div class="col-sm-6"><ol class="breadcrumb float-sm-right"><li class="breadcrumb-item"><a href="{{ route('admin.catatan-konseling.index') }}">Konseling</a></li><li class="breadcrumb-item active">Semua Catatan</li></ol></div></div>
@stop
@section('content')
<div class="counseling-records">
    <div class="row">@foreach([['Total Layanan',$stats['total'],'primary','clipboard-list'],['Sedang Ditangani',$stats['aktif'],'warning','hourglass-half'],['Perlu Tindak Lanjut',$stats['tindak_lanjut'],'danger','calendar-check'],['Selesai',$stats['selesai'],'success','check-circle']] as [$label,$value,$color,$icon])<div class="col-6 col-lg-3"><div class="info-box"><span class="info-box-icon bg-{{ $color }}"><i class="fas fa-{{ $icon }}"></i></span><div class="info-box-content"><span class="info-box-text">{{ $label }}</span><span class="info-box-number">{{ number_format($value) }}</span></div></div></div>@endforeach</div>
    <div class="card card-outline card-primary"><div class="card-header"><h3 class="card-title"><i class="fas fa-list mr-1"></i> Seluruh Catatan</h3><div class="card-tools"><a href="{{ route('admin.catatan-konseling.index') }}" class="btn btn-secondary btn-sm"><i class="fas fa-users"></i> Data Siswa</a>@can('create-catatan-konseling') <a href="{{ route('admin.catatan-konseling.create') }}" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Catatan Baru</a>@endcan</div></div><div class="card-body">
        <div class="counseling-filter rounded mb-3 p-3"><div class="row"><div class="col-md-4"><label>Status</label><select id="filter-status" class="form-control"><option value="">Semua status</option>@foreach($status as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><div class="col-md-4"><label>Kategori</label><select id="filter-kategori" class="form-control"><option value="">Semua kategori</option>@foreach($kategori as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><div class="col-md-4 d-flex align-items-end"><button id="reset-filter" class="btn btn-secondary btn-block"><i class="fas fa-sync-alt"></i> Reset Filter</button></div></div></div>
        <div class="table-responsive"><table id="records-table" class="table table-bordered table-hover w-100"><thead><tr><th>No</th><th>Siswa</th><th>Konselor</th><th>Tanggal</th><th>Layanan</th><th>Status</th><th>Akses</th><th>Aksi</th></tr></thead></table></div>
    </div></div>
</div>
@stop
@section('css')<link rel="stylesheet" href="//cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css"><style>.counseling-records .counseling-filter{background:#f8fafc;border:1px solid #e2e8f0}.counseling-records .info-box{min-height:82px}.counseling-records .info-box-icon{width:66px}.counseling-records table td{vertical-align:middle}</style>@stop
@section('js')
<script src="//cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script><script src="//cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>
<script>$(function(){const table=$('#records-table').DataTable({processing:true,serverSide:true,ajax:{url:@json(route('admin.catatan-konseling.records')),data:d=>{d.status=$('#filter-status').val();d.kategori=$('#filter-kategori').val()}},columns:[{data:'DT_RowIndex',orderable:false,searchable:false},{data:'siswa_nama',name:'siswa_nama'},{data:'konselor_nama',name:'konselor_nama'},{data:'tanggal_konseling',name:'tanggal_konseling'},{data:'layanan',name:'jenis_konseling'},{data:'status_badge',name:'status'},{data:'kerahasiaan',name:'is_confidential',searchable:false},{data:'action',orderable:false,searchable:false}],order:[[3,'desc']],language:{url:'//cdn.datatables.net/plug-ins/1.13.8/i18n/id.json'}});$('#filter-status,#filter-kategori').on('change',()=>table.ajax.reload());$('#reset-filter').on('click',()=>{$('#filter-status,#filter-kategori').val('');table.search('').ajax.reload()});$(document).on('click','.btn-delete',function(){const id=$(this).data('id');Swal.fire({title:'Hapus catatan?',text:'Catatan yang dihapus tidak tampil lagi pada riwayat.',icon:'warning',showCancelButton:true,confirmButtonColor:'#dc3545',confirmButtonText:'Ya, hapus',cancelButtonText:'Batal'}).then(result=>{if(!result.isConfirmed)return;$.ajax({url:@json(route('admin.catatan-konseling.index'))+'/'+id,type:'DELETE',data:{_token:@json(csrf_token())},success:r=>{table.ajax.reload(null,false);toastr.success(r.message)},error:x=>toastr.error(x.responseJSON?.message||'Catatan gagal dihapus.')})})})});</script>
@stop
