@extends('adminlte::page')
@section('title','Riwayat Konseling Siswa')
@section('plugins.Select2',true)
@section('content_header')
<div class="row mb-2"><div class="col-sm-6"><h1><i class="fas fa-file-medical-alt text-primary"></i> Riwayat Konseling Siswa</h1></div><div class="col-sm-6"><ol class="breadcrumb float-sm-right"><li class="breadcrumb-item"><a href="{{ route('admin.catatan-konseling.index') }}">Konseling</a></li><li class="breadcrumb-item active">Riwayat Siswa</li></ol></div></div>
@stop
@section('content')
<div class="counseling-report">
    <div class="card card-outline card-primary student-picker"><div class="card-header"><h3 class="card-title"><i class="fas fa-search mr-1"></i> Cari Siswa Aktif</h3></div><div class="card-body"><form method="GET"><div class="row"><div class="col-md-9"><select name="siswa_id" id="siswa_id" class="form-control" required>@if($student)<option value="{{ $student->id }}" selected>{{ $student->nama_lengkap }}</option>@endif</select></div><div class="col-md-3 mt-2 mt-md-0"><button class="btn btn-primary btn-block"><i class="fas fa-search"></i> Tampilkan Profil & Riwayat</button></div></div></form></div></div>

    @if($student)
    @php
        $class = $student->kelasTahunAktif->first();
        $parent = $student->ortu;
        $age = $student->tanggal_lahir ? $student->tanggal_lahir->age.' tahun' : '-';
        $addressSource = $student->alamat_sama_ortu && $parent
            ? [$parent->alamat_ortu, $parent->rt_ortu ? 'RT '.$parent->rt_ortu : null, $parent->rw_ortu ? 'RW '.$parent->rw_ortu : null, $parent->kodepos]
            : [$student->alamat_siswa, $student->rt_siswa ? 'RT '.$student->rt_siswa : null, $student->rw_siswa ? 'RW '.$student->rw_siswa : null, $student->kodepos_siswa];
        $address = implode(', ', array_filter($addressSource)) ?: '-';
        $activeRecords = $records->whereIn('status', ['baru','dalam_proses','perlu_rujukan'])->count();
        $overdueRecords = $records->filter->tindak_lanjut_terlambat->count();
    @endphp
    <div class="card profile-summary card-outline card-primary"><div class="card-body"><div class="row align-items-center">
        <div class="col-lg-4 profile-main"><div class="d-flex align-items-center"><img src="{{ $student->foto_profile_url }}" alt="Foto {{ $student->nama_lengkap }}" class="student-photo"><div class="ml-3"><span class="badge badge-primary mb-1">{{ $class?->nama_kelas ?? 'Tanpa rombel aktif' }}</span><h4 class="mb-1">{{ $student->nama_lengkap }}</h4><div class="text-muted small">NISN {{ $student->nisn ?: '-' }}@if($student->nis_lokal)<br>NIS Lokal {{ $student->nis_lokal }}@endif</div></div></div></div>
        <div class="col-lg-8 mt-3 mt-lg-0"><div class="row profile-metrics"><div class="col-4"><small>Total Layanan</small><strong>{{ $records->count() }}</strong></div><div class="col-4"><small>Kasus Aktif</small><strong class="text-warning">{{ $activeRecords }}</strong></div><div class="col-4"><small>Terlambat</small><strong class="text-danger">{{ $overdueRecords }}</strong></div></div><div class="profile-actions mt-3 text-lg-right">@can('create-catatan-konseling')<a href="{{ route('admin.catatan-konseling.create',['siswa_id'=>$student->id]) }}" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Catat Konseling</a>@endcan <a href="{{ route('admin.catatan-konseling.index') }}" class="btn btn-secondary btn-sm"><i class="fas fa-users"></i> Kembali ke Data Siswa</a></div></div>
    </div></div></div>

    <div class="row metadata-row">
        <div class="col-lg-4"><div class="card h-100"><div class="card-header"><h3 class="card-title"><i class="fas fa-id-card text-primary mr-1"></i> Identitas Pribadi</h3></div><div class="card-body"><dl class="meta-list"><dt>Jenis Kelamin</dt><dd>{{ $student->jenis_kelamin === 'L' ? 'Laki-laki' : 'Perempuan' }}</dd><dt>Tempat, Tanggal Lahir</dt><dd>{{ $student->tempat_lahir ?: '-' }}, {{ $student->tanggal_lahir?->translatedFormat('d F Y') ?? '-' }} <small>({{ $age }})</small></dd><dt>Agama</dt><dd>{{ $student->agama ?: '-' }}</dd><dt>Nomor HP</dt><dd>{{ $student->nomor_hp ?: '-' }}</dd><dt>Email Akun</dt><dd class="text-break">{{ $student->user?->email ?: '-' }}</dd></dl></div></div></div>
        <div class="col-lg-4 mt-3 mt-lg-0"><div class="card h-100"><div class="card-header"><h3 class="card-title"><i class="fas fa-school text-primary mr-1"></i> Informasi Akademik</h3></div><div class="card-body"><dl class="meta-list"><dt>Rombel Aktif</dt><dd>{{ $class?->nama_kelas ?? '-' }}</dd><dt>Tingkat</dt><dd>{{ $class?->tingkat ? 'Kelas '.$class->tingkat : '-' }}</dd><dt>Wali Kelas</dt><dd>{{ $class?->waliKelas?->name ?? '-' }}</dd><dt>Tahun Masuk</dt><dd>{{ $student->tahun_masuk ?: '-' }}</dd><dt>Asal Siswa</dt><dd>{{ $student->asal_siswa ? ucwords(str_replace('_',' ',$student->asal_siswa)) : '-' }}</dd></dl></div></div></div>
        <div class="col-lg-4 mt-3 mt-lg-0"><div class="card h-100"><div class="card-header"><h3 class="card-title"><i class="fas fa-users text-primary mr-1"></i> Orang Tua / Keluarga</h3></div><div class="card-body"><dl class="meta-list"><dt>Ayah</dt><dd>{{ $parent?->nama_ayah ?: '-' }}@if($parent?->pekerjaan_ayah)<small>{{ $parent->pekerjaan_ayah }} · {{ $parent->hp_ayah ?: 'tanpa nomor HP' }}</small>@endif</dd><dt>Ibu</dt><dd>{{ $parent?->nama_ibu ?: '-' }}@if($parent?->pekerjaan_ibu)<small>{{ $parent->pekerjaan_ibu }} · {{ $parent->hp_ibu ?: 'tanpa nomor HP' }}</small>@endif</dd><dt>Anak Ke / Bersaudara</dt><dd>{{ $student->anak_ke ?: '-' }} / {{ $student->jumlah_saudara ?: '-' }} bersaudara</dd><dt>Tempat Tinggal</dt><dd>{{ $student->jenis_tempat_tinggal ? ucwords(str_replace('_',' ',$student->jenis_tempat_tinggal)) : '-' }}</dd></dl></div></div></div>
    </div>

    <div class="card address-card mt-3"><div class="card-body py-3"><div class="d-flex"><span class="address-icon"><i class="fas fa-map-marker-alt"></i></span><div><small class="text-muted d-block font-weight-bold">ALAMAT DOMISILI</small><span>{{ $address }}</span></div></div></div></div>

    <div class="card card-outline card-primary mt-3"><div class="card-header"><h3 class="card-title"><i class="fas fa-history mr-1"></i> Riwayat Layanan Konseling</h3><div class="card-tools"><span class="badge badge-primary">{{ $records->count() }} layanan</span></div></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Tanggal</th><th>Layanan</th><th>Konselor</th><th>Status</th><th>Tindak Lanjut</th><th>Aksi</th></tr></thead><tbody>@forelse($records as $item)<tr><td>{{ $item->tanggal_konseling?->format('d/m/Y') }}</td><td><strong>{{ $item->jenis_label }}</strong><br><small class="text-muted">{{ $item->kategori_label }}</small></td><td>{{ $item->konselor?->nama_lengkap ?? '-' }}</td><td><span class="badge badge-{{ $item->status_badge }}">{{ $item->status_label }}</span></td><td>@if($item->tanggal_tindak_lanjut)<span class="{{ $item->tindak_lanjut_terlambat ? 'text-danger font-weight-bold' : '' }}">{{ $item->tanggal_tindak_lanjut->format('d/m/Y') }}</span>@else - @endif</td><td><a href="{{ route('admin.catatan-konseling.show',$item) }}" class="btn btn-info btn-sm" title="Lihat detail"><i class="fas fa-eye"></i></a></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4"><i class="fas fa-inbox fa-2x mb-2"></i><br>Belum ada catatan konseling yang dapat Anda akses.@can('create-catatan-konseling')<br><a href="{{ route('admin.catatan-konseling.create',['siswa_id'=>$student->id]) }}" class="btn btn-primary btn-sm mt-2"><i class="fas fa-plus"></i> Buat Catatan Pertama</a>@endcan</td></tr>@endforelse</tbody></table></div></div></div>
    @endif
</div>
@stop
@section('css')
<style>
.counseling-report .student-picker .card-body{padding:.85rem}.counseling-report .profile-summary{box-shadow:0 .35rem 1rem rgba(15,23,42,.07)}.counseling-report .student-photo{width:92px;height:116px;object-fit:cover;border-radius:.65rem;border:3px solid #fff;box-shadow:0 0 0 1px #cbd5e1}.counseling-report .profile-main h4{font-size:1.15rem;font-weight:700}.counseling-report .profile-metrics{background:#f8fafc;border:1px solid #e2e8f0;border-radius:.55rem;padding:.7rem 0;text-align:center}.counseling-report .profile-metrics>div+div{border-left:1px solid #e2e8f0}.counseling-report .profile-metrics small{display:block;color:#64748b;font-size:.72rem;font-weight:600}.counseling-report .profile-metrics strong{display:block;font-size:1.25rem}.counseling-report .metadata-row>.col-lg-4{display:flex}.counseling-report .metadata-row .card{width:100%;border:1px solid #e2e8f0;box-shadow:0 .25rem .75rem rgba(15,23,42,.05)}.counseling-report .meta-list{display:grid;grid-template-columns:42% 58%;gap:.65rem 0;margin:0}.counseling-report .meta-list dt{color:#64748b;font-size:.76rem;font-weight:600;margin:0}.counseling-report .meta-list dd{color:#1e293b;font-size:.8rem;font-weight:600;margin:0;min-width:0}.counseling-report .meta-list dd small{display:block;color:#64748b;font-weight:400}.counseling-report .address-card{border:1px solid #dbeafe;background:#f8fbff}.counseling-report .address-icon{width:38px;height:38px;display:flex;align-items:center;justify-content:center;border-radius:.45rem;background:#dbeafe;color:#2563eb;margin-right:.75rem;flex:none}.counseling-report table td{vertical-align:middle}@media(max-width:767.98px){.counseling-report .student-photo{width:74px;height:94px}.counseling-report .profile-actions .btn{margin-top:.35rem;width:100%}.counseling-report .meta-list{grid-template-columns:40% 60%}}
</style>
@stop
@section('js')
<script>$(function(){$('#siswa_id').select2({theme:'bootstrap4',width:'100%',placeholder:'Cari nama, NISN, atau NIS Lokal',minimumInputLength:2,ajax:{url:@json(route('admin.catatan-konseling.students.search')),dataType:'json',delay:300,data:p=>({q:p.term}),processResults:d=>d},templateResult:item=>item.loading?item.text:$('<div><strong></strong><br><small class="text-muted"></small></div>').find('strong').text(item.text).end().find('small').text('NISN '+(item.nisn||'-')+' · '+item.kelas).end()})});</script>
@stop
