@extends('layouts.admin')
@section('title','Riwayat Konseling Siswa')
@section('plugins.Select2',true)
@section('content_header')<div class="row mb-2"><div class="col-sm-6"><h1><i class="fas fa-file-medical-alt text-primary"></i> Riwayat Konseling Siswa</h1></div><div class="col-sm-6"><ol class="breadcrumb float-sm-right"><li class="breadcrumb-item"><a href="{{ route('admin.catatan-konseling.index') }}">Konseling</a></li><li class="breadcrumb-item active">Riwayat Siswa</li></ol></div></div>@stop
@section('content')
<div class="counseling-report"><div class="card card-outline card-primary"><div class="card-header"><h3 class="card-title">Pilih Siswa Aktif</h3></div><div class="card-body"><form method="GET"><div class="row"><div class="col-md-9"><select name="siswa_id" id="siswa_id" class="form-control" required>@if($student)<option value="{{ $student->id }}" selected>{{ $student->nama_lengkap }}</option>@endif</select></div><div class="col-md-3 mt-2 mt-md-0"><button class="btn btn-primary btn-block"><i class="fas fa-search"></i> Tampilkan Riwayat</button></div></div></form></div></div>
@if($student)<div class="card"><div class="card-header"><h3 class="card-title"><strong>{{ $student->nama_lengkap }}</strong> <small class="text-muted">· NISN {{ $student->nisn ?? '-' }} · {{ $student->kelasTahunAktif->first()?->nama_kelas ?? 'Tanpa rombel aktif' }}</small></h3><div class="card-tools"><span class="badge badge-primary">{{ $records->count() }} layanan</span></div></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Tanggal</th><th>Layanan</th><th>Konselor</th><th>Status</th><th>Tindak Lanjut</th><th></th></tr></thead><tbody>@forelse($records as $item)<tr><td>{{ $item->tanggal_konseling?->format('d/m/Y') }}</td><td>{{ $item->jenis_label }}<br><small class="text-muted">{{ $item->kategori_label }}</small></td><td>{{ $item->konselor?->nama_lengkap ?? '-' }}</td><td><span class="badge badge-{{ $item->status_badge }}">{{ $item->status_label }}</span></td><td>{{ $item->tanggal_tindak_lanjut?->format('d/m/Y') ?? '-' }}</td><td><a href="{{ route('admin.catatan-konseling.show',$item) }}" class="btn btn-info btn-sm"><i class="fas fa-eye"></i></a></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">Belum ada catatan konseling yang dapat Anda akses.</td></tr>@endforelse</tbody></table></div></div></div>@endif</div>
@stop
@section('js')<script>$(function(){$('#siswa_id').select2({theme:'bootstrap4',width:'100%',placeholder:'Cari nama, NISN, atau NIS Lokal',minimumInputLength:2,ajax:{url:@json(route('admin.catatan-konseling.students.search')),dataType:'json',delay:300,data:p=>({q:p.term}),processResults:d=>d},templateResult:item=>item.loading?item.text:$('<div><strong></strong><br><small class="text-muted"></small></div>').find('strong').text(item.text).end().find('small').text('NISN '+(item.nisn||'-')+' · '+item.kelas).end()})});</script>@stop
