@extends('layouts.admin')
@section('title', 'Smart Relasi Keluarga')
@section('content_header')
<div class="row mb-2"><div class="col-sm-6"><h1><i class="fas fa-project-diagram text-primary"></i> Smart Relasi Keluarga</h1></div><div class="col-sm-6"><ol class="breadcrumb float-sm-right"><li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li><li class="breadcrumb-item active">Relasi Keluarga</li></ol></div></div>
@stop
@section('content')
<div class="relasi-keluarga">
 <div class="card bg-gradient-primary text-white mb-4"><div class="card-body"><div class="row align-items-center"><div class="col-lg-8"><h4 class="mb-1">Deteksi relasi berbasis data yang sama</h4><p class="mb-0">Kandidat hanya memakai KK atau NIK yang identik. Konfirmasi operator diperlukan sebelum menjadi data relasi.</p></div><div class="col-lg-4 mt-3 mt-lg-0 text-lg-right"><strong>{{ $siblings->count() + $gtkCandidates->count() }}</strong> kandidat perlu ditinjau</div></div></div></div>
 @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
 <div class="card card-outline card-primary"><div class="card-header"><h3 class="card-title">Potensi saudara kandung</h3></div><div class="card-body table-responsive p-0"><table class="table table-hover mb-0"><thead><tr><th>Siswa</th><th>Potensi saudara</th><th>Dasar kecocokan</th><th></th></tr></thead><tbody>@forelse($siblings as $item)<tr><td>{{ $item['siswa']->nama_lengkap }} <small class="d-block text-muted">{{ $item['siswa']->kelasSaatIni?->nama_kelas }}</small></td><td>{{ $item['terkait']->nama_lengkap }} <small class="d-block text-muted">{{ $item['terkait']->kelasSaatIni?->nama_kelas }}</small></td><td><span class="badge badge-success">{{ implode(', ', $item['bukti']) }}</span></td><td><form method="POST" action="{{ route('admin.relasi-keluarga.store') }}">@csrf<input type="hidden" name="jenis_relasi" value="saudara_kandung"><input type="hidden" name="siswa_id" value="{{ $item['siswa']->id }}"><input type="hidden" name="siswa_terkait_id" value="{{ $item['terkait']->id }}">@foreach($item['bukti'] as $bukti)<input type="hidden" name="bukti[]" value="{{ $bukti }}">@endforeach<button class="btn btn-sm btn-success">Verifikasi</button></form></td></tr>@empty<tr><td colspan="4" class="text-center text-muted py-4">Tidak ada kandidat dengan KK/NIK orang tua yang sama.</td></tr>@endforelse</tbody></table></div></div>
 <div class="card card-outline card-success"><div class="card-header"><h3 class="card-title">Siswa dengan orang tua GTK</h3></div><div class="card-body table-responsive p-0"><table class="table table-hover mb-0"><thead><tr><th>Siswa</th><th>GTK</th><th>Relasi</th><th></th></tr></thead><tbody>@forelse($gtkCandidates as $item)<tr><td>{{ $item['siswa']->nama_lengkap }}</td><td>{{ $item['gtk']->nama_lengkap }} <small class="d-block text-muted">{{ $item['gtk']->jenis_ptk }}</small></td><td><span class="badge badge-success">NIK {{ strtolower($item['peran']) }} identik</span></td><td><form method="POST" action="{{ route('admin.relasi-keluarga.store') }}">@csrf<input type="hidden" name="jenis_relasi" value="anak_gtk"><input type="hidden" name="siswa_id" value="{{ $item['siswa']->id }}"><input type="hidden" name="gtk_id" value="{{ $item['gtk']->id }}"><input type="hidden" name="bukti[]" value="NIK {{ strtolower($item['peran']) }} identik"><button class="btn btn-sm btn-success">Verifikasi</button></form></td></tr>@empty<tr><td colspan="4" class="text-center text-muted py-4">Tidak ada kecocokan NIK orang tua dengan GTK.</td></tr>@endforelse</tbody></table></div></div>
 <div class="card card-outline card-secondary"><div class="card-header"><h3 class="card-title">Riwayat verifikasi</h3></div><div class="card-body table-responsive p-0"><table class="table table-sm mb-0"><thead><tr><th>Siswa</th><th>Relasi</th><th>Dasar</th><th>Waktu</th></tr></thead><tbody>@forelse($verified as $row)<tr><td>{{ $row->siswa?->nama_lengkap }}</td><td>{{ $row->jenis_relasi === 'anak_gtk' ? 'Anak GTK: '.$row->gtk?->nama_lengkap : 'Saudara: '.$row->siswaTerkait?->nama_lengkap }}</td><td>{{ implode(', ', $row->bukti_kecocokan ?? []) }}</td><td>{{ $row->diverifikasi_pada?->format('d M Y H:i') }}</td></tr>@empty<tr><td colspan="4" class="text-center text-muted py-3">Belum ada relasi terverifikasi.</td></tr>@endforelse</tbody></table></div></div>
</div>
@stop
