<?php

/*
|--------------------------------------------------------------------------
| Referensi Jadwal MAN 1 Metro 2026/2027
|--------------------------------------------------------------------------
|
| Kode berikut berasal dari sheet "Kode-guru-2026". Kode eksternal tidak
| menggantikan UUID SIMANSA; ia menjadi alias operasional yang dapat ditinjau
| dan diedit admin pada setiap tahun pelajaran.
|
*/

$guru = [
    ['1', 'Hi.Gunawan Susanto, S.Pd,M.Pd', 'Gunawan Susanto', 'kepala_madrasah'],
    ['2', 'Hi. Suhardi, S.Pd. M.P.Fis'],
    ['3', 'Drs. Sudriyatmoko'],
    ['4', 'Murniyanto, S.Pd, M.Pd'],
    ['5', 'Eva Kurniasih, SE'],
    ['6', 'Rokiban, S.Ag, M.PdI'],
    ['7', 'Dra. Hj. Zuraida'],
    ['8', 'Dra. Hj. Erlina Harniati'],
    ['9', 'Dra. Hj. Erniwati, M.Pd.I'],
    ['10', 'Mustofa Khoiri, M.Si'],
    ['11', 'Dra. Hj. Ade Suhairiah'],
    ['12', 'Hi. Sarbiyono, S.Pd, M.Pd'],
    ['13', 'Drs. Buyung Prana Jaya, M.Pd.I'],
    ['14', 'Drs. Hi. Gufron, M.Pd.I'],
    ['15', 'Ismoyo, S.Pd'],
    ['16', 'Lilis Odiyah, S.Pd'],
    ['17', 'Dra. Hj. Eni Susiati, M.Pd'],
    ['18', 'Hj. Endang W, S.Pd.M.P.Kim'],
    ['19', 'Kasiman, S.PdI, M.Pd.I'],
    ['20', 'Wagino, S.Pd. M.Pd.I'],
    ['21', 'H. Gunawan S, S.Ag, M.Pd.I', 'Gunawan Santoso', 'guru_fikih'],
    ['22', 'Hi. Khabib Wahyono, M.Kes'],
    ['23', 'Mustolah, S.Ag, M.Pd.I'],
    ['24', 'Helyani, S.Ag, M.Pd.I'],
    ['25', 'Hj. Endang Purnawati, S.Pd'],
    ['26', 'Feri Mitra Liana, S.Pd'],
    ['27', 'Iwan Saputra, S.Pd, M.Kes'],
    ['28', 'Miswanto, S.Pd, M.Pd'],
    ['29', "Musta'in, S.Ag, M.Pd.I"],
    ['30', 'Edya Rosita, S.Ag'],
    ['31', 'Dahlia, S.Pd'],
    ['32', 'Evi Kurniawati, SE'],
    ['33', 'Susi Masjuita, S.Ag'],
    ['34', 'Kartika Dewi, S.Pd'],
    ['35', 'Inta Wahidah, S.Pd'],
    ['36', 'M. Dorajat, S.Pd, M.Pd'],
    ['37', 'Eldi Asmi, S.Sos'],
    ['38', 'Supartini, SE'],
    ['39', 'Ardiyana, S.Pd'],
    ['40', 'Tati Aeris, S.Si'],
    ['41', 'Hj. Nury Wardhani, S.TP.M.Pd'],
    ['42', 'Dian Rahmawati, S.Pd'],
    ['43', 'Nanang Sukaryono, S.Kom'],
    ['44', 'Nur Sobari, S.Pd., M.Pd'],
    ['45', 'Mita Nafisyah, S.Pd'],
    ['46', 'Sudesti Vindi Pratiwi, S.Si'],
    ['47', 'Oki Sahroni, S.Si'],
    ['48', 'Ratia Hesti Putridinanti, S.Pd'],
    ['49', 'Aslihatus Sania Firdaus, S.E,Sy'],
    ['50', 'Tri Hayati, S.Pd'],
    ['51', 'Intan Permata Sari, S.T'],
    ['52', 'Novi Candra Dewi, S.Si'],
    ['53', 'Nita Hidayati, S.Pd'],
    ['54', 'Susi Maya Sari, S.Pd'],
    ['55', 'Kemas Yoga Pradana, S.Pd'],
    ['56', 'Milyani, S.Pd'],
    ['57', 'Chusnul Nur Muttaqin, S.Pd'],
    ['58', 'Rizki Suci Pratiwi, S.Pd'],
    ['59', 'Sholeha, S.Pd'],
    ['60', 'Inggrit Resti Faradisa, S.Pd.'],
    ['61', 'Suhandian, S.Pd'],
    ['62', "Latifatus Sya'ada, S.H"],
    ['63', 'Tri Mukhul Jannah, S.Pd, M.Pd'],
    ['64', 'Miftahul Jannah, S.Pd'],
    ['65', 'Kholifah Nuzulul Laili, S.Pd'],
    ['66', "Azizatun Nafi'ah, S.Si, M.Si"],
    ['67', 'Fahrurrozi, S.Pd.I'],
    ['68', 'Irhamudin Abdullah, M.Pd.I'],
    ['69', 'Apipudin, M.Pd.I'],
    ['70', 'Alif Darmawan Adi P, S.H'],
    ['71', 'Ristiani, M.Pd.I'],
    ['72', 'Nindi Aulia Nisa, S.Pd'],
    ['73', 'Tia Anngraini, S.Pd'],
    ['74', 'Binti Dzakiyah Sholehah, S.Pd'],
    ['75', 'M. Januar, S.Pd'],
    ['76', 'Anailil Fasikhah, M.Pd'],
    ['77', 'Novia Mayangsari, S.Pd'],
    ['78', 'Mardhatillah Hafidzah H., S.Pd'],
    ['79', 'Reksa Qodari Assidik, M.Kom'],
    ['80', 'Faris Fathurrohman, M.Pd.I'],
    ['81', 'Dinda Lathofiana Rohman, S.Pd'],
    ['82', 'Nurlaila, S.E, M.Pd.'],
    ['83', 'Ratnawati, S.Ag'],
    ['84', 'Salsabila Junika Destalia, S.Psi'],
    ['85', 'Hafif Syihamuddin, M.Pd'],
    ['86', 'Devi Lestari, M.Pd'],
    ['87', 'Heni Astuti, S.Ag'],
    ['88', 'Januba Roudloh Salsabila, S.Pd'],
    ['89', 'Malikatun KM. S, S.Sos., M.A'],
    ['90', 'Isna Istikomah, S.Pd'],
];

$mapel = [
    ['A', "Qur'an Hadist", 'M-QH'],
    ['B', 'Aqidah Akhlak', 'M-AA'],
    ['C', 'Fiqih', 'M-FIQ'],
    ['D', 'SKI', 'M-SKI'],
    ['E', 'Bahasa Arab', 'M-BA'],
    ['F', 'PKn', 'M-PP-F'],
    ['G', 'B. dan Sastra Indonesia', 'M-BIN-F'],
    ['H', 'Bahasa Inggris', 'M-BING-F'],
    ['I', 'Matematika', 'M-MAT-F'],
    ['J', 'Matematika Tingkat Lanjut', 'M-MATL'],
    ['K', 'Fisika', 'M-FIS'],
    ['L', 'Kimia', 'M-KIM'],
    ['M', 'Biologi', 'M-BIO'],
    ['N', 'Sejarah Tingkat Lanjut', 'M-SJRL'],
    ['O', 'Sejarah', 'M-SJR-F'],
    ['P', 'Geografi', 'M-GEO'],
    ['Q', 'Ekonomi', 'M-EKO'],
    ['R', 'Sosiologi', 'M-SOS'],
    ['S', 'Penjas ORKES', 'M-PJOK-F'],
    ['T', 'Seni Budaya', 'M-SENBUD-F'],
    ['U', 'Tahfidz', 'M-TAHFZ'],
    ['V', 'Prakarya & Kewirausahaan', 'M-PKW-F'],
    ['W', 'Bahasa Lampung', 'M-BLMP'],
    ['X', 'Keterampilan Agama', 'M-KTAGM'],
    ['Y', 'Informatika (TIK)', 'M-INF-F'],
    ['Z', 'Bimbingan Konseling', 'M-BK'],
];

return [
    'source' => 'jadwal_excel',
    'tahun_mulai' => 2026,
    'tahun_selesai' => 2027,
    'guru' => array_map(fn (array $row) => [
        'code' => $row[0],
        'name' => $row[1],
        'canonical_hint' => $row[2] ?? null,
        'context' => $row[3] ?? null,
    ], $guru),
    'mapel' => array_map(fn (array $row) => [
        'code' => $row[0],
        'name' => $row[1],
        'canonical_code' => $row[2],
    ], $mapel),
];
