<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Template Mata Pelajaran
    |--------------------------------------------------------------------------
    |
    | Template mata pelajaran untuk berbagai kurikulum.
    | Digunakan untuk form checklist pada pembuatan mata pelajaran baru.
    |
    */

    'K13' => [
        'rumpun_pai' => [
            'label' => 'Rumpun PAI (Madrasah)',
            'description' => 'Khusus untuk Madrasah di bawah naungan Kemenag',
            'mapel' => [
                [
                    'kode_mapel' => 'QH',
                    'nama_mapel' => 'Al-Quran Hadits',
                    'kelompok' => 'A',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 2,
                    'is_mapel_agama' => true,
                    'jenis_agama' => 'islam',
                    'is_rumpun_pai' => true,
                    'sub_pai' => 'quran_hadits',
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'AA',
                    'nama_mapel' => 'Akidah Akhlak',
                    'kelompok' => 'A',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 2,
                    'is_mapel_agama' => true,
                    'jenis_agama' => 'islam',
                    'is_rumpun_pai' => true,
                    'sub_pai' => 'akidah_akhlak',
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'FIQ',
                    'nama_mapel' => 'Fikih',
                    'kelompok' => 'A',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 2,
                    'is_mapel_agama' => true,
                    'jenis_agama' => 'islam',
                    'is_rumpun_pai' => true,
                    'sub_pai' => 'fikih',
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'SKI',
                    'nama_mapel' => 'Sejarah Kebudayaan Islam',
                    'kelompok' => 'A',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 2,
                    'is_mapel_agama' => true,
                    'jenis_agama' => 'islam',
                    'is_rumpun_pai' => true,
                    'sub_pai' => 'ski',
                    'kkm_default' => 75,
                ],
            ],
        ],
        
        'pai_umum' => [
            'label' => 'Pendidikan Agama Islam (Umum)',
            'description' => 'Untuk sekolah umum (bukan Madrasah)',
            'mapel' => [
                [
                    'kode_mapel' => 'PAI',
                    'nama_mapel' => 'Pendidikan Agama Islam dan Budi Pekerti',
                    'kelompok' => 'A',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 3,
                    'is_mapel_agama' => true,
                    'jenis_agama' => 'islam',
                    'kkm_default' => 75,
                ],
            ],
        ],
        
        'bahasa_arab' => [
            'label' => 'Bahasa Arab',
            'description' => 'Bahasa Arab wajib untuk Madrasah',
            'mapel' => [
                [
                    'kode_mapel' => 'BA',
                    'nama_mapel' => 'Bahasa Arab',
                    'kelompok' => 'A',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 2,
                    'is_bahasa_arab' => true,
                    'kkm_default' => 75,
                ],
            ],
        ],

        'kelompok_a' => [
            'label' => 'Kelompok A (Wajib Umum)',
            'description' => 'Mata pelajaran umum wajib untuk semua siswa',
            'mapel' => [
                [
                    'kode_mapel' => 'BIN',
                    'nama_mapel' => 'Bahasa Indonesia',
                    'kelompok' => 'A',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 6,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'MAT',
                    'nama_mapel' => 'Matematika',
                    'kelompok' => 'A',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 5,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'BING',
                    'nama_mapel' => 'Bahasa Inggris',
                    'kelompok' => 'A',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 4,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'PPKN',
                    'nama_mapel' => 'Pendidikan Pancasila dan Kewarganegaraan',
                    'kelompok' => 'A',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 3,
                    'kkm_default' => 75,
                ],
            ],
        ],

        'kelompok_b' => [
            'label' => 'Kelompok B (Wajib)',
            'description' => 'Mata pelajaran pengembangan diri dan keterampilan',
            'mapel' => [
                [
                    'kode_mapel' => 'IPA',
                    'nama_mapel' => 'Ilmu Pengetahuan Alam',
                    'kelompok' => 'B',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 5,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'IPS',
                    'nama_mapel' => 'Ilmu Pengetahuan Sosial',
                    'kelompok' => 'B',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 4,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'SENBUD',
                    'nama_mapel' => 'Seni Budaya',
                    'kelompok' => 'B',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 3,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'PJOK',
                    'nama_mapel' => 'Pendidikan Jasmani, Olahraga, dan Kesehatan',
                    'kelompok' => 'B',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 3,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'PKWU',
                    'nama_mapel' => 'Prakarya dan Kewirausahaan',
                    'kelompok' => 'B',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 2,
                    'kkm_default' => 75,
                ],
            ],
        ],

        'kelompok_c_mipa' => [
            'label' => 'Kelompok C - Peminatan MIPA (SMA/MA)',
            'description' => 'Mata pelajaran peminatan Matematika dan Ilmu Pengetahuan Alam',
            'mapel' => [
                [
                    'kode_mapel' => 'MAT-P',
                    'nama_mapel' => 'Matematika (Peminatan)',
                    'kelompok' => 'C',
                    'kategori' => 'Peminatan',
                    'jam_pelajaran' => 4,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'BIOLOGI',
                    'nama_mapel' => 'Biologi',
                    'kelompok' => 'C',
                    'kategori' => 'Peminatan',
                    'jam_pelajaran' => 4,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'FISIKA',
                    'nama_mapel' => 'Fisika',
                    'kelompok' => 'C',
                    'kategori' => 'Peminatan',
                    'jam_pelajaran' => 4,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'KIMIA',
                    'nama_mapel' => 'Kimia',
                    'kelompok' => 'C',
                    'kategori' => 'Peminatan',
                    'jam_pelajaran' => 4,
                    'kkm_default' => 75,
                ],
            ],
        ],

        'kelompok_c_ips' => [
            'label' => 'Kelompok C - Peminatan IPS (SMA/MA)',
            'description' => 'Mata pelajaran peminatan Ilmu Pengetahuan Sosial',
            'mapel' => [
                [
                    'kode_mapel' => 'GEO',
                    'nama_mapel' => 'Geografi',
                    'kelompok' => 'C',
                    'kategori' => 'Peminatan',
                    'jam_pelajaran' => 4,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'SEJ',
                    'nama_mapel' => 'Sejarah',
                    'kelompok' => 'C',
                    'kategori' => 'Peminatan',
                    'jam_pelajaran' => 4,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'EKO',
                    'nama_mapel' => 'Ekonomi',
                    'kelompok' => 'C',
                    'kategori' => 'Peminatan',
                    'jam_pelajaran' => 4,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'SOS',
                    'nama_mapel' => 'Sosiologi',
                    'kelompok' => 'C',
                    'kategori' => 'Peminatan',
                    'jam_pelajaran' => 4,
                    'kkm_default' => 75,
                ],
            ],
        ],

        'kelompok_c_bahasa' => [
            'label' => 'Kelompok C - Peminatan Bahasa (SMA/MA)',
            'description' => 'Mata pelajaran peminatan Bahasa dan Budaya',
            'mapel' => [
                [
                    'kode_mapel' => 'BIN-P',
                    'nama_mapel' => 'Bahasa Indonesia (Peminatan)',
                    'kelompok' => 'C',
                    'kategori' => 'Peminatan',
                    'jam_pelajaran' => 4,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'BING-P',
                    'nama_mapel' => 'Bahasa Inggris (Peminatan)',
                    'kelompok' => 'C',
                    'kategori' => 'Peminatan',
                    'jam_pelajaran' => 4,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'BASING',
                    'nama_mapel' => 'Bahasa Asing Lainnya',
                    'kelompok' => 'C',
                    'kategori' => 'Peminatan',
                    'jam_pelajaran' => 4,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'SASTRA',
                    'nama_mapel' => 'Sastra Indonesia',
                    'kelompok' => 'C',
                    'kategori' => 'Peminatan',
                    'jam_pelajaran' => 4,
                    'kkm_default' => 75,
                ],
            ],
        ],

        'muatan_lokal' => [
            'label' => 'Muatan Lokal (Optional)',
            'description' => 'Mata pelajaran muatan lokal sesuai kebutuhan daerah',
            'mapel' => [
                [
                    'kode_mapel' => 'BJW',
                    'nama_mapel' => 'Bahasa Jawa',
                    'kategori' => 'Muatan Lokal',
                    'jam_pelajaran' => 2,
                    'is_muatan_lokal' => true,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'BSUNDA',
                    'nama_mapel' => 'Bahasa Sunda',
                    'kategori' => 'Muatan Lokal',
                    'jam_pelajaran' => 2,
                    'is_muatan_lokal' => true,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'KOMPUTER',
                    'nama_mapel' => 'Komputer dan Informatika',
                    'kategori' => 'Muatan Lokal',
                    'jam_pelajaran' => 2,
                    'is_muatan_lokal' => true,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'KESENIAN',
                    'nama_mapel' => 'Kesenian Daerah',
                    'kategori' => 'Muatan Lokal',
                    'jam_pelajaran' => 2,
                    'is_muatan_lokal' => true,
                    'kkm_default' => 75,
                ],
            ],
        ],
    ],

    'MERDEKA' => [
        'pai_madrasah' => [
            'label' => 'PAI Madrasah (Kemenag)',
            'description' => 'Rumpun PAI khusus Madrasah Kurikulum Merdeka',
            'mapel' => [
                [
                    'kode_mapel' => 'M-QH',
                    'nama_mapel' => 'Al-Quran Hadits',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 2,
                    'is_mapel_agama' => true,
                    'jenis_agama' => 'islam',
                    'is_rumpun_pai' => true,
                    'sub_pai' => 'quran_hadits',
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-AA',
                    'nama_mapel' => 'Akidah Akhlak',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 2,
                    'is_mapel_agama' => true,
                    'jenis_agama' => 'islam',
                    'is_rumpun_pai' => true,
                    'sub_pai' => 'akidah_akhlak',
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-FIQ',
                    'nama_mapel' => 'Fikih',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 2,
                    'is_mapel_agama' => true,
                    'jenis_agama' => 'islam',
                    'is_rumpun_pai' => true,
                    'sub_pai' => 'fikih',
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-SKI',
                    'nama_mapel' => 'Sejarah Kebudayaan Islam',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 2,
                    'is_mapel_agama' => true,
                    'jenis_agama' => 'islam',
                    'is_rumpun_pai' => true,
                    'sub_pai' => 'ski',
                    'kkm_default' => 75,
                ],
            ],
        ],

        'bahasa_arab' => [
            'label' => 'Bahasa Arab',
            'description' => 'Bahasa Arab wajib untuk Madrasah',
            'mapel' => [
                [
                    'kode_mapel' => 'M-BA',
                    'nama_mapel' => 'Bahasa Arab',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 2,
                    'is_bahasa_arab' => true,
                    'kkm_default' => 75,
                ],
            ],
        ],

        'wajib_umum' => [
            'label' => 'Mata Pelajaran Wajib (SD/SMP)',
            'description' => 'Mata pelajaran wajib Kurikulum Merdeka untuk SD/SMP',
            'mapel' => [
                [
                    'kode_mapel' => 'M-PAI',
                    'nama_mapel' => 'Pendidikan Agama Islam dan Budi Pekerti',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 3,
                    'is_mapel_agama' => true,
                    'jenis_agama' => 'islam',
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-PPKN',
                    'nama_mapel' => 'Pendidikan Pancasila',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 2,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-BIN',
                    'nama_mapel' => 'Bahasa Indonesia',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 6,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-MAT',
                    'nama_mapel' => 'Matematika',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 5,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-IPAS',
                    'nama_mapel' => 'Ilmu Pengetahuan Alam dan Sosial',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 5,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-BING',
                    'nama_mapel' => 'Bahasa Inggris',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 3,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-PJOK',
                    'nama_mapel' => 'Pendidikan Jasmani Olahraga dan Kesehatan',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 2,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-SENBUD',
                    'nama_mapel' => 'Seni dan Budaya',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 2,
                    'kkm_default' => 75,
                ],
            ],
        ],

        'wajib_sma' => [
            'label' => 'Mata Pelajaran Wajib (SMA/MA)',
            'description' => 'Mata pelajaran wajib Kurikulum Merdeka untuk SMA/MA Fase F',
            'mapel' => [
                [
                    'kode_mapel' => 'M-PAI-F',
                    'nama_mapel' => 'Pendidikan Agama Islam dan Budi Pekerti',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 2,
                    'is_mapel_agama' => true,
                    'jenis_agama' => 'islam',
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-PP-F',
                    'nama_mapel' => 'Pendidikan Pancasila',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 2,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-BIN-F',
                    'nama_mapel' => 'Bahasa Indonesia',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 4,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-MAT-F',
                    'nama_mapel' => 'Matematika',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 4,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-SEJ-F',
                    'nama_mapel' => 'Sejarah',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 2,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-BING-F',
                    'nama_mapel' => 'Bahasa Inggris',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 3,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-PJOK-F',
                    'nama_mapel' => 'Pendidikan Jasmani Olahraga dan Kesehatan',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 2,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-SEN-F',
                    'nama_mapel' => 'Seni (Musik/Rupa/Teater/Tari)',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 2,
                    'kkm_default' => 75,
                ],
            ],
        ],

        'pilihan_sma' => [
            'label' => 'Mata Pelajaran Pilihan (SMA/MA)',
            'description' => 'Mata pelajaran pilihan sesuai minat dan bakat siswa SMA/MA',
            'mapel' => [
                [
                    'kode_mapel' => 'M-INF',
                    'nama_mapel' => 'Informatika',
                    'kategori' => 'Pilihan',
                    'jam_pelajaran' => 3,
                    'is_mapel_pilihan' => true,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-FIS',
                    'nama_mapel' => 'Fisika',
                    'kategori' => 'Pilihan',
                    'jam_pelajaran' => 3,
                    'is_mapel_pilihan' => true,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-KIM',
                    'nama_mapel' => 'Kimia',
                    'kategori' => 'Pilihan',
                    'jam_pelajaran' => 3,
                    'is_mapel_pilihan' => true,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-BIO',
                    'nama_mapel' => 'Biologi',
                    'kategori' => 'Pilihan',
                    'jam_pelajaran' => 3,
                    'is_mapel_pilihan' => true,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-EKO',
                    'nama_mapel' => 'Ekonomi',
                    'kategori' => 'Pilihan',
                    'jam_pelajaran' => 3,
                    'is_mapel_pilihan' => true,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-SOS',
                    'nama_mapel' => 'Sosiologi',
                    'kategori' => 'Pilihan',
                    'jam_pelajaran' => 3,
                    'is_mapel_pilihan' => true,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-GEO',
                    'nama_mapel' => 'Geografi',
                    'kategori' => 'Pilihan',
                    'jam_pelajaran' => 3,
                    'is_mapel_pilihan' => true,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-ANTRO',
                    'nama_mapel' => 'Antropologi',
                    'kategori' => 'Pilihan',
                    'jam_pelajaran' => 3,
                    'is_mapel_pilihan' => true,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-BJEP',
                    'nama_mapel' => 'Bahasa Jepang',
                    'kategori' => 'Pilihan',
                    'jam_pelajaran' => 3,
                    'is_mapel_pilihan' => true,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-BMAND',
                    'nama_mapel' => 'Bahasa Mandarin',
                    'kategori' => 'Pilihan',
                    'jam_pelajaran' => 3,
                    'is_mapel_pilihan' => true,
                    'kkm_default' => 75,
                ],
            ],
        ],

        'projek' => [
            'label' => 'Projek Penguatan Profil Pelajar Pancasila',
            'description' => 'Projek P5 untuk Kurikulum Merdeka',
            'mapel' => [
                [
                    'kode_mapel' => 'M-P5',
                    'nama_mapel' => 'Projek Penguatan Profil Pelajar Pancasila',
                    'kategori' => 'Wajib',
                    'jam_pelajaran' => 2,
                    'is_projek_p5' => true,
                    'capaian_pembelajaran' => 'Peserta didik mampu mengembangkan profil pelajar Pancasila melalui projek berbasis permasalahan nyata di lingkungan sekitar.',
                    'kkm_default' => 75,
                ],
            ],
        ],

        'muatan_lokal' => [
            'label' => 'Muatan Lokal',
            'description' => 'Mata pelajaran muatan lokal sesuai kebutuhan daerah',
            'mapel' => [
                [
                    'kode_mapel' => 'M-BJW',
                    'nama_mapel' => 'Bahasa Jawa',
                    'kategori' => 'Muatan Lokal',
                    'jam_pelajaran' => 2,
                    'is_muatan_lokal' => true,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-BSUN',
                    'nama_mapel' => 'Bahasa Sunda',
                    'kategori' => 'Muatan Lokal',
                    'jam_pelajaran' => 2,
                    'is_muatan_lokal' => true,
                    'kkm_default' => 75,
                ],
                [
                    'kode_mapel' => 'M-BBALI',
                    'nama_mapel' => 'Bahasa Bali',
                    'kategori' => 'Muatan Lokal',
                    'jam_pelajaran' => 2,
                    'is_muatan_lokal' => true,
                    'kkm_default' => 75,
                ],
            ],
        ],
    ],
];
