@extends('adminlte::page')

@section('title', 'Detail Nilai RDM')

@section('content_header')
<div class="row mb-2"><div class="col-sm-6"><h1><i class="fas fa-list-alt text-primary mr-2"></i>Detail Nilai RDM</h1></div><div class="col-sm-6"><ol class="breadcrumb float-sm-right"><li class="breadcrumb-item"><a href="{{ route('admin.gtk.dashboard') }}">Dashboard</a></li><li class="breadcrumb-item"><a href="{{ route('admin.nilai-rdm.index') }}">Rekap Nilai RDM</a></li><li class="breadcrumb-item active">Detail Siswa</li></ol></div></div>
@stop

@section('content')
<div class="nilai-rdm-detail pb-4">
    <div class="card bg-gradient-primary text-white mb-3"><div class="card-body py-3 px-4"><div class="row align-items-center"><div class="col-lg-8"><div class="small font-weight-bold text-uppercase mb-1"><i class="fas fa-lock mr-1"></i> REKAP BACA-SAJA RDM</div><h2 class="h4 font-weight-bold mb-1">{{ $siswa->nama_lengkap }}</h2><p class="mb-0 text-white-50">NISN {{ $siswa->nisn ?: '-' }} · {{ $membership->kelas?->nama_lengkap ?? $membership->kelas?->nama_kelas ?? '-' }}</p></div><div class="col-lg-4 mt-3 mt-lg-0"><div class="nilai-rdm-detail__year"><small>TAHUN PELAJARAN</small><strong>{{ $year->nama }}</strong><span>Sumber data: RDM tersinkron</span></div></div></div></div></div>
    <div class="row mb-3"><div class="col-6 col-md-3 mb-2 mb-md-0"><div class="info-box mb-0"><span class="info-box-icon bg-primary elevation-1"><i class="fas fa-list-check"></i></span><div class="info-box-content"><span class="info-box-text">Nilai Masuk</span><span class="info-box-number">{{ number_format($scoreCount) }}</span></div></div></div><div class="col-6 col-md-3 mb-2 mb-md-0"><div class="info-box mb-0"><span class="info-box-icon bg-info elevation-1"><i class="fas fa-book"></i></span><div class="info-box-content"><span class="info-box-text">Mapel</span><span class="info-box-number">{{ number_format($scores->flatten(1)->pluck('mata_pelajaran_id')->unique()->count()) }}</span></div></div></div><div class="col-6 col-md-3"><div class="info-box mb-0"><span class="info-box-icon bg-success elevation-1"><i class="fas fa-calendar-alt"></i></span><div class="info-box-content"><span class="info-box-text">Semester</span><span class="info-box-number">{{ number_format($scores->count()) }}</span></div></div></div><div class="col-6 col-md-3"><div class="info-box mb-0"><span class="info-box-icon bg-warning elevation-1"><i class="fas fa-chart-line"></i></span><div class="info-box-content"><span class="info-box-text">Rata-rata</span><span class="info-box-number">{{ $average !== null ? number_format($average, 2) : '-' }}</span></div></div></div></div>
    <div class="card card-outline card-primary"><div class="card-header"><h3 class="card-title"><i class="fas fa-layer-group text-primary mr-2"></i>Nilai per Semester dan Mata Pelajaran</h3><div class="card-tools"><a href="{{ route('admin.nilai-rdm.index') }}" class="btn btn-sm btn-outline-secondary"><i class="fas fa-arrow-left mr-1"></i>Kembali</a></div></div><div class="card-body"><div class="alert alert-light border rdm-detail-note mb-3"><i class="fas fa-info-circle text-primary mr-1"></i>Data ini hanya berasal dari sinkronisasi RDM pada rombel dan tahun pelajaran aktif. Nilai tidak dapat diubah dari halaman wali kelas.</div>
        @forelse($scores as $semester => $semesterScores)
            <details class="rdm-semester" @if($loop->first) open @endif><summary><span><i class="fas fa-chevron-right rdm-semester__chevron"></i>{{ \App\Models\NilaiSiswa::SEMESTER_LABELS[$semester] ?? 'Semester '.$semester }}</span><span class="rdm-semester__meta">{{ $semesterScores->count() }} nilai · Rata-rata {{ $semesterScores->pluck('nilai')->filter(fn ($value) => $value !== null)->avg() !== null ? number_format($semesterScores->pluck('nilai')->filter(fn ($value) => $value !== null)->avg(), 2) : '-' }}</span></summary><div class="rdm-semester__body"><div class="table-responsive d-none d-md-block"><table class="table table-sm table-hover mb-0 rdm-score-table"><thead><tr><th>Mata Pelajaran</th><th>Kode</th><th class="text-center">Nilai</th><th class="text-center">Predikat</th><th>Sinkron Terakhir</th></tr></thead><tbody>@foreach($semesterScores as $score)<tr><td><strong>{{ $score->mataPelajaran?->nama_mapel ?? '-' }}</strong></td><td><code>{{ $score->mataPelajaran?->kode_mapel ?? '-' }}</code></td><td class="text-center"><span class="rdm-score">{{ $score->nilai !== null ? number_format($score->nilai, 2) : '-' }}</span></td><td class="text-center"><span class="badge badge-light border">{{ $score->predikat ?: \App\Models\NilaiSiswa::hitungPredikat($score->nilai) }}</span></td><td><small>{{ $score->imported_at?->translatedFormat('d M Y H:i') ?? '-' }}</small></td></tr>@endforeach</tbody></table></div><div class="d-md-none rdm-score-cards">@foreach($semesterScores as $score)<article class="rdm-score-card"><div><strong>{{ $score->mataPelajaran?->nama_mapel ?? '-' }}</strong><small>{{ $score->mataPelajaran?->kode_mapel ?? '-' }} · Sinkron {{ $score->imported_at?->translatedFormat('d M Y H:i') ?? '-' }}</small></div><div class="rdm-score-card__value"><strong>{{ $score->nilai !== null ? number_format($score->nilai, 2) : '-' }}</strong><span>{{ $score->predikat ?: \App\Models\NilaiSiswa::hitungPredikat($score->nilai) }}</span></div></article>@endforeach</div></div></details>
        @empty
            <div class="text-center text-muted py-5"><i class="fas fa-database d-block mb-2 fa-lg"></i>Belum ada nilai RDM tersinkron untuk siswa ini pada tahun pelajaran aktif.</div>
        @endforelse
    </div></div>
</div>
@stop

@section('css')
<style>
.nilai-rdm-detail .card{border-radius:14px;box-shadow:0 7px 18px rgba(15,23,42,.05)}.nilai-rdm-detail__year{padding:12px 14px;border:1px solid rgba(255,255,255,.3);border-radius:11px;background:rgba(255,255,255,.12)}.nilai-rdm-detail__year small,.nilai-rdm-detail__year strong,.nilai-rdm-detail__year span{display:block}.nilai-rdm-detail__year small{font-size:.68rem;font-weight:800;letter-spacing:.06em}.nilai-rdm-detail__year strong{font-size:1.06rem}.nilai-rdm-detail__year span{margin-top:2px;font-size:.75rem;opacity:.9}.rdm-detail-note{font-size:.82rem;line-height:1.5}.rdm-semester{margin-bottom:10px;border:1px solid #dbe4f0;border-radius:12px;background:#fff;overflow:hidden}.rdm-semester:last-child{margin-bottom:0}.rdm-semester summary{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:13px 15px;background:#f8fafc;color:#1e3162;cursor:pointer;font-weight:750;list-style:none}.rdm-semester summary::-webkit-details-marker{display:none}.rdm-semester__chevron{margin-right:8px;color:#4f46e5;transition:transform .18s ease}.rdm-semester[open] .rdm-semester__chevron{transform:rotate(90deg)}.rdm-semester__meta{color:#70809e;font-size:.75rem;font-weight:600;text-align:right}.rdm-semester__body{border-top:1px solid #e8edf5}.rdm-score-table thead th{border-top:0;background:#f6f8fc;color:#52627a;font-size:.68rem;text-transform:uppercase;white-space:nowrap}.rdm-score-table td{vertical-align:middle}.rdm-score{display:inline-block;min-width:56px;padding:4px 7px;border-radius:8px;background:#eff6ff;color:#1d4ed8;font-weight:800}.rdm-score-cards{padding:9px}.rdm-score-card{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px;border-bottom:1px solid #edf1f6}.rdm-score-card:last-child{border-bottom:0}.rdm-score-card>div:first-child{min-width:0}.rdm-score-card strong,.rdm-score-card small{display:block}.rdm-score-card small{margin-top:3px;color:#718096;font-size:.7rem;line-height:1.4}.rdm-score-card__value{flex:0 0 auto;text-align:right}.rdm-score-card__value strong{color:#1d4ed8;font-size:1rem}.rdm-score-card__value span{display:inline-block;margin-top:3px;padding:2px 6px;border:1px solid #dbe4f0;border-radius:999px;color:#52627a;font-size:.68rem;font-weight:700}@media(max-width:767px){.nilai-rdm-detail .info-box{min-height:74px}.nilai-rdm-detail .info-box-icon{width:46px;font-size:1rem}.nilai-rdm-detail .info-box-number{font-size:1rem}.rdm-semester summary{align-items:flex-start;flex-direction:column}.rdm-semester__meta{text-align:left}.nilai-rdm-detail .card-header{align-items:flex-start}.nilai-rdm-detail .card-tools{margin-top:7px;margin-left:0;float:none}}
</style>
@stop
