@extends('adminlte::page')
@section('title', 'Asatidz Asrama')
@section('content_header') @stop
@section('content')
@include('asrama._alerts')
@php $heroTitle='Asatidz Asrama';$heroDescription='Assign GTK SIMANSA dan berikan akses portal serta input nilai asrama secara otomatis.';$heroAction='<button class="btn btn-light" data-toggle="modal" data-target="#assignAsatidz"><i class="fas fa-user-plus mr-1"></i> Assign Asatidz</button>'; @endphp
@include('asrama._hero')
<div class="asrama-panel"><div class="asrama-panel__body asrama-form"><form method="get" class="row align-items-end"><div class="col-md-5"><label>Filter Unit</label><select name="asrama_id" class="form-control"><option value="">Semua unit</option>@foreach($units as $unit)<option value="{{ $unit->id }}" @selected($selectedUnit===$unit->id)>{{ $unit->nama }}</option>@endforeach</select></div><div class="col-md-2 mt-2"><button class="btn btn-info btn-block">Terapkan</button></div></form></div></div>
<div class="asrama-panel"><div class="table-responsive"><table class="table asrama-table"><thead><tr><th>GTK</th><th>Unit</th><th>Identitas</th><th>Jabatan</th><th>Akun</th><th>Status</th><th></th></tr></thead><tbody>
@forelse($records as $item)<tr><td><strong>{{ $item->gtk->nama_lengkap }}</strong><br><small>{{ $item->gtk->nip ?: $item->gtk->nuptk }}</small></td><td>{{ $item->asrama->nama }}</td><td>{{ $item->nomor_identitas ?: '-' }}</td><td>{{ $item->jabatan }}</td><td>{{ $item->gtk->user?'Terhubung':'Belum ada akun' }}</td><td><span class="asrama-badge {{ $item->is_active?'asrama-badge--active':'asrama-badge--muted' }}">{{ $item->is_active?'Aktif':'Nonaktif' }}</span></td><td><button class="btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#editAsatidz{{ $item->id }}">Edit</button></td></tr>
@empty<tr><td colspan="7" class="asrama-empty"><i class="fas fa-chalkboard-teacher"></i>Belum ada asatidz.</td></tr>@endforelse
</tbody></table></div><div class="p-3">{{ $records->links() }}</div></div>
<div class="modal fade" id="assignAsatidz"><div class="modal-dialog modal-lg"><form method="post" action="{{ route('asrama.asatidz.store') }}" class="modal-content asrama-form">@csrf<div class="modal-header"><h5>Assign GTK sebagai Asatidz</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="row"><div class="col-md-6"><label>Unit</label><select required name="asrama_id" class="form-control">@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->nama }}</option>@endforeach</select></div><div class="col-md-6"><label>GTK</label><select required name="gtk_id" class="form-control"><option value="">Pilih GTK</option>@foreach($gtks as $gtk)<option value="{{ $gtk->id }}">{{ $gtk->nama_lengkap }}{{ $gtk->nip?' · '.$gtk->nip:'' }}</option>@endforeach</select></div><div class="col-md-6 mt-3"><label>Jabatan</label><input required name="jabatan" value="Asatidz" class="form-control"></div><div class="col-md-6 mt-3"><label>Nomor identitas</label><input name="nomor_identitas" class="form-control"></div><div class="col-md-6 mt-3"><label>Tanggal mulai</label><input type="date" name="tanggal_mulai" value="{{ now()->toDateString() }}" class="form-control"></div><div class="col-12 mt-3"><label>Catatan</label><textarea name="catatan" class="form-control"></textarea></div></div></div><div class="modal-footer"><button class="btn btn-info">Assign Asatidz</button></div></form></div></div>
@foreach($records as $item)<div class="modal fade" id="editAsatidz{{ $item->id }}"><div class="modal-dialog"><form method="post" action="{{ route('asrama.asatidz.update',$item) }}" class="modal-content asrama-form">@csrf @method('PUT')<div class="modal-header"><h5>Edit Penugasan</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="form-group"><label>Jabatan</label><input required name="jabatan" class="form-control" value="{{ $item->jabatan }}"></div><div class="form-group"><label>Nomor identitas</label><input name="nomor_identitas" class="form-control" value="{{ $item->nomor_identitas }}"></div><div class="row"><div class="col-6"><label>Mulai</label><input type="date" name="tanggal_mulai" class="form-control" value="{{ $item->tanggal_mulai?->toDateString() }}"></div><div class="col-6"><label>Selesai</label><input type="date" name="tanggal_selesai" class="form-control" value="{{ $item->tanggal_selesai?->toDateString() }}"></div></div><div class="form-group mt-3"><label>Catatan</label><textarea name="catatan" class="form-control">{{ $item->catatan }}</textarea></div><div class="custom-control custom-switch"><input id="asatidzActive{{ $item->id }}" type="checkbox" name="is_active" value="1" class="custom-control-input" @checked($item->is_active)><label for="asatidzActive{{ $item->id }}" class="custom-control-label">Penugasan aktif</label></div></div><div class="modal-footer"><button class="btn btn-info">Simpan</button></div></form></div></div>@endforeach
@stop
@section('css') @include('asrama._styles') @stop
