@extends('adminlte::page')
@section('title', 'Santri Asrama')
@section('content_header') @stop
@section('content')
@include('asrama._alerts')
@php $heroTitle='Santri Asrama';$heroDescription='Assign siswa SIMANSA sebagai santri tanpa menggandakan data identitas.';$heroAction='<button class="btn btn-light" data-toggle="modal" data-target="#assignSantri"><i class="fas fa-user-plus mr-1"></i> Assign Santri</button>'; @endphp
@include('asrama._hero')
<div class="asrama-panel"><div class="asrama-panel__body asrama-form"><form method="get" class="row align-items-end"><div class="col-md-5"><label>Filter Unit</label><select name="asrama_id" class="form-control"><option value="">Semua unit</option>@foreach($units as $unit)<option value="{{ $unit->id }}" @selected($selectedUnit===$unit->id)>{{ $unit->nama }}</option>@endforeach</select></div><div class="col-md-2 mt-2"><button class="btn btn-info btn-block">Terapkan</button></div></form></div></div>
<div class="asrama-panel"><div class="table-responsive"><table class="table asrama-table"><thead><tr><th>No. Induk</th><th>Santri</th><th>Unit</th><th>Kelas Reguler</th><th>Masuk</th><th>Status</th><th></th></tr></thead><tbody>
@forelse($records as $item)<tr><td><code>{{ $item->nomor_induk_asrama }}</code></td><td><strong>{{ $item->siswa->nama_lengkap }}</strong><br><small>NISN {{ $item->siswa->nisn }}</small></td><td>{{ $item->asrama->nama }}</td><td>{{ $item->siswa->kelasTahunAktif->first()?->nama_kelas ?? '-' }}</td><td>{{ $item->tanggal_masuk?->format('d/m/Y')??'-' }}</td><td><span class="asrama-badge {{ $item->status==='aktif'?'asrama-badge--active':'asrama-badge--muted' }}">{{ ucfirst($item->status) }}</span></td><td><button class="btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#editSantri{{ $item->id }}">Edit</button></td></tr>
@empty<tr><td colspan="7" class="asrama-empty"><i class="fas fa-user-graduate"></i>Belum ada santri.</td></tr>@endforelse
</tbody></table></div><div class="p-3">{{ $records->links() }}</div></div>
<div class="modal fade" id="assignSantri"><div class="modal-dialog modal-lg"><form method="post" action="{{ route('asrama.santri.store') }}" class="modal-content asrama-form">@csrf<div class="modal-header"><h5>Assign Siswa sebagai Santri</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="form-group"><label>Unit Asrama</label><select required name="asrama_id" class="form-control">@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->nama }}</option>@endforeach</select></div><div class="form-group"><label>Pilih Siswa</label><select required multiple name="siswa_ids[]" class="form-control" size="12">@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->nama_lengkap }} · {{ $student->nis_lokal ?: $student->nisn }}</option>@endforeach</select><small class="form-text text-muted">Gunakan Ctrl/Command untuk memilih lebih dari satu.</small></div><div class="row"><div class="col-md-6"><label>Nomor induk (khusus satu siswa)</label><input name="nomor_induk_asrama" class="form-control"></div><div class="col-md-6"><label>Tanggal masuk</label><input type="date" name="tanggal_masuk" class="form-control" value="{{ now()->toDateString() }}"></div></div></div><div class="modal-footer"><button class="btn btn-info">Assign Santri</button></div></form></div></div>
@foreach($records as $item)<div class="modal fade" id="editSantri{{ $item->id }}"><div class="modal-dialog"><form method="post" action="{{ route('asrama.santri.update',$item) }}" class="modal-content asrama-form">@csrf @method('PUT')<div class="modal-header"><h5>Edit {{ $item->siswa->nama_lengkap }}</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="form-group"><label>Nomor induk</label><input required name="nomor_induk_asrama" class="form-control" value="{{ $item->nomor_induk_asrama }}"></div><div class="row"><div class="col-6"><label>Tanggal masuk</label><input type="date" name="tanggal_masuk" class="form-control" value="{{ $item->tanggal_masuk?->toDateString() }}"></div><div class="col-6"><label>Tanggal keluar</label><input type="date" name="tanggal_keluar" class="form-control" value="{{ $item->tanggal_keluar?->toDateString() }}"></div></div><div class="form-group mt-3"><label>Status</label><select name="status" class="form-control"><option value="aktif" @selected($item->status==='aktif')>Aktif</option><option value="nonaktif" @selected($item->status==='nonaktif')>Nonaktif</option></select></div><div class="form-group"><label>Catatan</label><textarea name="catatan" class="form-control">{{ $item->catatan }}</textarea></div></div><div class="modal-footer"><button class="btn btn-info">Simpan</button></div></form></div></div>@endforeach
@stop
@section('css') @include('asrama._styles') @stop
