@extends('adminlte::page')

@section('title', 'Integrasi Moodle')
@section('content_header')
<div class="row mb-2"><div class="col-sm-6"><h1><i class="fas fa-cloud text-primary mr-2"></i>Integrasi Moodle</h1></div><div class="col-sm-6"><ol class="breadcrumb float-sm-right"><li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li><li class="breadcrumb-item active">Integrasi Moodle</li></ol></div></div>
@stop

@section('content')
<div class="moodle-sync-page">
<div class="card bg-gradient-primary text-white mb-4"><div class="card-body"><div class="row align-items-center"><div class="col-lg-8"><div class="text-uppercase small font-weight-bold mb-2 opacity-75"><i class="fas fa-arrows-rotate mr-1"></i> SIMANSA → Moodle</div><h2 class="mb-2">Sinkronisasi data yang terkontrol</h2><p class="mb-0">Tinjau perubahan terlebih dahulu, konfirmasi, lalu pantau prosesnya secara live. SIMANSA tetap menjadi sumber data utama.</p></div><div class="col-lg-4 mt-3 mt-lg-0"><div class="hero-status"><span class="d-block small">Status koneksi</span><strong><i class="fas fa-circle mr-1"></i>{{ $integration->last_test_status === 'success' ? 'Terhubung' : 'Belum dites' }}</strong><small class="d-block mt-1">{{ $integration->last_tested_at ? 'Tes terakhir '.$integration->last_tested_at->format('d M Y H:i') : 'Tes koneksi diperlukan sebelum sync' }}</small></div></div></div></div></div>
<div class="row mb-4">@foreach([['Siswa',$preview['students'],'user dengan NISN'],['GTK',$preview['gtk'],'user dengan NIK'],['Kohor',$preview['cohorts'],number_format($preview['members']).' anggota'],['Kategori',$preview['categories'],number_format($preview['category_items']).' item']] as $metric)<div class="col-6 col-lg-3 mb-3 mb-lg-0"><div class="metric-card"><span>{{ $metric[0] }}</span><strong>{{ number_format($metric[1]) }}</strong><small>{{ $metric[2] }}</small></div></div>@endforeach</div>
<div class="row"><div class="col-xl-5 mb-4"><div class="card card-outline card-primary h-100"><div class="card-header"><h3 class="card-title"><i class="fas fa-sliders-h mr-2"></i>Konfigurasi koneksi</h3></div><form method="POST" action="{{ route('admin.moodle-sync.update') }}">@csrf @method('PUT')<div class="card-body"><div class="form-group"><label>Nama koneksi</label><input name="name" class="form-control" value="{{ old('name', $integration->name) }}" required></div><div class="form-group"><label>URL Moodle</label><input type="url" name="base_url" class="form-control" value="{{ old('base_url', $integration->base_url) }}" required></div><div class="form-group"><label>Token Web Service</label><input type="password" name="webservice_token" class="form-control" placeholder="Kosongkan jika tidak ingin mengubah token"><small class="text-muted">Token disimpan terenkripsi dan tidak pernah ditampilkan.</small></div><div class="form-group"><label>Domain email siswa</label><input name="student_email_domain" class="form-control" value="{{ old('student_email_domain', $integration->student_email_domain) }}" required></div>@foreach(['enabled'=>'Aktifkan integrasi','sync_users'=>'Sinkronkan user siswa dan GTK','sync_cohorts'=>'Sinkronkan kohor rombel','sync_categories'=>'Sinkronkan kategori kursus'] as $id => $label)<div class="custom-control custom-switch mb-2"><input type="checkbox" class="custom-control-input" id="{{ $id }}" name="{{ $id }}" value="1" @checked($integration->{$id})><label class="custom-control-label" for="{{ $id }}">{{ $label }}</label></div>@endforeach</div><div class="card-footer d-flex justify-content-between"><button class="btn btn-primary"><i class="fas fa-save mr-1"></i>Simpan</button><button type="button" id="moodle-test-connection" class="btn btn-outline-success"><i class="fas fa-plug mr-1"></i>Tes koneksi</button></div></form></div></div>
<div class="col-xl-7 mb-4"><div class="card card-outline card-info h-100"><div class="card-header"><h3 class="card-title"><i class="fas fa-route mr-2"></i>Preview dan sinkronisasi</h3><span class="badge badge-{{ $integration->last_test_status === 'success' ? 'success' : 'secondary' }}">{{ $integration->last_test_status === 'success' ? 'Terhubung' : 'Belum dites' }}</span></div><div class="card-body"><div class="callout callout-info mb-4"><h5 class="mb-1"><i class="fas fa-eye mr-1"></i> Selalu preview dahulu</h5><p class="mb-0">Klik salah satu aksi untuk melihat jumlah perubahan sebelum data dikirim ke Moodle. Sistem tidak menghapus akun, kohor, atau kategori Moodle.</p></div><div class="sync-actions"><button class="btn btn-outline-primary sync-preview" data-type="users"><i class="fas fa-users mr-1"></i>Preview user</button><button class="btn btn-outline-info sync-preview" data-type="cohorts"><i class="fas fa-layer-group mr-1"></i>Preview kohor</button><button class="btn btn-outline-warning sync-preview" data-type="categories"><i class="fas fa-folder mr-1"></i>Preview kategori</button><button class="btn btn-primary sync-preview" data-type="all"><i class="fas fa-sync mr-1"></i>Preview semua</button></div></div><div class="card-footer small text-muted"><i class="fas fa-shield-alt text-primary mr-1"></i> Tidak ada perubahan pada tahap preview.</div></div></div></div>
<div class="card card-outline card-secondary"><div class="card-header"><h3 class="card-title"><i class="fas fa-history mr-2"></i>Riwayat sinkronisasi</h3></div><div class="card-body p-0 table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Waktu</th><th>Jenis</th><th>Status</th><th>Ringkasan</th><th>Pesan</th></tr></thead><tbody>@forelse($runs as $run)<tr><td>{{ $run->started_at?->format('d M Y H:i') ?: $run->created_at?->format('d M Y H:i') }}</td><td>{{ strtoupper($run->type) }}</td><td><span class="badge badge-{{ $run->status === 'success' ? 'success' : ($run->status === 'failed' ? 'danger' : 'warning') }}">{{ ucfirst($run->status) }}</span></td><td>{{ collect($run->summary ?: [])->only(['created','updated','failed'])->map(fn($value,$key) => "$key: $value")->implode(' · ') ?: '—' }}</td><td class="text-muted">{{ $run->error ?: '—' }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">Belum ada riwayat sinkronisasi.</td></tr>@endforelse</tbody></table></div></div>
</div>
@stop

@section('css')<style>.moodle-sync-page .card{border-radius:12px}.moodle-sync-page .hero-status{padding:1rem 1.1rem;border:1px solid rgba(255,255,255,.35);border-radius:12px;background:rgba(0,0,0,.12)}.moodle-sync-page .hero-status strong{font-size:1.35rem}.moodle-sync-page .metric-card{height:100%;padding:1rem;border:1px solid #e2e8f0;border-radius:12px;background:#fff;box-shadow:0 5px 16px rgba(30,64,175,.06)}.moodle-sync-page .metric-card span,.moodle-sync-page .metric-card strong,.moodle-sync-page .metric-card small{display:block}.moodle-sync-page .metric-card span{font-size:.78rem;text-transform:uppercase;font-weight:700;color:#64748b}.moodle-sync-page .metric-card strong{font-size:1.6rem;color:#1e3a8a}.moodle-sync-page .metric-card small{color:#64748b}.moodle-sync-page .sync-actions{display:flex;flex-wrap:wrap;gap:.6rem}.moodle-sync-page .sync-progress{height:12px;border-radius:20px}.moodle-sync-page .sync-progress .progress-bar{transition:width .35s ease}</style>@endsection

@section('js')
<script>/*
$(function(){const csrf=document.querySelector('meta[name="csrf-token"]').content, previewUrl=@json(route('admin.moodle-sync.preview')), startUrl=@json(route('admin.moodle-sync.start')), progressUrl=@json(route('admin.moodle-sync.progress',['run'=>'__RUN__'])), labels={users:'user siswa dan GTK',cohorts:'kohor rombel',categories:'kategori kursus',all:'seluruh data'}, number=n=>new Intl.NumberFormat('id-ID').format(n||0), request=(url,body)=>fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrf,'Accept':'application/json'},body:JSON.stringify(body)}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message||'Permintaan gagal.');return d;});
function watch(id){const poll=()=>fetch(progressUrl.replace('__RUN__',id),{headers:{Accept:'application/json'}}).then(r=>r.json()).then(d=>{const box=Swal.getHtmlContainer();if(!box)return;const bar=box.querySelector('.sync-progress .progress-bar'),stage=box.querySelector('.sync-stage'),counts=box.querySelector('.sync-counts');if(bar){bar.style.width=d.percent+'%';bar.textContent=d.percent+'%'}if(stage)stage.textContent=d.stage||'Memproses';if(counts)counts.textContent=`${number(d.processed)} / ${number(d.total)} item`;if(['success','failed'].includes(d.status)){Swal.close();if(d.status==='success')toastr.success(`Sinkronisasi selesai. Dibuat ${number(d.summary.created)}, diperbarui ${number(d.summary.updated)}, gagal ${number(d.summary.failed)}.`);else toastr.error(d.error||'Sinkronisasi gagal.');setTimeout(()=>location.reload(),700);return}setTimeout(poll,1500)}).catch(()=>setTimeout(poll,2500));poll()}
$('.sync-preview').on('click',function(){const type=$(this).data('type');Swal.fire({title:'Menyiapkan preview…',html:'Membaca data SIMANSA dan menghitung rencana perubahan.',allowOutsideClick:false,didOpen:()=>Swal.showLoading()});request(previewUrl,{type}).then(d=>{const p=d.preview;return Swal.fire({icon:'info',title:'Preview '+labels[type],html:`<div class="text-muted small mb-3">${d.message}</div><div class="row text-center"><div class="col-6 mb-3"><strong class="d-block h4 mb-0">${number(p.students)}</strong><small>Siswa</small></div><div class="col-6 mb-3"><strong class="d-block h4 mb-0">${number(p.gtk)}</strong><small>GTK</small></div><div class="col-6"><strong class="d-block h4 mb-0">${number(p.cohorts)}</strong><small>Kohor</small></div><div class="col-6"><strong class="d-block h4 mb-0">${number(p.category_items)}</strong><small>Item kategori</small></div></div><div class="alert alert-warning mt-3 mb-0">Perkiraan total item: <strong>${number(d.total)}</strong>.</div>`,showCancelButton:true,confirmButtonText:'Mulai sinkronisasi',cancelButtonText:'Batal',confirmButtonColor:'#2563eb'})}).then(r=>{if(!r.isConfirmed)return Swal.fire({icon:'warning',title:'Konfirmasi dibatalkan',timer:1200,showConfirmButton:false});return Swal.fire({icon:'warning',title:'Konfirmasi sinkronisasi',text:`Jalankan sinkronisasi ${labels[type]} sekarang?`,showCancelButton:true,confirmButtonText:'Ya, mulai',cancelButtonText:'Batal',confirmButtonColor:'#2563eb'}).then(c=>{if(!c.isConfirmed)return;return request(startUrl,{type}).then(s=>{Swal.fire({title:'Sinkronisasi berjalan',html:'<div class="sync-stage mb-2">Menyiapkan data</div><div class="progress sync-progress mb-2"><div class="progress-bar bg-primary" style="width:0%">0%</div></div><div class="sync-counts small text-muted">0 item</div>',allowOutsideClick:false,showConfirmButton:false});watch(s.run_id)})})}).catch(e=>Swal.fire({icon:'error',title:'Tidak dapat melanjutkan',text:e.message}))})})
});
*/</script>
<script>
document.addEventListener('DOMContentLoaded', function () {
    const csrf = document.querySelector('meta[name="csrf-token"]')?.content || '';
    const testButton = document.getElementById('moodle-test-connection');
    const previewUrl = @json(route('admin.moodle-sync.preview'));
    const startUrl = @json(route('admin.moodle-sync.start'));
    const progressUrl = @json(route('admin.moodle-sync.progress', ['run' => '__RUN__']));
    const labels = {users:'user siswa dan GTK', cohorts:'kohor rombel', categories:'kategori kursus', all:'seluruh data'};
    const number = value => new Intl.NumberFormat('id-ID').format(value || 0);
    const notify = (type, message) => window.toastr && typeof window.toastr[type] === 'function' ? window.toastr[type](message) : window.alert(message);
    const post = (url, body) => fetch(url, {method:'POST', headers:{'Content-Type':'application/json', 'X-CSRF-TOKEN':csrf, 'Accept':'application/json'}, body:JSON.stringify(body || {})}).then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Permintaan gagal.'); return data; });
    const confirmAction = (options) => window.Swal ? Swal.fire(options) : Promise.resolve({isConfirmed: window.confirm(options.text || options.title || 'Lanjutkan?')});

    document.addEventListener('click', function (event) {
        if (!testButton || event.target.closest('#moodle-test-connection') !== testButton) return;
        event.preventDefault();
        event.stopImmediatePropagation();
        const openProgress = () => window.Swal ? Swal.fire({title:'Menguji koneksi Moodle', html:'<div class="moodle-live-stage">Menghubungi Web Service Moodle...</div><div class="progress moodle-progress mt-3"><div class="progress-bar" style="width:20%">20%</div></div><div class="moodle-live-log small text-muted mt-3 text-left">[20%] Permintaan koneksi dikirim</div>', allowOutsideClick:false, showConfirmButton:false}) : Promise.resolve();
        (window.Swal ? Swal.fire({icon:'question', title:'Tes koneksi Moodle?', text:'Sistem akan menghubungi Moodle tanpa mengubah data.', showCancelButton:true, confirmButtonText:'Ya, tes koneksi', cancelButtonText:'Batal', confirmButtonColor:'#2563eb'}) : Promise.resolve({isConfirmed:window.confirm('Tes koneksi Moodle sekarang?')})).then(result => { if (!result.isConfirmed) return; return openProgress().then(() => post(@json(route('admin.moodle-sync.test'))).then(data => { if(window.Swal) Swal.update({icon:'success', title:'Koneksi berhasil', html:'<div class="moodle-live-log text-left">[100%] '+data.message+'</div>', showConfirmButton:true, confirmButtonText:'Tutup'}); else notify('success', data.message); }).catch(error => { if(window.Swal) Swal.update({icon:'error', title:'Tes koneksi gagal', html:'<div class="moodle-live-log text-left">[100%] '+error.message+'</div>', showConfirmButton:true, confirmButtonText:'Tutup'}); else notify('error', error.message); }));
    }, true);
    if (testButton) testButton.addEventListener('click', function () {
        testButton.disabled = true;
        testButton.innerHTML = '<i class="fas fa-spinner fa-spin mr-1"></i>Menguji...';
        post(@json(route('admin.moodle-sync.test'))).then(data => { notify('success', data.message); setTimeout(() => window.location.reload(), 700); }).catch(error => notify('error', error.message)).finally(() => { testButton.disabled = false; testButton.innerHTML = '<i class="fas fa-plug mr-1"></i>Tes koneksi'; });
    });

    document.addEventListener('click', function (event) {
        const button = event.target.closest('.sync-preview');
        if (!button) return;
        event.preventDefault();
        event.stopImmediatePropagation();
        const type = button.dataset.type;
        const loading = window.Swal ? Swal.fire({title:'Menyiapkan preview…', text:'Membaca data SIMANSA.', allowOutsideClick:false, showConfirmButton:false, didOpen:() => Swal.showLoading()}) : Promise.resolve();
        loading.then(() => post(previewUrl, {type})).then(data => {
            const p = data.preview;
            return confirmAction({icon:'info', title:'Preview '+labels[type], html:`<p>${data.message}</p><div class="row text-center"><div class="col-6"><strong class="d-block h4">${number(p.students)}</strong><small>Siswa</small></div><div class="col-6"><strong class="d-block h4">${number(p.gtk)}</strong><small>GTK</small></div><div class="col-6"><strong class="d-block h4">${number(p.cohorts)}</strong><small>Kohor</small></div><div class="col-6"><strong class="d-block h4">${number(p.category_items)}</strong><small>Item kategori</small></div></div><div class="alert alert-warning mt-3">Perkiraan item: <strong>${number(data.total)}</strong></div>`, text:`Akan memproses sekitar ${number(data.total)} item.`, showCancelButton:true, confirmButtonText:'Mulai sinkronisasi', cancelButtonText:'Batal', confirmButtonColor:'#2563eb'}).then(result => result.isConfirmed ? post(startUrl, {type}) : null);
        }).then(start => {
            if (!start) return;
            if (window.Swal) Swal.fire({title:'Sinkronisasi berjalan', html:'<div class="sync-stage mb-2">Menyiapkan data</div><div class="progress sync-progress"><div class="progress-bar" style="width:0%">0%</div></div><div class="sync-counts small text-muted mt-2">0 item</div><div class="moodle-live-log text-left small mt-3">[0%] Menunggu worker Moodle</div>', allowOutsideClick:false, showConfirmButton:false});
            const poll = () => fetch(progressUrl.replace('__RUN__', start.run_id), {headers:{Accept:'application/json'}}).then(response => response.json()).then(data => { if (window.Swal && Swal.getHtmlContainer()) { const box=Swal.getHtmlContainer(), bar=box.querySelector('.progress-bar'), stage=box.querySelector('.sync-stage'), counts=box.querySelector('.sync-counts'); if(bar){bar.style.width=data.percent+'%';bar.textContent=data.percent+'%';} if(stage)stage.textContent=data.stage || 'Memproses'; if(counts)counts.textContent=`${number(data.processed)} / ${number(data.total)} item`; } if(['success','failed'].includes(data.status)){ if(window.Swal) Swal.close(); notify(data.status === 'success' ? 'success' : 'error', data.status === 'success' ? 'Sinkronisasi selesai.' : (data.error || 'Sinkronisasi gagal.')); setTimeout(() => window.location.reload(), 700); return; } setTimeout(poll, 1500); }).catch(() => setTimeout(poll, 2500));
            poll();
        }).catch(error => { if(window.Swal) Swal.fire({icon:'error', title:'Tidak dapat melanjutkan', text:error.message}); else notify('error', error.message); });
    }, true);
});
</script>
@endsection
