@extends('adminlte::page')

@section('title', 'Integrasi Moodle')
@section('content_header')
<div class="d-flex justify-content-between align-items-center flex-wrap mb-2"><div><h1 class="mb-1"><i class="fas fa-cloud text-primary mr-2"></i>Integrasi Moodle</h1><p class="text-muted mb-0">Kelola user, GTK, kohor, dan kategori kursus dari data SIMANSA.</p></div></div>
@stop

@section('content')
<div class="moodle-sync-page">
    @if(session('toastr_success'))<div class="alert alert-success border-0 shadow-sm"><i class="fas fa-check-circle mr-2"></i>{{ session('toastr_success') }}</div>@endif
    @if(session('toastr_error'))<div class="alert alert-danger border-0 shadow-sm"><i class="fas fa-exclamation-circle mr-2"></i>{{ session('toastr_error') }}</div>@endif
    <div class="row"><div class="col-xl-5 mb-4"><div class="card card-outline card-primary sync-card h-100"><div class="card-header"><h3 class="card-title"><i class="fas fa-sliders-h mr-2"></i>Konfigurasi koneksi</h3></div><form method="POST" action="{{ route('admin.moodle-sync.update') }}">@csrf @method('PUT')<div class="card-body"><div class="form-group"><label>Nama koneksi</label><input name="name" class="form-control" value="{{ old('name', $integration->name) }}" required></div><div class="form-group"><label>URL Moodle</label><input type="url" name="base_url" class="form-control" value="{{ old('base_url', $integration->base_url) }}" required></div><div class="form-group"><label>Token Web Service</label><input type="password" name="webservice_token" class="form-control" placeholder="Kosongkan jika tidak ingin mengubah token"><small class="text-muted">Token disimpan terenkripsi dan tidak pernah ditampilkan kembali.</small></div><div class="form-group"><label>Domain email siswa</label><input name="student_email_domain" class="form-control" value="{{ old('student_email_domain', $integration->student_email_domain) }}" required></div><div class="custom-control custom-switch mb-2"><input type="checkbox" class="custom-control-input" id="enabled" name="enabled" value="1" @checked($integration->enabled)><label class="custom-control-label" for="enabled">Aktifkan integrasi</label></div><div class="custom-control custom-switch mb-2"><input type="checkbox" class="custom-control-input" id="sync_users" name="sync_users" value="1" @checked($integration->sync_users)><label class="custom-control-label" for="sync_users">Sinkronkan user siswa dan GTK</label></div><div class="custom-control custom-switch mb-2"><input type="checkbox" class="custom-control-input" id="sync_cohorts" name="sync_cohorts" value="1" @checked($integration->sync_cohorts)><label class="custom-control-label" for="sync_cohorts">Sinkronkan kohor rombel</label></div><div class="custom-control custom-switch"><input type="checkbox" class="custom-control-input" id="sync_categories" name="sync_categories" value="1" @checked($integration->sync_categories)><label class="custom-control-label" for="sync_categories">Sinkronkan kategori kursus</label></div></div><div class="card-footer d-flex justify-content-between"><button class="btn btn-primary"><i class="fas fa-save mr-1"></i>Simpan</button><button type="submit" formaction="{{ route('admin.moodle-sync.test') }}" formmethod="POST" class="btn btn-outline-success"><i class="fas fa-plug mr-1"></i>Tes koneksi</button></div></form></div></div>
    <div class="col-xl-7 mb-4"><div class="card card-outline card-info sync-card h-100"><div class="card-header"><h3 class="card-title"><i class="fas fa-route mr-2"></i>Rencana sinkronisasi</h3><span class="badge badge-{{ $integration->last_test_status === 'success' ? 'success' : 'secondary' }}">{{ $integration->last_test_status === 'success' ? 'Terhubung' : 'Belum dites' }}</span></div><div class="card-body"><div class="row mb-4"><div class="col-6 col-md-3"><div class="metric"><small>Siswa</small><strong>{{ number_format($preview['students']) }}</strong></div></div><div class="col-6 col-md-3"><div class="metric"><small>GTK</small><strong>{{ number_format($preview['gtk']) }}</strong></div></div><div class="col-6 col-md-3"><div class="metric"><small>Kohor</small><strong>{{ number_format($preview['cohorts']) }}</strong></div></div><div class="col-6 col-md-3"><div class="metric"><small>Tahun kategori</small><strong>{{ number_format($preview['categories']) }}</strong></div></div></div><div class="sync-note"><i class="fas fa-shield-alt text-primary mr-2"></i><div><strong>SIMANSA adalah sumber data utama.</strong><p class="mb-0 text-muted">Sinkronisasi hanya membuat atau memperbarui data. Akun dan kursus Moodle tidak dihapus otomatis.</p></div></div><div class="d-flex flex-wrap mt-4"><form method="POST" action="{{ route('admin.moodle-sync.sync') }}" class="mr-2 mb-2 sync-form">@csrf<input type="hidden" name="type" value="users"><button class="btn btn-outline-primary"><i class="fas fa-users mr-1"></i>Sync user</button></form><form method="POST" action="{{ route('admin.moodle-sync.sync') }}" class="mr-2 mb-2 sync-form">@csrf<input type="hidden" name="type" value="cohorts"><button class="btn btn-outline-info"><i class="fas fa-layer-group mr-1"></i>Sync kohor</button></form><form method="POST" action="{{ route('admin.moodle-sync.sync') }}" class="mr-2 mb-2 sync-form">@csrf<input type="hidden" name="type" value="categories"><button class="btn btn-outline-warning"><i class="fas fa-folder-tree mr-1"></i>Sync kategori</button></form><form method="POST" action="{{ route('admin.moodle-sync.sync') }}" class="mb-2 sync-form">@csrf<input type="hidden" name="type" value="all"><button class="btn btn-primary"><i class="fas fa-sync mr-1"></i>Sync semua</button></form></div></div><div class="card-footer small text-muted">{{ $integration->last_tested_at ? 'Tes terakhir: '.$integration->last_tested_at->format('d M Y H:i').' — '.$integration->last_test_message : 'Tes koneksi diperlukan sebelum sinkronisasi.' }}</div></div></div></div>
    <div class="card card-outline card-secondary sync-card"><div class="card-header"><h3 class="card-title"><i class="fas fa-history mr-2"></i>Riwayat sinkronisasi</h3></div><div class="card-body p-0 table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Waktu</th><th>Jenis</th><th>Status</th><th>Ringkasan</th><th>Pesan</th></tr></thead><tbody>@forelse($runs as $run)<tr><td>{{ $run->started_at?->format('d M Y H:i') }}</td><td>{{ strtoupper($run->type) }}</td><td><span class="badge badge-{{ $run->status === 'success' ? 'success' : ($run->status === 'failed' ? 'danger' : 'warning') }}">{{ ucfirst($run->status) }}</span></td><td>{{ collect($run->summary ?: [])->map(fn($value,$key) => "$key: $value")->implode(' · ') }}</td><td class="text-muted">{{ $run->error ?: '—' }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">Belum ada riwayat sinkronisasi.</td></tr>@endforelse</tbody></table></div></div>
</div>
@stop

@section('css')<style>.moodle-sync-page .sync-card{border-radius:12px}.moodle-sync-page .card-header{display:flex;justify-content:space-between;align-items:center}.moodle-sync-page .metric{border:1px solid #e5eaf2;border-radius:10px;padding:13px;background:#f8faff}.moodle-sync-page .metric small,.moodle-sync-page .metric strong{display:block}.moodle-sync-page .metric small{color:#6c757d}.moodle-sync-page .metric strong{font-size:1.35rem;color:#243b70}.moodle-sync-page .sync-note{display:flex;align-items:flex-start;padding:14px;border-radius:10px;background:#f4f7ff}.moodle-sync-page table thead th{background:#f7f9fc;border-top:0;font-size:.76rem;text-transform:uppercase;color:#536273}</style>@endsection
@section('js')<script>$(function(){$('.sync-form').on('submit',function(e){if(!confirm('Jalankan sinkronisasi Moodle sekarang? Proses akan dicatat di riwayat.'))e.preventDefault();});});</script>@endsection
