@extends('adminlte::page')

@section('title', 'Anggota Rombel ke Kohor')

@section('content_header')
<div class="d-flex justify-content-between align-items-center mb-2"><div><h1 class="mb-1"><i class="fas fa-users-cog text-primary mr-2"></i>Anggota Rombel ke Kohor</h1><p class="text-muted mb-0">Rekonsiliasi membership Moodle berdasarkan rombel aktif SIMANSA.</p></div><ol class="breadcrumb mb-0"><li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li><li class="breadcrumb-item"><a href="{{ route('admin.moodle-sync.index') }}">Moodle</a></li><li class="breadcrumb-item active">Anggota Rombel</li></ol></div>
@stop

@section('content')
<div class="moodle-membership-page">
    <div class="card bg-gradient-primary text-white compact-hero"><div class="card-body"><div class="d-flex flex-wrap justify-content-between align-items-center"><div><div class="eyebrow">SIMANSA → MOODLE</div><h2 class="mb-1">Kelola anggota kohor secara terkontrol</h2><p class="mb-0 text-white-50">Preview membandingkan siswa aktif pada tahun ajaran aktif. Moodle belum diubah sampai Anda menyetujui hasilnya.</p></div><div class="hero-year mt-2 mt-md-0"><i class="fas fa-calendar-alt mr-1"></i>{{ $activeYear?->nama ?: 'Tahun aktif belum ditentukan' }}</div></div></div></div>
    <div class="card card-outline card-primary filter-card"><div class="card-header"><h3 class="card-title"><i class="fas fa-filter text-primary mr-1"></i>Ruang lingkup</h3><span class="text-muted small">Siswa aktif + rombel aktif</span></div><div class="card-body"><div class="row align-items-end"><div class="col-md-3"><label for="membership-level">Tingkat</label><select id="membership-level" class="form-control"><option value="">Semua tingkat</option><option value="10">X</option><option value="11">XI</option><option value="12">XII</option></select></div><div class="col-md-5"><label for="membership-classes">Rombel <small class="text-muted">(kosongkan untuk semua)</small></label><select id="membership-classes" class="form-control" multiple></select></div><div class="col-md-4 d-flex mt-3 mt-md-0"><button type="button" id="membership-preview" class="btn btn-primary mr-2 flex-fill"><i class="fas fa-search mr-1"></i>Preview perubahan</button><button type="button" id="membership-reset" class="btn btn-outline-secondary"><i class="fas fa-undo"></i></button></div></div><div class="scope-note mt-3"><i class="fas fa-shield-alt text-success mr-1"></i>Anggota manual di Moodle tidak dihapus. Sistem hanya mengelola siswa SIMANSA yang terdeteksi berdasarkan username/NISN.</div></div></div>
    <div id="membership-result" class="d-none"><div class="row compact-stats"><div class="col-sm-6 col-lg-3"><div class="stat-card"><small>Rombel diperiksa</small><strong id="stat-total">0</strong></div></div><div class="col-sm-6 col-lg-3"><div class="stat-card stat-warning"><small>Perlu penyesuaian</small><strong id="stat-ready">0</strong></div></div><div class="col-sm-6 col-lg-3"><div class="stat-card stat-success"><small>Tambah anggota</small><strong id="stat-add">0</strong></div></div><div class="col-sm-6 col-lg-3"><div class="stat-card stat-danger"><small>Keluarkan anggota</small><strong id="stat-remove">0</strong></div></div></div><div class="card card-outline card-primary data-card"><div class="card-header d-flex justify-content-between align-items-center"><div><h3 class="card-title mb-1">Preview anggota rombel</h3><div class="small text-muted" id="preview-message">Moodle belum diubah.</div></div><button type="button" id="membership-apply" class="btn btn-success btn-sm" disabled><i class="fas fa-check mr-1"></i>Terapkan perubahan</button></div><div class="card-body p-0"><div class="table-responsive"><table id="membership-table" class="table table-hover mb-0"><thead><tr><th>Rombel SIMANSA</th><th>Kohor Moodle</th><th>SIMANSA</th><th>Moodle</th><th>Tambah</th><th>Keluarkan</th><th>Status</th></tr></thead><tbody></tbody></table></div></div></div></div>
    <div id="membership-empty" class="empty-state"><i class="fas fa-users-slash"></i><h4>Belum ada preview</h4><p>Pilih tingkat atau rombel, lalu jalankan preview untuk melihat perbedaan membership.</p></div>
</div>
@stop

@push('css')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ttskch/select2-bootstrap4-theme@1.5.2/dist/select2-bootstrap4.min.css"><link rel="stylesheet" href="https://cdn.datatables.net/1.13.8/css/dataTables.bootstrap4.min.css">
<style>
.moodle-membership-page .compact-hero{border:0;border-radius:1rem;box-shadow:0 10px 24px rgba(37,99,235,.16)}.moodle-membership-page .compact-hero .card-body{padding:1.25rem 1.5rem}.moodle-membership-page .eyebrow{font-size:.7rem;letter-spacing:.12em;font-weight:700;opacity:.8}.moodle-membership-page .compact-hero h2{font-size:1.35rem}.moodle-membership-page .hero-year{padding:.55rem .8rem;border:1px solid rgba(255,255,255,.3);border-radius:.6rem;font-size:.8rem}.moodle-membership-page .filter-card,.moodle-membership-page .data-card{border-radius:.85rem}.moodle-membership-page label{font-size:.78rem;font-weight:700;color:#475569}.moodle-membership-page .form-control{min-height:40px;border-radius:.55rem;border-color:#dbe3ef}.moodle-membership-page .select2-container{width:100%!important}.moodle-membership-page .select2-selection{border-color:#dbe3ef!important;border-radius:.55rem!important;min-height:40px!important}.moodle-membership-page .scope-note{padding:.65rem .8rem;border-radius:.55rem;background:#f0fdf4;color:#64748b;font-size:.78rem}.moodle-membership-page .compact-stats{margin-bottom:1rem}.moodle-membership-page .stat-card{height:100%;padding:1rem 1.1rem;background:#fff;border:1px solid #e2e8f0;border-radius:.8rem;box-shadow:0 4px 15px rgba(15,23,42,.04)}.moodle-membership-page .stat-card small,.moodle-membership-page .stat-card strong{display:block}.moodle-membership-page .stat-card small{color:#64748b;font-weight:700}.moodle-membership-page .stat-card strong{font-size:1.7rem;color:#0f172a}.moodle-membership-page .stat-warning{border-left:3px solid #f59e0b}.moodle-membership-page .stat-success{border-left:3px solid #10b981}.moodle-membership-page .stat-danger{border-left:3px solid #ef4444}.moodle-membership-page .data-card thead th{font-size:.7rem;color:#64748b;text-transform:uppercase;letter-spacing:.04em;white-space:nowrap}.moodle-membership-page .data-card td{font-size:.82rem;vertical-align:middle}.moodle-membership-page .status-badge{display:inline-block;padding:.3rem .5rem;border-radius:999px;font-size:.7rem;font-weight:700;background:#e0f2fe;color:#075985}.moodle-membership-page .status-needs_sync{background:#fef3c7;color:#92400e}.moodle-membership-page .status-missing_user{background:#fee2e2;color:#991b1b}.moodle-membership-page .status-missing_cohort,.moodle-membership-page .status-ambiguous{background:#f1f5f9;color:#475569}.moodle-membership-page .empty-state{padding:3.5rem 1rem;text-align:center;border:1px dashed #cbd5e1;border-radius:.85rem;background:#fff;color:#64748b}.moodle-membership-page .empty-state i{font-size:2rem;color:#c4b5fd}.moodle-membership-page .empty-state h4{margin:.8rem 0 .25rem;color:#334155;font-size:1.05rem}
</style>
@endpush

@push('js')
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script><script src="https://cdn.datatables.net/1.13.8/js/jquery.dataTables.min.js"></script><script src="https://cdn.datatables.net/1.13.8/js/dataTables.bootstrap4.min.js"></script>
<script>
$(function(){var csrf=document.querySelector('meta[name="csrf-token"]')?.getAttribute('content')||'',previewUrl=@json(route('admin.moodle-sync.memberships.preview')),classesUrl=@json(route('admin.moodle-sync.memberships.classes')),applyUrl=@json(route('admin.moodle-sync.memberships.apply')),progressUrl=@json(route('admin.moodle-sync.progress',['run'=>'__RUN__'])),pauseUrl=@json(route('admin.moodle-sync.runs.pause',['run'=>'__RUN__'])),resumeUrl=@json(route('admin.moodle-sync.runs.resume',['run'=>'__RUN__'])),stopUrl=@json(route('admin.moodle-sync.runs.stop',['run'=>'__RUN__'])),token=null,table=null;
var esc=function(v){return $('<div>').text(v||'-').html();};var post=function(url,data){return fetch(url,{method:'POST',headers:{'Accept':'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify(data||{})}).then(function(r){return r.json().then(function(d){if(!r.ok)throw new Error(d.message||'Permintaan gagal.');return d;});});};
var classes=$('#membership-classes').select2({theme:'bootstrap4',placeholder:'Cari rombel...',allowClear:true,ajax:{url:classesUrl,dataType:'json',delay:250,data:function(p){return{q:p.term,tingkat:$('#membership-level').val()};},processResults:function(d){return d;}}});$('#membership-level').on('change',function(){classes.val(null).trigger('change');});
var label=function(s){return{s:'Sesuai',needs_sync:'Perlu disesuaikan',missing_user:'Ada user belum tersedia',missing_cohort:'Kohor belum ditemukan',ambiguous:'Kohor ganda'}[s]||s;};
$('#membership-preview').on('click',function(){var b=$(this);b.prop('disabled',true).html('<i class="fas fa-spinner fa-spin mr-1"></i>Membandingkan...');var ids=classes.val()||[];post(previewUrl,{tingkat:$('#membership-level').val()||null,local_ids:ids}).then(function(d){token=d.preview_token;$('#membership-empty').addClass('d-none');$('#membership-result').removeClass('d-none');$('#stat-total').text(d.summary.total);$('#stat-ready').text(d.summary.ready);$('#stat-add').text(d.summary.add);$('#stat-remove').text(d.summary.remove);$('#preview-message').text(d.message+' User belum ada: '+d.summary.missing_user+'.');$('#membership-apply').prop('disabled',!(d.summary.add||d.summary.remove));if(table)table.destroy();table=$('#membership-table').DataTable({data:d.records,autoWidth:false,pageLength:10,order:[[0,'asc']],columns:[{data:'class',render:esc},{data:'cohort_name',render:esc},{data:'local_count'},{data:'moodle_count',render:function(v){return v===null?'-':v;}},{data:'add_count'},{data:'remove_count'},{data:'status',render:function(v){return '<span class="status-badge status-'+esc(v)+'">'+esc(label(v))+'</span>';}}],language:{emptyTable:'Belum ada data',lengthMenu:'Tampilkan _MENU_ data',search:'Cari:',info:'Menampilkan _START_–_END_ dari _TOTAL_ data',infoEmpty:''}});}).catch(function(e){window.toastr&&toastr.error(e.message);}).finally(function(){b.prop('disabled',false).html('<i class="fas fa-search mr-1"></i>Preview perubahan');});});
var progress=function(id){var html='<div class="text-left"><div id="mp-stage" class="font-weight-bold text-center mb-2">Menyiapkan...</div><div class="progress mb-2"><div id="mp-bar" class="progress-bar bg-primary" style="width:0%">0%</div></div><div id="mp-count" class="small text-muted text-center mb-2">0 item</div><div id="mp-logs" style="max-height:180px;overflow:auto;background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:8px">Menunggu log...</div></div>';Swal.fire({title:'Penyesuaian anggota berjalan',html:html,showConfirmButton:false,allowOutsideClick:false});var poll=function(){fetch(progressUrl.replace('__RUN__',id),{headers:{Accept:'application/json'}}).then(function(r){return r.json();}).then(function(d){if(!$('#mp-bar').length)return;$('#mp-stage').text((d.stage||'Memproses')+' ('+d.percent+'%)');$('#mp-bar').css('width',d.percent+'%').text(d.percent+'%');$('#mp-count').text(d.processed+' / '+d.total+' item');var logs=(d.summary&&d.summary.logs)||[];$('#mp-logs').html(logs.slice(-10).map(function(x){return '<div class="small border-bottom py-1"><b>'+esc(x.class)+'</b> — '+esc(x.message)+'</div>';}).join('')||'Menunggu log...');if(['success','failed','stopped'].indexOf(d.status)>=0){clearInterval(timer);Swal.close();if(d.status==='success')toastr&&toastr.success('Penyesuaian anggota selesai.');else toastr&&toastr.warning(d.status==='stopped'?'Proses dihentikan.':'Proses gagal.');setTimeout(function(){location.reload();},800);}});};var timer=setInterval(poll,700);poll();};
$('#membership-apply').on('click',function(){if(!token)return;var s=$('#stat-add').text(),r=$('#stat-remove').text();Swal.fire({icon:'warning',title:'Terapkan membership Moodle?',html:'<p>Tambah <b>'+s+'</b> anggota dan keluarkan <b>'+r+'</b> anggota dari kohor terkelola SIMANSA.</p><label class="d-block text-left"><input type="checkbox" id="membership-confirm"> Saya memahami perubahan ini akan mengubah membership Moodle.</label>',showCancelButton:true,confirmButtonText:'Ya, terapkan',cancelButtonText:'Batal',preConfirm:function(){if(!$('#membership-confirm').prop('checked')){Swal.showValidationMessage('Centang persetujuan terlebih dahulu.');return false;}return true;}}).then(function(x){if(!x.isConfirmed)return;post(applyUrl,{preview_token:token,confirmed:true}).then(function(d){toastr&&toastr.success(d.message);progress(d.run_id);}).catch(function(e){toastr&&toastr.error(e.message);});});});$('#membership-reset').on('click',function(){location.reload();});});
</script>
@endpush
