@extends('adminlte::page')

@section('title', 'Pengaturan API Moodle')

@section('content_header')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="mb-1"><i class="fas fa-sliders-h text-primary mr-2"></i>Pengaturan API Moodle</h1><p class="text-muted mb-0">Kelola koneksi Web Service untuk Smart Check.</p></div><a href="{{ route('admin.moodle-sync.index') }}" class="btn btn-outline-primary"><i class="fas fa-arrow-left mr-1"></i>Smart Check Users</a></div>
@stop

@section('content')
<div class="row"><div class="col-lg-8"><div class="card card-outline card-primary"><div class="card-header"><h3 class="card-title">Konfigurasi koneksi</h3></div><form method="POST" action="{{ route('admin.moodle-sync.update') }}">@csrf @method('PUT')<div class="card-body"><div class="form-group"><label>Nama koneksi</label><input name="name" class="form-control" value="{{ old('name', $integration->name) }}" required></div><div class="form-group"><label>URL Moodle</label><input type="url" name="base_url" class="form-control" value="{{ old('base_url', $integration->base_url) }}" required></div><div class="form-group"><label>Token Web Service</label><input type="password" name="webservice_token" class="form-control" placeholder="Kosongkan untuk mempertahankan token"><small class="text-muted">Token tersimpan terenkripsi dan tidak pernah ditampilkan.</small></div><div class="form-group"><label>Domain email siswa</label><input name="student_email_domain" class="form-control" value="{{ old('student_email_domain', $integration->student_email_domain) }}" required></div><div class="custom-control custom-switch mb-2"><input type="checkbox" class="custom-control-input" id="enabled" name="enabled" value="1" @checked($integration->enabled)><label class="custom-control-label" for="enabled">Aktifkan integrasi</label></div><div class="custom-control custom-switch mb-2"><input type="checkbox" class="custom-control-input" id="sync_users" name="sync_users" value="1" @checked($integration->sync_users)><label class="custom-control-label" for="sync_users">Izinkan pengelolaan user</label></div><div class="custom-control custom-switch mb-2"><input type="checkbox" class="custom-control-input" id="sync_cohorts" name="sync_cohorts" value="1" @checked($integration->sync_cohorts)><label class="custom-control-label" for="sync_cohorts">Izinkan pengelolaan kohor</label></div><div class="custom-control custom-switch"><input type="checkbox" class="custom-control-input" id="sync_categories" name="sync_categories" value="1" @checked($integration->sync_categories)><label class="custom-control-label" for="sync_categories">Izinkan pengelolaan kategori</label></div></div><div class="card-footer"><button class="btn btn-primary"><i class="fas fa-save mr-1"></i>Simpan pengaturan</button></div></form></div></div><div class="col-lg-4"><div class="card card-outline card-info"><div class="card-header"><h3 class="card-title">Status keamanan</h3></div><div class="card-body"><p><i class="fas fa-shield-halved text-success mr-2"></i>Token terenkripsi</p><p><i class="fas fa-eye text-info mr-2"></i>Smart Check bersifat read-only</p><p class="mb-0"><i class="fas fa-user-lock text-warning mr-2"></i>Perubahan wajib melalui konfirmasi</p></div></div></div></div>
@stop
