@extends('adminlte::page')
@section('title', 'Standar Penugasan GTK')
@section('content_header')
<div class="row mb-2"><div class="col-sm-6"><h1><i class="fas fa-sliders-h text-primary"></i> Standar Penugasan GTK</h1></div><div class="col-sm-6"><ol class="breadcrumb float-sm-right"><li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li><li class="breadcrumb-item"><a href="{{ route('admin.penugasan-gtk.index') }}">Penugasan GTK</a></li><li class="breadcrumb-item active">Standar</li></ol></div></div>
@stop
@section('content')
<div class="assignment-types-page">
@if(session('success'))<div class="alert alert-success"><i class="fas fa-check-circle mr-1"></i>{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><strong>Data belum dapat disimpan.</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card bg-gradient-primary text-white mb-3"><div class="card-body py-3"><div class="row align-items-center"><div class="col-lg-8"><h4 class="mb-1"><i class="fas fa-book-open mr-2"></i>Master Jenis & Ekuivalensi</h4><p class="mb-0">Perubahan standar hanya berlaku untuk penugasan baru. Nilai pada SK dan histori lama tidak ikut berubah.</p></div><div class="col-lg-4 text-lg-right mt-3 mt-lg-0"><a href="{{ route('admin.penugasan-gtk.index') }}" class="btn btn-light btn-sm"><i class="fas fa-arrow-left"></i> Kembali</a> <button class="btn btn-success btn-sm" id="addType" data-toggle="modal" data-target="#typeModal"><i class="fas fa-plus"></i> Jenis Baru</button></div></div></div></div>
<div class="card card-outline card-primary"><div class="card-header"><h3 class="card-title"><i class="fas fa-list mr-1"></i> Daftar Standar</h3><div class="card-tools"><span class="badge badge-info">KMA 736/2026</span></div></div><div class="card-body"><div class="table-responsive"><table class="table table-hover table-bordered"><thead><tr><th>Jenis Penugasan</th><th>Kategori</th><th class="text-center">Ekuivalensi</th><th class="text-center">Minimum Mengajar</th><th>Ketentuan</th><th>Dasar</th><th>Status</th><th class="text-right">Aksi</th></tr></thead><tbody>
@foreach($types as $type)
@php($typeRecord = $type->only(['kode','nama','kelompok','kategori','ekuivalensi_jtm','minimal_jtm_mengajar','jenis_unit','maks_pemegang','wajib_sk','dapat_dirangkap','dasar_hukum','berlaku_mulai','berlaku_selesai','is_active']))
<tr><td><strong>{{ $type->nama }}</strong><small class="d-block text-muted">{{ $type->kode }}@if($type->kelompok) · kelompok {{ $type->kelompok }}@endif</small><small class="d-block text-muted">{{ $type->assignments_count }} histori penugasan</small></td><td><span class="badge badge-{{ $type->kategori==='penuh'?'dark':($type->kategori==='utama'?'primary':'info') }}">{{ ucfirst($type->kategori) }}</span></td><td class="text-center"><strong>{{ $type->ekuivalensi_jtm }} JTM</strong></td><td class="text-center">{{ $type->minimal_jtm_mengajar }} JTM</td><td><small>@if($type->jenis_unit)<span class="d-block"><i class="fas fa-map-marker-alt"></i> Unit: {{ $type->jenis_unit }}</span>@endif<span class="d-block"><i class="fas fa-users"></i> Maks: {{ $type->maks_pemegang ?: 'sesuai kebutuhan/rasio' }}</span><span class="d-block"><i class="fas fa-file-signature"></i> SK {{ $type->wajib_sk?'wajib':'opsional' }}</span><span class="d-block"><i class="fas fa-layer-group"></i> {{ $type->dapat_dirangkap?'Dapat dirangkap':'Tidak dirangkap' }}</span></small></td><td><small>{{ $type->dasar_hukum ?: '-' }}</small><small class="d-block text-muted">{{ $type->berlaku_mulai?->format('d/m/Y') ?: '-' }} s.d. {{ $type->berlaku_selesai?->format('d/m/Y') ?: 'berlaku' }}</small></td><td><span class="badge badge-{{ $type->is_active?'success':'secondary' }}">{{ $type->is_active?'Aktif':'Nonaktif' }}</span></td><td class="text-right"><button class="btn btn-sm btn-primary edit-type" data-toggle="modal" data-target="#typeModal" data-url="{{ route('admin.penugasan-gtk.types.update',$type) }}" data-record='@json($typeRecord)'><i class="fas fa-edit"></i></button></td></tr>
@endforeach
</tbody></table></div></div></div>
</div>

<div class="modal fade" id="typeModal" tabindex="-1"><div class="modal-dialog modal-lg"><form method="POST" action="{{ route('admin.penugasan-gtk.types.store') }}" class="modal-content">@csrf<div id="typeMethod"></div><div class="modal-header"><h5 class="modal-title"><i class="fas fa-sliders-h mr-1"></i><span id="typeModalTitle">Jenis Penugasan Baru</span></h5><button class="close" type="button" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="row">
<div class="col-md-4"><div class="form-group"><label>Kode <span class="text-danger">*</span></label><input name="kode" class="form-control" required placeholder="contoh: kepala_lab_bahasa"></div></div><div class="col-md-8"><div class="form-group"><label>Nama Penugasan <span class="text-danger">*</span></label><input name="nama" class="form-control" required></div></div>
<div class="col-md-4"><div class="form-group"><label>Kelompok</label><input name="kelompok" class="form-control" placeholder="waka, kepala_unit, tugas_lain"></div></div><div class="col-md-4"><div class="form-group"><label>Kategori <span class="text-danger">*</span></label><select name="kategori" class="form-control" required><option value="penuh">Penuh</option><option value="utama">Tugas tambahan utama</option><option value="lain" selected>Tugas tambahan lain</option></select></div></div><div class="col-md-4"><div class="form-group"><label>Jenis Unit</label><input name="jenis_unit" class="form-control" placeholder="laboratorium/bidang/kegiatan"></div></div>
<div class="col-md-4"><div class="form-group"><label>Ekuivalensi JTM <span class="text-danger">*</span></label><input type="number" min="0" max="40" name="ekuivalensi_jtm" class="form-control" required value="0"></div></div><div class="col-md-4"><div class="form-group"><label>Minimum JTM Mengajar <span class="text-danger">*</span></label><input type="number" min="0" max="40" name="minimal_jtm_mengajar" class="form-control" required value="18"></div></div><div class="col-md-4"><div class="form-group"><label>Maksimum Pemegang</label><input type="number" min="1" max="99" name="maks_pemegang" class="form-control" placeholder="Kosong = berdasarkan kebutuhan"></div></div>
<div class="col-md-6"><div class="form-group"><label>Dasar Hukum</label><input name="dasar_hukum" class="form-control" value="KMA Nomor 736 Tahun 2026"></div></div><div class="col-md-3"><div class="form-group"><label>Berlaku Mulai</label><input type="date" name="berlaku_mulai" class="form-control" value="2026-07-01"></div></div><div class="col-md-3"><div class="form-group"><label>Berlaku Selesai</label><input type="date" name="berlaku_selesai" class="form-control"></div></div>
<div class="col-12"><div class="d-flex flex-wrap type-switches"><div class="custom-control custom-switch mr-4"><input type="checkbox" class="custom-control-input" id="typeRequiresSk" name="wajib_sk" value="1" checked><label class="custom-control-label" for="typeRequiresSk">Wajib SK</label></div><div class="custom-control custom-switch mr-4"><input type="checkbox" class="custom-control-input" id="typeStackable" name="dapat_dirangkap" value="1"><label class="custom-control-label" for="typeStackable">Dapat dirangkap</label></div><div class="custom-control custom-switch"><input type="checkbox" class="custom-control-input" id="typeActive" name="is_active" value="1" checked><label class="custom-control-label" for="typeActive">Aktif</label></div></div></div>
</div><div class="alert alert-info mt-3 mb-0"><i class="fas fa-shield-alt mr-1"></i>Jangan mengubah standar hanya untuk menyesuaikan satu guru. Gunakan nilai master sesuai regulasi; penugasan lama tetap menyimpan snapshotnya.</div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button><button class="btn btn-primary"><i class="fas fa-save mr-1"></i>Simpan Standar</button></div></form></div></div>
@stop
@section('css')<style>.assignment-types-page table{font-size:.8rem}.assignment-types-page .type-switches{padding:.75rem;background:#f8fafc;border:1px solid #e2e8f0;border-radius:.4rem}.assignment-types-page .modal textarea{resize:vertical}</style>@stop
@section('js')<script>$(function(){const modal=$('#typeModal'),form=modal.find('form'),createUrl=@json(route('admin.penugasan-gtk.types.store'));$('#addType').on('click',function(){form[0].reset();form.attr('action',createUrl);$('#typeMethod').empty();$('#typeModalTitle').text('Jenis Penugasan Baru');$('[name="dasar_hukum"]').val('KMA Nomor 736 Tahun 2026');$('[name="berlaku_mulai"]').val('2026-07-01');$('#typeRequiresSk,#typeActive').prop('checked',true);});$('.edit-type').on('click',function(){const record=$(this).data('record');form[0].reset();form.attr('action',$(this).data('url'));$('#typeMethod').html('<input type="hidden" name="_method" value="PUT">');$('#typeModalTitle').text('Perbarui Standar Penugasan');Object.keys(record).forEach(key=>{const input=form.find('[name="'+key+'"]');if(input.attr('type')==='checkbox')input.prop('checked',!!record[key]);else {let value=record[key]??'';if(typeof value==='string'&&value.includes('T'))value=value.split('T')[0];input.val(value);}});});@if($errors->any())$('#addType').trigger('click');@endif});</script>@stop
