@extends('adminlte::page')
@section('title', 'Beban Kerja GTK')
@section('content_header')
<div class="row mb-2"><div class="col-sm-6"><h1><i class="fas fa-balance-scale text-primary"></i> Beban Kerja GTK</h1></div><div class="col-sm-6"><ol class="breadcrumb float-sm-right"><li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li><li class="breadcrumb-item"><a href="{{ route('admin.penugasan-gtk.index') }}">Penugasan GTK</a></li><li class="breadcrumb-item active">Beban Kerja</li></ol></div></div>
@stop
@section('content')
<div class="gtk-workload-page">
<div class="card bg-gradient-primary text-white mb-3"><div class="card-body py-3"><div class="row align-items-center"><div class="col-lg-8"><h4 class="mb-1"><i class="fas fa-chart-bar mr-2"></i>Rekap Jam Mengajar & Ekuivalensi</h4><p class="mb-0">Jam aktual berasal dari jadwal, sedangkan ekuivalensi berasal dari penugasan resmi aktif. Keduanya tetap ditampilkan terpisah.</p></div><div class="col-lg-4 text-lg-right mt-3 mt-lg-0"><a href="{{ route('admin.penugasan-gtk.index') }}" class="btn btn-light btn-sm"><i class="fas fa-arrow-left"></i> Penugasan GTK</a></div></div></div></div>
<div class="row">@foreach([['GTK Terhitung',$stats['gtk'],'primary'],['Memenuhi',$stats['memenuhi'],'success'],['Kurang',$stats['kurang'],'warning'],['Perlu Verifikasi',$stats['review'],'danger']] as [$label,$value,$color])<div class="col-6 col-xl-3"><div class="card workload-stat border-{{ $color }}"><div class="card-body"><small>{{ $label }}</small><h3 class="text-{{ $color }}">{{ number_format($value) }}</h3></div></div></div>@endforeach</div>
<div class="card card-outline card-primary"><div class="card-header"><h3 class="card-title"><i class="fas fa-users mr-1"></i>{{ $gtk ? 'Beban Kerja '.$gtk->nama_lengkap : 'Rekap Seluruh GTK' }}</h3></div><div class="card-body">
<form method="GET" class="workload-filter mb-3"><div class="row"><div class="col-md-4"><label>Tahun Pelajaran</label><select name="tahun_pelajaran_id" class="form-control">@foreach($years as $item)<option value="{{ $item->id }}" @selected($year?->id===$item->id)>{{ $item->nama }}</option>@endforeach</select></div><div class="col-md-3"><label>Semester</label><select name="semester" class="form-control"><option value="1" @selected($semester===1)>Ganjil</option><option value="2" @selected($semester===2)>Genap</option></select></div>@if($gtk)<input type="hidden" name="gtk_id" value="{{ $gtk->id }}"><div class="col-md-3"><label>GTK</label><input class="form-control" value="{{ $gtk->nama_lengkap }}" disabled></div>@endif<div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary btn-block"><i class="fas fa-sync-alt"></i> Tampilkan</button></div></div></form>
<div class="table-responsive"><table class="table table-hover table-bordered"><thead><tr><th>GTK</th><th class="text-center">Mengajar</th><th class="text-center">Ekuivalensi</th><th class="text-center">Total</th><th>Rincian Penugasan</th><th>Status</th></tr></thead><tbody>@forelse($rows as $row)@php($colors=['memenuhi'=>'success','kurang'=>'warning','lebih'=>'danger','review'=>'danger'])<tr><td><div class="d-flex"><img src="{{ $row['gtk']->foto_profile_url }}" class="workload-photo mr-2" alt=""><div><strong>{{ $row['gtk']->nama_lengkap }}</strong><small class="d-block text-muted">{{ $row['gtk']->nip ?: 'NIP -' }} · {{ $row['gtk']->jenis_ptk ?: 'GTK' }}</small><a class="small" href="{{ route('admin.gtk.schedule',$row['gtk']) }}"><i class="fas fa-calendar-alt"></i> Lihat jadwal</a></div></div></td><td class="text-center"><strong>{{ $row['jtm_mengajar'] }}</strong><small class="d-block text-muted">JTM aktual</small></td><td class="text-center"><strong class="text-primary">{{ $row['jtm_ekuivalensi'] }}</strong><small class="d-block text-muted">JTM diakui</small></td><td class="text-center"><span class="workload-total">{{ $row['jtm_total'] }}</span><small class="d-block text-muted">JTM tercatat</small></td><td>@forelse($row['tugas_tambahan'] as $task)<div class="task-line {{ $task['diakui'] ? '' : 'text-muted' }}"><i class="fas {{ $task['diakui'] ? 'fa-check-circle text-success' : 'fa-info-circle' }} mr-1"></i>{{ $task['label'] }} <span class="badge badge-light">{{ $task['jtm_diakui'] }}/{{ $task['jtm'] }} JTM</span>@if($task['catatan'])<small class="d-block ml-3 text-warning">{{ $task['catatan'] }}</small>@endif</div>@empty<span class="text-muted">Tidak ada ekuivalensi</span>@endforelse @foreach($row['warnings'] as $warning)<small class="d-block text-danger mt-1"><i class="fas fa-exclamation-triangle"></i> {{ $warning }}</small>@endforeach</td><td><span class="badge badge-{{ $colors[$row['status']] ?? 'secondary' }}">{{ ['memenuhi'=>'Memenuhi','kurang'=>'Kurang','lebih'=>'Lebih 40 JTM','review'=>'Perlu verifikasi'][$row['status']] ?? ucfirst($row['status']) }}</span></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">Belum ada jadwal atau penugasan pada periode ini.</td></tr>@endforelse</tbody></table></div>
<div class="alert alert-info mb-0"><i class="fas fa-info-circle mr-1"></i>Rekap ini adalah alat kontrol internal. Validasi final SKMT, SKBK, dan TPG tetap mengikuti ketentuan Kementerian Agama serta hasil verifikasi pejabat berwenang.</div>
</div></div></div>
@stop
@section('css')<style>.gtk-workload-page .workload-stat{border:1px solid #e2e8f0;border-top-width:3px;box-shadow:0 4px 14px rgba(15,23,42,.06)}.gtk-workload-page .workload-stat .card-body{padding:.8rem}.gtk-workload-page .workload-stat h3{margin:0;font-size:1.4rem;font-weight:700}.gtk-workload-page .workload-stat small{color:#64748b;font-weight:600}.gtk-workload-page .workload-filter{padding:.8rem;background:#f8fafc;border:1px solid #e2e8f0;border-radius:.4rem}.gtk-workload-page .workload-filter label{font-size:.75rem}.gtk-workload-page table{font-size:.82rem}.gtk-workload-page .workload-photo{width:42px;height:52px;object-fit:cover;border-radius:.35rem;border:1px solid #dbe3ef}.gtk-workload-page .workload-total{display:inline-flex;align-items:center;justify-content:center;width:42px;height:42px;border-radius:50%;background:#2563eb;color:#fff;font-weight:700;font-size:1rem}.gtk-workload-page .task-line+.task-line{margin-top:.3rem}</style>@stop
